import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestHealthgrades:
    
    def test_healthgrades_1a0d0ee6(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.33708561905975-input-group").clear()
        self.driver.find_element(By.ID, "0.33708561905975-input-group").send_keys("optometrist")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]/em[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='quick-filter--telehealth']/span[1]").click()
    
    def test_healthgrades_1bddb11a(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.4223421356630017-input-group").clear()
        self.driver.find_element(By.ID, "0.4223421356630017-input-group").send_keys("dentist")
        self.driver.find_element(By.ID, "0.22936273705926946-input-group").clear()
        self.driver.find_element(By.ID, "0.22936273705926946-input-group").send_keys("90210")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[3]/div[1]/div[1]/div[5]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Dr. Daniela Pavlin, DDS')]").click()
    
    def test_healthgrades_1c8c7da0(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.8185473519118971-input-group").clear()
        self.driver.find_element(By.ID, "0.8185473519118971-input-group").send_keys("neurosurgeon")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[9]/div[1]/div[1]/div[3]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[9]/div[1]/div[1]/div[4]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[9]/div[1]/div[1]/div[5]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[5]/div[1]/div[1]/div[3]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
    
    def test_healthgrades_1db97e87(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "top-searches--hero-link-4").click()
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[3]/div[1]/div[2]/a[4]/div[1]").click()
        self.driver.find_element(By.ID, "location-filter-input-group").clear()
        self.driver.find_element(By.ID, "location-filter-input-group").send_keys("new orleans")
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[1]/div[4]/section[1]/div[2]/div[1]/ul[1]/li[2]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.ID, "selectSpecialties").clear()
        self.driver.find_element(By.ID, "selectSpecialties").select("Primary Care")
        self.driver.find_element(By.ID, "newsletter-form-footer").clear()
        self.driver.find_element(By.ID, "newsletter-form-footer").send_keys("buckeye.foobar@gmail.com")
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/footer[1]/div[1]/div[3]/div[1]/form[1]/button[1]").click()
    
    def test_healthgrades_248803b0(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.41417660294542147-input-group").clear()
        self.driver.find_element(By.ID, "0.41417660294542147-input-group").send_keys("psychiatrist")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]/em[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='quick-filter--telehealth']/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[1]/div[1]/div[1]/div[4]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[5]/div[1]/div[1]/div[5]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Dr. Nathaniel Johns, MD')]").click()
    
    def test_healthgrades_000ada18(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.33943474706794796-input-group").clear()
        self.driver.find_element(By.ID, "0.33943474706794796-input-group").send_keys("primary care")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]/em[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='onetrust-close-btn-container']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[10]/div[1]/div[1]/div[2]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
    
    def test_healthgrades_e1f5d933(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.3774919234705696-input-group").clear()
        self.driver.find_element(By.ID, "0.3774919234705696-input-group").send_keys("dentist")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "0.18394885934439542-input-group").clear()
        self.driver.find_element(By.ID, "0.18394885934439542-input-group").send_keys("90028")
        self.driver.find_element(By.XPATH, "//div[@id='usearch-container']/main[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--rating']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[2]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
    
    def test_healthgrades_e3661b90(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.9719210181220865-input-group").clear()
        self.driver.find_element(By.ID, "0.9719210181220865-input-group").send_keys("dentist")
        self.driver.find_element(By.ID, "0.697052231725303-input-group").clear()
        self.driver.find_element(By.ID, "0.697052231725303-input-group").send_keys("98011")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.ID, "standard-filter--rating").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='search-results']/div[1]/div[2]/div[1]/div[1]/button[1]/span[2]").click()
        self.driver.find_element(By.ID, "sort-option-distance").click()
        self.driver.find_element(By.XPATH, "//div[@id='pro-card-featured-2WGJG']/div[1]").click()
    
    def test_healthgrades_a5aa692b(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a hospital')]").click()
        self.driver.find_element(By.ID, "0.9855496750530259-input-group").clear()
        self.driver.find_element(By.ID, "0.9855496750530259-input-group").send_keys("SSM Health Cardinal Glennon Children's Hospital")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Reviews')]").click()
    
    def test_healthgrades_aaf607f2(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.9441715697680066-input-group").clear()
        self.driver.find_element(By.ID, "0.9441715697680066-input-group").send_keys("acupuncture")
        self.driver.find_element(By.ID, "0.24700223222436657-input-group").clear()
        self.driver.find_element(By.ID, "0.24700223222436657-input-group").send_keys("Mountain Pass, CA")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--insurance']/svg[1]").click()
        self.driver.find_element(By.ID, "insurance-filter-input-group").clear()
        self.driver.find_element(By.ID, "insurance-filter-input-group").send_keys("Blue Cross Blue Shield")
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@role='menuitemradio' and @name='plan-type-filter-dropdown-select--btn-HPT0000407' and @type='button']").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--distance']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[5]/label[1]/span[2]/span[1]").click()
    
    def test_healthgrades_abf89604(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "pop-search-tab-3").click()
        self.driver.find_element(By.XPATH, "//a[@id='pop-search--procedures-knee-replacement']/span[2]/svg[2]").click()
        self.driver.find_element(By.ID, "0.8405719287015809-input-group").clear()
        self.driver.find_element(By.ID, "0.8405719287015809-input-group").send_keys("glendale")
        self.driver.find_element(By.XPATH, "//div[@id='usearch-container']/main[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[1]/div[1]/div[1]/div[1]/label[1]/span[2]/span[1]/span[1]/div[1]/span[1]/svg[1]/rect[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[5]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[9]/div[1]/div[1]/div[2]/label[1]/span[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[10]/div[1]/div[1]/div[2]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'View Profile')]").click()
    
    def test_healthgrades_970f88ad(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a hospital')]").click()
        self.driver.find_element(By.XPATH, "//span[@id='MegaMenuFindHospitalContainer']/span[1]/div[1]/div[4]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "N-subcategory-item--/new-york").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[2]/div[1]/div[1]/div[4]/label[1]/span[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'View Profile')]").click()
    
    def test_healthgrades_0fd6eca4(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.616055763247944-input-group").clear()
        self.driver.find_element(By.ID, "0.616055763247944-input-group").send_keys("dermatologist")
        self.driver.find_element(By.ID, "0.29566440157609364-input-group").clear()
        self.driver.find_element(By.ID, "0.29566440157609364-input-group").send_keys("10019")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--distance']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[3]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--insurance']/svg[1]").click()
        self.driver.find_element(By.ID, "insurance-filter-input-group").clear()
        self.driver.find_element(By.ID, "insurance-filter-input-group").send_keys("medicare")
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[2]/button[1]").click()
    
    def test_healthgrades_13978dfc(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Health A to Z')]").click()
        self.driver.find_element(By.XPATH, "//span[@id='MegaMenuHealthAZContainer']/span[1]/div[1]/div[4]/strong[2]").click()
        self.driver.find_element(By.XPATH, "//span[@id='MegaMenuHealthAZContainer']/span[1]/div[1]/div[4]/a[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Viagra')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Side effects')]").click()
    
    def test_healthgrades_a2ddc4cd(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Health A to Z')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Depression')]").click()
        self.driver.find_element(By.XPATH, "//label[contains(.,'No, undiagnosed')]").click()
        self.driver.find_element(By.XPATH, "//label[contains(.,'In-office visit')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(@href, 'link://https://www.healthgrades.com/right-care/depression/find-a-specialist-who-treats-depression?hid=connect_toolbar')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH' and @type='text' and @placeholder='City, State or ZIP']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH' and @type='text' and @placeholder='City, State or ZIP']").send_keys("denver")
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/div[12]/div[4]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/div[4]/div[3]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[5]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@value='gender' and @type='button']").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/div[11]/div[3]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[4]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/div[7]/div[3]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/div[2]/div[4]/label[7]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hggps']/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/button[1]").click()
    
    def test_healthgrades_ac2ef6f7(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.5679288458430847-input-group").clear()
        self.driver.find_element(By.ID, "0.5679288458430847-input-group").send_keys("primary care")
        self.driver.find_element(By.ID, "0.05587429885614914-input-group").clear()
        self.driver.find_element(By.ID, "0.05587429885614914-input-group").send_keys("chicago")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[10]/div[1]/div[1]/div[12]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
    
    def test_healthgrades_bc6f46ca(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a hospital')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Bariatric Surgery')]").click()
        self.driver.find_element(By.XPATH, "//section[@id='search-results']/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "sort-option-patientsatisfaction").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'View Profile')]").click()
    
    def test_healthgrades_cf75f837(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.618025363203915-input-group").clear()
        self.driver.find_element(By.ID, "0.618025363203915-input-group").send_keys("pediatrician")
        self.driver.find_element(By.ID, "0.7372450449920116-input-group").clear()
        self.driver.find_element(By.ID, "0.7372450449920116-input-group").send_keys("90028")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--specialty']/svg[1]/use[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[1]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--rating']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/div[2]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
    
    def test_healthgrades_d3c763fb(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.4800956043873914-input-group").clear()
        self.driver.find_element(By.ID, "0.4800956043873914-input-group").send_keys("primary care")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[5]/div[1]/div[1]/div[5]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[3]/div[1]/div[1]/div[1]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[1]/div[1]/div[1]/div[2]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
    
    def test_healthgrades_57a7153d(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.9606898207997223-input-group").clear()
        self.driver.find_element(By.ID, "0.9606898207997223-input-group").send_keys("dermatologist")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[5]/div[1]/div[1]/div[2]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[10]/div[1]/div[1]/div[6]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
    
    def test_healthgrades_7133792d(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.8964680369745299-input-group").clear()
        self.driver.find_element(By.ID, "0.8964680369745299-input-group").send_keys("Neurologist")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]/em[1]").click()
        self.driver.find_element(By.ID, "0.45880827566355276-input-group").clear()
        self.driver.find_element(By.ID, "0.45880827566355276-input-group").send_keys("New York")
        self.driver.find_element(By.XPATH, "//div[@id='usearch-container']/main[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'View Profile')]").click()
    
    def test_healthgrades_8aa9bddc(self):
        # self.driver.get("https://www.healthgrades.com/")
        self.driver.find_element(By.ID, "0.581095264485394-input-group").clear()
        self.driver.find_element(By.ID, "0.581095264485394-input-group").send_keys("allergy")
        self.driver.find_element(By.XPATH, "//form[@id='hero-search-bar']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "0.7644171572862428-input-group").clear()
        self.driver.find_element(By.ID, "0.7644171572862428-input-group").send_keys("stamford")
        self.driver.find_element(By.XPATH, "//div[@id='usearch-container']/main[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='quick-filter--nearby']/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='standard-filter--rating']/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='filter-bar']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[3]/div[1]/div[1]/div[3]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[2]/div[1]/fieldset[5]/div[1]/div[1]/div[4]/label[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='all-filters-modal']/section[1]/div[3]/button[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Schedule Now')]").click()
        self.driver.find_element(By.ID, "input-9").click()
        self.driver.find_element(By.XPATH, "//li[@role='button']").click()
        self.driver.find_element(By.ID, "select_12").click()
        self.driver.find_element(By.ID, "select_option_19").click()
        self.driver.find_element(By.XPATH, "//li[contains(.,'11am')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Continue to Visit Details')]").click()
        self.driver.find_element(By.XPATH, "//label[contains(.,'Me')]").click()
        self.driver.find_element(By.XPATH, "//label[contains(.,'No')]").click()
        self.driver.find_element(By.ID, "month").clear()
        self.driver.find_element(By.ID, "month").send_keys("5")
        self.driver.find_element(By.ID, "day").clear()
        self.driver.find_element(By.ID, "day").send_keys("5")
        self.driver.find_element(By.ID, "year").clear()
        self.driver.find_element(By.ID, "year").send_keys("1995")
        self.driver.find_element(By.ID, "comments").clear()
        self.driver.find_element(By.ID, "comments").send_keys("none")
        self.driver.find_element(By.XPATH, "//span[contains(.,'Continue to Contact Info')]").click()
    