import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from browser_helper import calculate_dates, switch_to_new_tab


@pytest.mark.usefixtures("setup_class")
class TestRyanair:
    
    # def test_ryanair_f02ef5ca(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Events & Activities')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Family Friendly')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[9]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[4]/div[6]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Get tickets')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[2]/button[2]/img[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/div[2]/button[2]/img[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/div[2]/button[2]/img[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/button[1]").click()
    #
    # def test_ryanair_490dc61c(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Plan')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Fare Finder')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@role='textbox' and @type='text' and @placeholder='']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='textbox' and @type='text' and @placeholder='']").send_keys("dresden")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Dresden')]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[2]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[2]/div[2]/div[1]/div[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Anywhere')]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'$ 150')]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'$ 100')]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,\"Let's go\")]").click()
    #
    # def test_ryanair_81b23d7b(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'hotels')]").click()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").clear()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").send_keys("DUBAI")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-14']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-locations-properties-container[1]/hp-room-search-locations-properties[1]/div[1]/hp-room-search-location-item[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Choose date')]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-15']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[5]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-15']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[4]/div[10]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-16']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[4]/div[19]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-17']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-rooms-container[1]/hp-room-search-rooms[1]/hp-rooms-picker[1]/ry-counter[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-17']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-rooms-container[1]/hp-room-search-rooms[1]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-17']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-rooms-container[1]/hp-room-search-rooms[1]/hp-rooms-picker[2]/ry-counter[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-17']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-rooms-container[1]/hp-room-search-rooms[1]/div[4]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/rooms-root[1]/rooms-list[1]/div[3]/div[1]/div[1]/rooms-filters-wrapper[1]/div[2]/rooms-filter-container[4]/rooms-star-rating-filter[1]/rooms-chip-list[1]/rooms-chip[5]/span[1]/icon[1]/span[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/rooms-root[1]/rooms-list[1]/div[3]/div[1]/div[1]/rooms-filters-wrapper[1]/div[2]/rooms-filter-container[7]/div[1]/rooms-property-facility-filter[1]/rooms-checkbox-list[1]/div[3]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/rooms-root[1]/rooms-list[1]/div[3]/div[1]/div[1]/rooms-filters-wrapper[1]/div[2]/rooms-filter-container[8]/div[1]/rooms-room-facility-filter[1]/rooms-checkbox-list[1]/div[8]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/rooms-root[1]/rooms-list[1]/div[3]/div[1]/div[1]/rooms-filters-wrapper[1]/div[2]/rooms-filter-container[8]/div[1]/rooms-room-facility-filter[1]/rooms-checkbox-list[1]/div[3]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/rooms-root[1]/rooms-list[1]/div[3]/div[1]/div[1]/rooms-filters-wrapper[1]/div[2]/rooms-filter-container[7]/div[1]/rooms-property-facility-filter[1]/rooms-checkbox-list[1]/div[13]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/rooms-root[1]/rooms-list[1]/div[3]/div[1]/div[1]/rooms-filters-wrapper[1]/div[2]/rooms-filter-container[9]/div[1]/rooms-accommodation-type-filter[1]/rooms-checkbox-list[1]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Distance from city centre')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Choose room')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Book now')]").click()
    #
    # def test_ryanair_333e1892(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'hotels')]").click()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").click()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").clear()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").send_keys("Dublin")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-locations-properties-container[1]/hp-room-search-locations-properties[1]/div[1]/hp-room-search-location-item[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Choose date')]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[3]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[2]/div[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[3]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-9']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-rooms-container[1]/hp-room-search-rooms[1]/hp-rooms-picker[1]/ry-counter[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-9']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-rooms-container[1]/hp-room-search-rooms[1]/div[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/div[1]/button[1]").click()
    #
    # def test_ryanair_3594153c(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Events & Activities')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[2]/li[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[2]/aside[1]/div[1]/section[1]/div[1]/div[2]/div[1]/div[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[3]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[3]/div[3]/div[1]/span[1]").click()
    #
    # def test_ryanair_400c291f(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/fsw-trip-type-container[1]/fsw-trip-type[1]/fsw-trip-type-button[2]/button[1]/icon[1]/span[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.ID, "input-button__departure").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-1']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-origin-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "input-button__destination").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/fsw-countries[1]/div[4]/div[4]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[2]/calendar-body[1]/div[5]/div[16]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-passengers-container[1]/fsw-passengers[1]/fsw-passengers-picker-container[1]/fsw-passengers-picker[1]/ry-counter[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-passengers-container[1]/fsw-passengers[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/div[1]/div[1]/div[1]/button[1]").click()
    #
    # def test_ryanair_4f75897b(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Plan')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Try Somewhere New')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Destinations')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='te-destinations-list']/div[1]/div[2]/div[3]/div[2]/ul[1]/li[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='te-destinations-list']/div[1]/div[2]/div[3]/div[2]/ul[1]/li[2]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='te-destinations-list']/div[1]/div[2]/div[3]/div[2]/ul[1]/li[3]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='te-destinations-list']/div[1]/div[2]/div[3]/div[2]/ul[1]/li[4]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='te-destinations-list']/h1[1]/div[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='te-destinations-list']/h1[1]/div[1]/div[1]/div[3]/div[2]").click()
    #     self.driver.find_element(By.ID, "te-destinations-filter-button").click()
    #
    # def test_ryanair_555dd7af(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//img[@alt='GIFT CARDS']").click()
    #     self.driver.find_element(By.XPATH, "//img[@title='Happy Birthday']").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//ry-dropdown-item[@id='GBP']/button[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/app-root[1]/div[1]/app-content[1]/lp-gift-vouchers[1]/gift-cards-container[1]/gift-cards[1]/form[1]/div[1]/div[1]/gift-cards-details-form[1]/gift-cards-amount-form[1]/section-layout[1]/div[2]/ry-dropdown[2]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-dropdown-item[@id='100']/button[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/app-root[1]/div[1]/app-content[1]/lp-gift-vouchers[1]/gift-cards-container[1]/gift-cards[1]/form[1]/div[1]/div[1]/gift-cards-details-form[1]/section-layout[1]/div[2]/ry-counter[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@name='message']").clear()
    #     self.driver.find_element(By.XPATH, "//textarea[@name='message']").send_keys("Happy Birthday Love")
    #     self.driver.find_element(By.XPATH, "//input[@name='customerName' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='customerName' and @type='text']").send_keys("Stuart Bloom")
    #     self.driver.find_element(By.XPATH, "//input[@name='firstName' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='firstName' and @type='text']").send_keys("Denise")
    #     self.driver.find_element(By.XPATH, "//input[@name='lastName' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='lastName' and @type='text']").send_keys("Bloom")
    #     self.driver.find_element(By.XPATH, "//input[@name='email' and @type='email']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='email' and @type='email']").send_keys("denise.bloom@bbt.com")
    #     self.driver.find_element(By.NAME, "firstName").clear()
    #     self.driver.find_element(By.NAME, "firstName").send_keys("Debbi")
    #     self.driver.find_element(By.NAME, "lastName").clear()
    #     self.driver.find_element(By.NAME, "lastName").send_keys("Wolowitz")
    #     self.driver.find_element(By.NAME, "email").clear()
    #     self.driver.find_element(By.NAME, "email").send_keys("debbi.wo@bbt.com")
    #     self.driver.find_element(By.XPATH, "/html/body[1]/app-root[1]/div[1]/app-content[1]/lp-gift-vouchers[1]/gift-cards-container[1]/gift-cards[1]/gift-cards-footer[1]/div[1]/div[2]/div[1]/div[1]/ry-checkbox[1]/label[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Go to checkout')]").click()
    #
    # def test_ryanair_725c38e7(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Events & Activities')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[14]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[4]/div[4]/div[1]/div[7]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[4]/div[4]/div[1]/div[7]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[2]/main[1]/section[1]/div[1]/div[1]/div[1]/div[1]/a[1]/h2[1]/div[1]/span[1]/span[1]").click()
    #
    # def test_ryanair_767faaa6(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Car Hire')]").click()
    #     self.driver.find_element(By.ID, "input-button__pick-up-location").clear()
    #     self.driver.find_element(By.ID, "input-button__pick-up-location").send_keys("berlin")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-17']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-pickup-location-container[1]/hp-car-hire-location[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-18']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-18']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[2]/calendar-body[1]/div[4]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-20']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[4]/div[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-19']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-time-selector-container[1]/hp-time-selector-list[1]/hp-time-selector-item[24]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-21']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-time-selector-container[1]/hp-time-selector-list[1]/hp-time-selector-item[23]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-spinner[contains(.,\"Let's go\")]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='partner-ryanair']/div[4]/div[5]/div[2]/div[1]/a[3]/div[5]").click()
    #     self.driver.find_element(By.XPATH, "//ul[@id='aircon-filter-content']/li[1]/label[1]/div[1]/ins[1]").click()
    #     self.driver.find_element(By.XPATH, "//ul[@id='groupsize-filter-content']/li[2]/label[1]/div[1]/ins[1]").click()
    #     self.driver.find_element(By.XPATH, "//ul[@id='card-filter-content']/li[2]/label[1]/div[1]/ins[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Show all 10 cars')]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='partner-ryanair']/div[4]/div[5]/div[3]/table[1]/tbody[1]/tr[3]/td[4]/a[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "radio_yes").click()
    #     self.driver.find_element(By.ID, "bookCta").click()
    
    def test_ryanair_edf748d4(self):
        # self.driver.get("http://ryanair.com/")

        # self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-search-widget-tabs-container[1]/button[3]/hp-search-widget-tab[1]").click()
        self.driver.find_element(By.XPATH, "//button[@aria-label='hotels']").click()

        # self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/hp-room-search-widget-controls-container[1]/hp-room-search-widget-controls[1]/div[1]/hp-input-button[1]/div[1]/div[1]").clear()
        # self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/hp-room-search-widget-controls-container[1]/hp-room-search-widget-controls[1]/div[1]/hp-input-button[1]/div[1]/div[1]").send_keys("jakarta")
        # self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/hp-room-search-widget-controls-container[1]/hp-room-search-widget-controls[1]/div[1]/hp-input-button[1]").clear()
        # self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/hp-room-search-widget-controls-container[1]/hp-room-search-widget-controls[1]/div[1]/hp-input-button[1]").send_keys("jakarta")
        # self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-locations-properties-container[1]/hp-room-search-locations-properties[1]/div[1]/hp-room-search-location-item[1]/div[1]").click()
        self.driver.find_element(By.ID, "input-button__locations-or-properties").clear()
        self.driver.find_element(By.ID, "input-button__locations-or-properties").send_keys("Jakarta")
        self.driver.find_element(By.XPATH, "//div[@class='tooltip-inner']//div[text()='Jakarta, Special Capital Region of Jakarta']").click()

        # self.driver.find_element(By.XPATH, "//div[contains(.,'Choose date')]").click()
        # self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-9']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[3]/div[2]").click()
        # self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-9']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[2]/div[10]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-10']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[2]/div[19]/div[1]").click()
        # self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-room-search-widget[1]/hp-app-room-search-widget[1]/hp-room-search-widget-container[1]/hp-room-search-widget[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.CSS_SELECTOR, "hp-input-button[uniqueid='check-in']").click()
        start_date_str, end_date_str = calculate_dates(14, 17)
        self.driver.find_element(By.XPATH, f"//div[@class='tooltip-inner']//div[@data-id='{start_date_str}']").click()
        self.driver.find_element(By.XPATH, f"//div[@class='tooltip-inner']//div[@data-id='{end_date_str}']").click()
        self.driver.find_element(By.XPATH, "//button[@data-ref='rooms-search-widget__cta']").click()

        # handle the cookie popup again
        # self.driver.find_element(By.XPATH, "//div[@id='cookie-popup-with-overlay']/div[1]/div[3]/button[2]").click()
        if self.driver.find_element(By.ID, "onetrust-accept-btn-handler") is not None:
            # wait for the cookie popup to be stable otherwise will have: selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted
            time.sleep(2)
            self.driver.find_element(By.ID, "onetrust-accept-btn-handler").click()

        # self.driver.find_element(By.XPATH, "//span[contains(.,'Lowest price')]").click()
        sort_by_dropdown = self.driver.find_element(By.ID, "sort-filter-dropdown-sort")
        sort_by_select = Select(sort_by_dropdown)
        sort_by_select.select_by_value("PRICE_LOW_TO_HIGH")

        # wait for a few seconds to let the result to be refreshed otherwise will click on a wrong result item
        time.sleep(2)

        # self.driver.find_element(By.XPATH, "//button[contains(.,'Choose room')]").click()
        self.driver.find_element(By.XPATH, "//div[@data-stid='property-listing-results']/div[1]//a[@data-stid='open-hotel-information']").click()
        switch_to_new_tab(self.driver)

        # self.driver.find_element(By.XPATH, "//button[contains(.,'Book now')]").click()
        self.driver.find_element(By.XPATH, "//button[@data-stid='sticky-button']").click()
        self.driver.find_element(By.XPATH, "//button[@data-stid='submit-hotel-reserve']").click()
        self.driver.find_element(By.XPATH, "//button[@data-stid='submit-hotel-reserve' and @type='submit' and ./span[text()='Pay now']]").click()


        # self.driver.find_element(By.XPATH, "//input[@name='firstName' and @type='text']").clear()
        # self.driver.find_element(By.XPATH, "//input[@name='firstName' and @type='text']").send_keys("Joe")
        # self.driver.find_element(By.XPATH, "//input[@name='firstSurname' and @type='text']").clear()
        # self.driver.find_element(By.XPATH, "//input[@name='firstSurname' and @type='text']").send_keys("Bloggs")
        # self.driver.find_element(By.ID, "email").clear()
        # self.driver.find_element(By.ID, "email").send_keys("buckeye.foobar@gmail.com")
        # self.driver.find_element(By.ID, "confirmEmail").clear()
        # self.driver.find_element(By.ID, "confirmEmail").send_keys("buckeye.foobar@gmail.com")
        # self.driver.find_element(By.XPATH, "//input[@name='phone' and @type='tel']").clear()
        # self.driver.find_element(By.XPATH, "//input[@name='phone' and @type='tel']").send_keys("1111111111111111")
        self.driver.find_element(By.NAME, "tripPreferencesRequest.hotelTripPreferences.hotelRoomPreferences[0].firstName").clear()
        self.driver.find_element(By.NAME, "tripPreferencesRequest.hotelTripPreferences.hotelRoomPreferences[0].firstName").send_keys("Joe")
        self.driver.find_element(By.NAME, "tripPreferencesRequest.hotelTripPreferences.hotelRoomPreferences[0].lastName").clear()
        self.driver.find_element(By.NAME, "tripPreferencesRequest.hotelTripPreferences.hotelRoomPreferences[0].lastName").send_keys("Bloggs")
        self.driver.find_element(By.XPATH, "//input[@name='email' and @type='email']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='email' and @type='email']").send_keys("buckeye.foobar@gmail.com")
        self.driver.find_element(By.NAME, "tripPreferencesRequest.hotelTripPreferences.hotelRoomPreferences[0].preferredPhoneNumber").clear()
        self.driver.find_element(By.NAME, "tripPreferencesRequest.hotelTripPreferences.hotelRoomPreferences[0].preferredPhoneNumber").send_keys("1111111111111111")
        self.driver.find_element(By.ID, "creditCardInput").clear()
        self.driver.find_element(By.ID, "creditCardInput").send_keys("1234567890123456")
        expiry_month_dropdown = self.driver.find_element(By.NAME, "expiration_month")
        expiry_month_select = Select(expiry_month_dropdown)
        expiry_month_select.select_by_value("7")
        expiry_year_dropdown = self.driver.find_element(By.NAME, "expiration_year")
        expiry_year_select = Select(expiry_year_dropdown)
        expiry_year_select.select_by_value("2026")
        self.driver.find_element(By.ID, "new_cc_security_code").clear()
        self.driver.find_element(By.ID, "new_cc_security_code").send_keys("123")
        self.driver.find_element(By.ID, "explicit-consent").click()
        self.driver.find_element(By.ID, "complete-booking").click()
    
    # def test_ryanair_2742f638(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.ID, "input-button__departure").clear()
    #     self.driver.find_element(By.ID, "input-button__departure").send_keys("TEL AVIV")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-1']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-origin-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "input-button__destination").clear()
    #     self.driver.find_element(By.ID, "input-button__destination").send_keys("VENICE")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[3]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[3]/div[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[4]/div[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Search')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Select')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Select')]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'more')]").click()
    #
    # def test_ryanair_3e50b35f(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'hotels')]").click()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").clear()
    #     self.driver.find_element(By.ID, "input-button__locations-or-properties").send_keys("Athens, Attica, Greeece")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-locations-properties-container[1]/hp-room-search-locations-properties[1]/div[1]/hp-room-search-location-item[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Choose date')]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[2]/calendar-body[1]/div[2]/div[16]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Choose date')]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-lazy-room-search-controls-tooltips[1]/hp-app-room-search-controls-tooltips[1]/hp-room-search-controls-tooltips-container[1]/hp-room-search-controls-tooltips[1]/hp-room-search-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[3]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-spinner[contains(.,'Search')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cookie-popup-with-overlay']/div[1]/div[3]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Lowest price')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Choose room')]").click()
    #
    # def test_ryanair_c5070129(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Plan')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Fare Finder')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@role='textbox' and @type='text' and @placeholder='']").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Dublin')]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[2]/main[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[2]/div[2]/div[1]/div[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Anywhere')]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[2]/main[1]/div[1]/div[1]/div[1]/form[1]/farefinder-budget-input[1]/div[2]/div[2]/div[1]/div[2]/core-icon[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'$ 150')]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,\"Let's go\")]").click()
    #
    # def test_ryanair_6d87b507(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.ID, "input-button__destination").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/fsw-countries[1]/div[3]/div[4]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//fsw-airport-item[@role='button']").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[2]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[2]/div[19]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[2]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Choose date')]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[3]/div[7]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/div[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Select')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Select')]").click()
    #
    # def test_ryanair_7219145b(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/fsw-trip-type-container[1]/fsw-trip-type[1]/fsw-trip-type-button[2]/button[1]/icon[1]/span[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.ID, "input-button__departure").clear()
    #     self.driver.find_element(By.ID, "input-button__departure").send_keys("faro")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-1']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-origin-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "input-button__destination").clear()
    #     self.driver.find_element(By.ID, "input-button__destination").send_keys("bournemouth")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[6]/div[19]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ry-checkbox[1]/label[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/div[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Select')]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/app-root[1]/flights-root[1]/div[1]/div[1]/div[1]/div[1]/flights-lazy-content[1]/fare-selector-container[1]/fare-selector[1]/div[1]/fare-table-container[1]/fare-table[1]/div[2]/ry-spinner[1]/div[1]/div[1]/div[1]/fare-card[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-portal[@id='ry-modal-portal']/div[1]/fare-upgrade-container[1]/fare-upgrade-component[1]/ry-dialog[1]/div[1]/div[1]/div[3]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/app-root[1]/flights-root[1]/div[1]/div[1]/div[1]/div[1]/flights-lazy-content[1]/flights-passengers[1]/pax-app-container[1]/pax-app[1]/ry-spinner[1]/ry-login-touchpoint-container[1]/ry-login-touchpoint[1]/div[1]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//ry-dropdown[@id='title-0-error-message']/div[2]/div[1]/div[1]/ry-dropdown-item[1]/button[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "form.passengers.ADT-0.name").clear()
    #     self.driver.find_element(By.ID, "form.passengers.ADT-0.name").send_keys("Joe")
    #     self.driver.find_element(By.ID, "form.passengers.ADT-0.surname").clear()
    #     self.driver.find_element(By.ID, "form.passengers.ADT-0.surname").send_keys("Bloggs")
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
    #     self.driver.find_element(By.XPATH, "//ry-portal[@id='ry-modal-portal']/div[1]/seats-modal[1]/ry-dialog[1]/div[1]/div[2]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//img[@alt='undefined']").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Continue without a seat')]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/bags-root[1]/bags-booking-container[1]/div[1]/main[1]/div[1]/section[1]/div[1]/bags-cabin-lazy-bag[1]/bags-cabin-bag-section[1]/bags-bag-layout[1]/div[1]/div[3]/div[2]/bags-pax-table-journey-container[1]/div[1]/div[2]/bags-cabin-bag-table-controls-container[1]/bags-cabin-bag-table-controls[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/bags-root[1]/bags-booking-container[1]/div[1]/main[1]/div[1]/section[1]/div[1]/bags-cabin-lazy-bag[1]/bags-cabin-bag-section[1]/bags-bag-layout[1]/div[1]/div[3]/div[2]/bags-pax-table-journey-container[1]/div[1]/div[2]/bags-cabin-bag-table-controls-container[1]/bags-cabin-bag-table-controls[1]/div[1]/bags-small-bag-pax-control[1]/div[1]/bags-product-selector[1]/div[1]/div[1]/div[1]/ry-radio-circle-button[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'No thanks')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
    #
    # def test_ryanair_112dba49(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Events & Activities')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/ul[3]/li[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/section[1]/div[2]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[2]/aside[1]/div[1]/section[1]/div[1]/div[6]/div[1]/div[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[4]/div[4]/div[1]/div[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Get tickets')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[2]/button[2]/img[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[8]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[9]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/img[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[9]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/main[1]/div[1]/div[9]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[2]/button[1]").click()
    #
    # def test_ryanair_1202e28a(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Car Hire')]").click()
    #     self.driver.find_element(By.ID, "input-button__pick-up-location").clear()
    #     self.driver.find_element(By.ID, "input-button__pick-up-location").send_keys("Athens")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-pickup-location-container[1]/hp-car-hire-location[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/month-toggle[1]/div[1]/div[2]/div[1]/div[2]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[2]/div[16]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-10']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[3]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-lazy-car-hire-widget[1]/hp-app-car-hire-widget[1]/hp-car-hire-widget-container[1]/hp-car-hire-widget[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='in-path-container']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[4]/div[1]/div[2]/div[1]/label[1]/span[2]").click()
    #
    # def test_ryanair_87ca0d6a(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.ID, "input-button__departure").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-1']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-origin-container[1]/fsw-airports[1]/fsw-countries[1]/div[3]/div[6]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-1']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-origin-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/fsw-countries[1]/div[3]/div[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-3']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-destination-container[1]/fsw-airports[1]/div[1]/fsw-airports-list[1]/div[2]/div[1]/fsw-airport-item[11]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-6']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[6]/div[7]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-flexible-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[2]/calendar-body[1]/div[2]/div[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-app-controls-tooltips[1]/fsw-controls-tooltips-container[1]/fsw-controls-tooltips[1]/fsw-passengers-container[1]/fsw-passengers[1]/fsw-passengers-picker-container[1]/fsw-passengers-picker[1]/ry-counter[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//label[contains(.,'Apply promo code')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='promocode' and @type='text' and @placeholder='Apply promo code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='promocode' and @type='text' and @placeholder='Apply promo code']").send_keys("1000001")
    #     self.driver.find_element(By.XPATH, "/html/body[1]/hp-app-root[1]/hp-home-container[1]/hp-home[1]/hp-search-widget-container[1]/hp-search-widget[1]/div[1]/hp-flight-search-widget-container[1]/fsw-flight-search-widget-container[1]/fsw-flight-search-widget[1]/div[1]/div[1]/div[1]/button[1]").click()
    #
    # def test_ryanair_b5c98548(self):
    #     # self.driver.get("http://ryanair.com/")
    #     self.driver.find_element(By.XPATH, "//div[contains(.,'Car Hire')]").click()
    #     self.driver.find_element(By.ID, "input-button__pick-up-location").clear()
    #     self.driver.find_element(By.ID, "input-button__pick-up-location").send_keys("Paris Charles de Gaulle Airport (CDG)")
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-7']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-pickup-location-container[1]/hp-car-hire-location[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-8']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[4]/div[10]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-10']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-car-hire-datepicker-container[1]/fsw-datepicker[1]/ry-datepicker-desktop[1]/div[1]/calendar[1]/calendar-body[1]/div[5]/div[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-9']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-time-selector-container[1]/hp-time-selector-list[1]/hp-time-selector-item[21]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-tooltip[@id='ry-tooltip-11']/div[2]/hp-lazy-car-hire-controls-tooltips[1]/hp-app-car-hire-controls-tooltips[1]/hp-car-hire-controls-tooltips-container[1]/hp-car-hire-controls-tooltips[1]/hp-time-selector-container[1]/hp-time-selector-list[1]/hp-time-selector-item[21]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//ry-spinner[contains(.,\"Let's go\")]").click()
    