import time

import pytest
from selenium.webdriver.common.by import By

from browser_helper import calculate_budget_dates


@pytest.mark.usefixtures("setup_class")
class TestBudget:
    
    # def test_budget_91695df8(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reservations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Budget Truck')]").click()
    #     self.driver.find_element(By.ID, "txtPickupLocation").clear()
    #     self.driver.find_element(By.ID, "txtPickupLocation").send_keys("08817")
    #     self.driver.find_element(By.ID, "pickUpDate").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'12')]").click()
    #     self.driver.find_element(By.ID, "ddlPickupTimes").clear()
    #     self.driver.find_element(By.ID, "ddlPickupTimes").select("02 30 PM")
    #     self.driver.find_element(By.ID, "radio-value-LO").click()
    #     self.driver.find_element(By.ID, "btnFindTruck").click()
    #     self.driver.find_element(By.ID, "btnIsSoldOut1").click()
    #     self.driver.find_element(By.ID, "selectMiles").clear()
    #     self.driver.find_element(By.ID, "selectMiles").send_keys("100")
    #     self.driver.find_element(By.ID, "btnContinuetoLocation").click()
    #     self.driver.find_element(By.ID, "btnAvailableTuckId0").click()
    #     self.driver.find_element(By.ID, "cntrl0").clear()
    #     self.driver.find_element(By.ID, "cntrl0").send_keys("2")
    #     self.driver.find_element(By.ID, "lnkNoThanks").click()
    #
    # def test_budget_63693bf5(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Select This Location')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[3]/div[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[1]/div[2]/h3[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[3]/div[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #
    # def test_budget_dd8a2207(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("SFO")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'27')]").click()
    #     self.driver.find_element(By.ID, "res-home-vehicle-type").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='selectCar']/div[1]/div[2]/div[6]/div[1]/div[7]/div[1]/div[1]/div[4]/div[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #
    # def test_budget_380d2539(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("SFO")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'27')]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #
    # def test_budget_3c76cc80(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reservations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Get e-Receipt')]").click()
    #     self.driver.find_element(By.ID, "lastName").clear()
    #     self.driver.find_element(By.ID, "lastName").send_keys("Smith")
    #     self.driver.find_element(By.ID, "Confirmation-no").clear()
    #     self.driver.find_element(By.ID, "Confirmation-no").send_keys("X123456989")
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[3]/div[1]/div[5]/button[1]").click()
    #
    # def test_budget_44678c96(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Cars & Services')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Popular Rental Cars')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[2]/section[1]/div[1]/div[1]/section[1]/div[1]/div[1]/div[3]/div[1]/a[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'10')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Continue')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Select This Location')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #
    # def test_budget_a3f650df(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Locations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Top Airport Locations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Birmingham-Shuttlesworth Intl')]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'10')]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[3]/div[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[1]/div[2]/h3[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #
    # def test_budget_ba40d2fb(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Van Rental')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("Portugal Cove")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Select This Location')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[4]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[4]/ul[1]/li[2]/a[1]").click()
    #
    # def test_budget_4ce1633f(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Partner Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='middle']/div[2]/div[1]/a[3]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("roanoke")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "to").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'10')]").click()
    #     self.driver.find_element(By.ID, "partnerCheckboxId").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.ID, "res-vehicles-filter-by-vehicle-type").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='myDiv']/div[1]/div[1]/ul[1]/li[4]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[3]/div[1]/div[2]/div[1]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #
    # def test_budget_4d0de000(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Free Upgrade Deal')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("ontario")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[@title='Next']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'2')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'6')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("11 00 AM")
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("4 30 PM")
    #     self.driver.find_element(By.ID, "res-home-vehicle-type").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='selectCar']/div[1]/div[2]/div[6]/div[1]/div[7]/div[1]/div[1]/div[4]/div[1]/div[1]/img[1]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.personalInfoRQ.residency']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.personalInfoRQ.residency']").select("Australia")
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.ID, "res-vehicles-sort").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Later')]").click()
    #     self.driver.find_element(By.ID, "res-extras-continue-top").click()
    #
    # def test_budget_6a9a2e52(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
    #     self.driver.find_element(By.ID, "nav-d-1231").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Country')]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@role='searchbox' and @type='search' and @placeholder='Select a Country']").click()
    #     self.driver.find_element(By.ID, "select2-l-country-result-4zlx-United States of America").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Team')]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@role='searchbox' and @type='search' and @placeholder='Select a Team']").click()
    #     self.driver.find_element(By.ID, "select2-l-team-result-69am-Finance").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Time Type')]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@role='searchbox' and @type='search' and @placeholder='Select a Time Type']").click()
    #     self.driver.find_element(By.ID, "select2-l-type-result-fcy1-Full time").click()
    #     self.driver.find_element(By.ID, "js-main-job-search").click()
    #     self.driver.find_element(By.ID, "js-job-djot8au4kn").click()
    #     self.driver.find_element(By.ID, "js-apply-external").click()
    #
    # def test_budget_7f0d7056(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Luxury Car Rental')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("New York, United States, 100")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Select This Location')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]").click()
    #
    # def test_budget_87b23bf1(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Long-Term Car Rental')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("orlando")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'29')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'28')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("9 00 AM")
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("9 00 AM")
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.ID, "res-vehicles-sort").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #     self.driver.find_element(By.ID, "GPSchk").click()
    #     self.driver.find_element(By.ID, "XMRchk").click()
    #     self.driver.find_element(By.ID, "GSOchk").click()
    #     self.driver.find_element(By.ID, "res-extras-continue-top").click()
    #
    # def test_budget_593830ff(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Cars & Services')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Products & Services')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/div[1]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/div[1]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'click here')]").click()
    #
    # def test_budget_66625c9d(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Partner Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='middle']/div[2]/div[1]/a[5]/div[2]/button[1]").click()
    #
    # def test_budget_694f3b5c(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("Manhattan")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[10]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("3 00 PM")
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("6 00 PM")
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Select This Location')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #
    # def test_budget_d1de3d1a(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Military & Veterans')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("nevada city")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='ui-datepicker-div']/div[5]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='ui-datepicker-div']/div[5]/div[1]/select[1]").select("June 2023")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'6')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("11 00 AM")
    #     self.driver.find_element(By.ID, "to").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='ui-datepicker-div']/div[5]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='ui-datepicker-div']/div[5]/div[1]/select[1]").select("June 2023")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'10')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("1 00 PM")
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #     self.driver.find_element(By.ID, "GPSchk").click()
    #     self.driver.find_element(By.ID, "TOLchk").click()
    #     self.driver.find_element(By.ID, "res-extras-continue-bottom").click()
    #
    # def test_budget_e592a68f(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reservations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Budget Truck')]").click()
    #     self.driver.find_element(By.ID, "txtPickupLocation").clear()
    #     self.driver.find_element(By.ID, "txtPickupLocation").send_keys("10001")
    #     self.driver.find_element(By.ID, "pickUpDate").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'23')]").click()
    #     self.driver.find_element(By.ID, "radio-value-LO").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='flexibleDateChk']/span[1]").click()
    #     self.driver.find_element(By.ID, "btnFindTruck").click()
    #     self.driver.find_element(By.ID, "btnIsSoldOut1").click()
    #
    # def test_budget_03103341(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("Roanoke")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.ID, "res-vehicles-sort").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reservation-partial']/div[1]/div[1]/div[2]/section[1]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #     self.driver.find_element(By.ID, "res-extras-continue-top").click()
    #
    # def test_budget_03ac581c(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Cars & Services')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Protections & Coverages')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[4]/a[1]/div[1]/div[1]/div[2]/h4[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/p[5]/a[1]/b[1]").click()
    #
    # def test_budget_1655f54a(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Trip Ideas')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='middle']/div[2]/div[1]/a[2]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("LOS ANGELES")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='ui-datepicker-div']/div[5]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='ui-datepicker-div']/div[5]/div[1]/select[1]").select("July 2023")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'7')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'15')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("1 00 PM")
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("2 00 PM")
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.personalInfoRQ.residency']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.personalInfoRQ.residency']").select("Vietnam")
    #     self.driver.find_element(By.ID, "res-home-vehicle-type").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='selectCar']/div[1]/div[2]/div[6]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #
    # def test_budget_0245df99(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Cars & Services')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Car Guides')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Vehicle Info')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reserve')]").click()
    #
    # def test_budget_27a8bf82(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Cars & Services')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Car Sales')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@role='combobox' and @type='button' and @title='All Makes']").click()
    #     self.driver.find_element(By.ID, "inventory-search1").clear()
    #     self.driver.find_element(By.ID, "inventory-search1").send_keys("26807")
    #     self.driver.find_element(By.XPATH, "//button[@role='combobox' and @type='button' and @title='25 miles']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='facet-browse-inventory-search1']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[6]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='make--heading']/div[1]/a[1]/span[1]/i[1]").click()
    #     self.driver.find_element(By.ID, "make-Buick").click()
    #     self.driver.find_element(By.XPATH, "//img[@role='presentation' and @title='2022 Buick Enclave Premium SUV']").click()
    #
    # def test_budget_31c12c59(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reservations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'View / Modify / Cancel')]").click()
    #     self.driver.find_element(By.ID, "countrylookup").clear()
    #     self.driver.find_element(By.ID, "countrylookup").select("UNITED STATES")
    #     self.driver.find_element(By.ID, "res-view-lastName").clear()
    #     self.driver.find_element(By.ID, "res-view-lastName").send_keys("smith")
    #     self.driver.find_element(By.ID, "res-view-confirmationNumber").clear()
    #     self.driver.find_element(By.ID, "res-view-confirmationNumber").send_keys("123456")
    #     self.driver.find_element(By.XPATH, "//form[@id='res-viewModifyForm']/div[3]/div[1]/div[5]/button[1]").click()
    #
    # def test_budget_942e315d(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Fastbreak')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Fastbreak Program')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/section[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/hgroup[1]/h2[1]/span[1]/p[3]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "saveEnrollmentForm").click()
    #
    # def test_budget_44a12ff5(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Locations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a Location')]").click()
    #     self.driver.find_element(By.ID, "PicLoc_value").clear()
    #     self.driver.find_element(By.ID, "PicLoc_value").send_keys("laguardia airport")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='avisHome']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/div[2]/div[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//li[@id='SearchpushPin_1']/div[1]/a[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("midnight")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("noon")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguDropLoc' and @type='text' and @placeholder='Return to same location']").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #
    # def test_budget_4c997e24(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("10023")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[3]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'12')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("3 00 AM")
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Select This Location')]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #
    # def test_budget_bcc2b6df(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//form[@id='selectCar']/div[1]/div[1]/div[2]/div[1]/div[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "txtPickupLocation").clear()
    #     self.driver.find_element(By.ID, "txtPickupLocation").send_keys("07718")
    #     self.driver.find_element(By.ID, "pickUpDate").click()
    #     self.driver.find_element(By.ID, "datepicker-popup-nextDiv-pickUpDate").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.ID, "ddlPickupTimes").clear()
    #     self.driver.find_element(By.ID, "ddlPickupTimes").select("04 00 PM")
    #     self.driver.find_element(By.ID, "radio-value-LO").click()
    #     self.driver.find_element(By.ID, "btnFindTruck").click()
    #     self.driver.find_element(By.ID, "btnIsSoldOut1").click()
    #     self.driver.find_element(By.ID, "selectMiles").clear()
    #     self.driver.find_element(By.ID, "selectMiles").send_keys("250")
    #     self.driver.find_element(By.ID, "btnContinuetoLocation").click()
    #     self.driver.find_element(By.ID, "pickuptime0").clear()
    #     self.driver.find_element(By.ID, "pickuptime0").select("04 00 PM")
    #     self.driver.find_element(By.ID, "droppickuptime0").clear()
    #     self.driver.find_element(By.ID, "droppickuptime0").select("04 30 PM")
    #     self.driver.find_element(By.ID, "btnAvailableTuckId0").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='10069']/div[1]/div[2]/button[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "lnkNoThanks").click()
    
    def test_budget_c759aa6c(self):
        # self.driver.get("https://www.budget.com/en/home")
        # uiteststudy@gmail.com:UITestStudy2024!
        # self.driver.find_element(By.ID, "res-login-profile").click()
        # self.driver.find_element(By.ID, "username").click()
        # self.driver.find_element(By.ID, "username").send_keys("uiteststudy@gmail.com")
        # self.driver.find_element(By.ID, "password").click()
        # self.driver.find_element(By.ID, "password").send_keys("UITestStudy2024!")
        # self.driver.find_element(By.ID, "res-login-profile").click()
        self.driver.find_element(By.ID, "PicLoc_value").clear()
        self.driver.find_element(By.ID, "PicLoc_value").send_keys("Chicago O'hare Intl Airport, ORD")
        self.driver.find_element(By.XPATH, "//span[contains(text(),\"Chicago O'Hare Intl Airport\")]").click()
        (start_date_year, start_date_month_adjusted, start_date_day), (end_date_year, end_date_month_adjusted, end_date_day) = calculate_budget_dates(7, 14)
        # time.sleep(2)
        self.driver.find_element(By.ID, "from").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, f"//td[@data-year='{start_date_year}' and @data-month='{start_date_month_adjusted}']//a[text()='{start_date_day}']").click()
        time.sleep(2)
        self.driver.find_element(By.ID, "to").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, f"//td[@data-year='{end_date_year}' and @data-month='{end_date_month_adjusted}']//a[text()='{end_date_day}']").click()
        # time.sleep(2)
        self.driver.find_element(By.ID, "res-home-vehicle-type").click()
        self.driver.find_element(By.XPATH, "//form[@id='selectCar']//img[@alt='SUVs & Wagons']").click()
        self.driver.find_element(By.ID, "res-home-select-car").click()
        self.driver.find_element(By.ID, "res-vehicles-sort").click()
        self.driver.find_element(By.XPATH, "//a[contains(.,'Price (Low to High)')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(.,'Add Offer Code')]").click()
        self.driver.find_element(By.XPATH, "//a[@ng-click='vm.applyCoupon()' and text()='Update']").click()
        # time.sleep(1)
        # self.driver.find_element(By.XPATH, "/html/body/div[6]/div[2]/div[1]/div/div/div[2]/div[1]/section[3]/div[1]/div[2]/div/section/div[1]/div/div[2]/div[2]/div[2]/a").click()
    
    # def test_budget_cf361c84(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Locations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a Location')]").click()
    #     self.driver.find_element(By.ID, "PicLoc_value").clear()
    #     self.driver.find_element(By.ID, "PicLoc_value").send_keys("washington")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Make a Reservation')]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[@title='Next']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'1')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'2')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("11 00 AM")
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("11 00 AM")
    #     self.driver.find_element(By.XPATH, "//input[@name='anguDropLoc' and @type='text' and @placeholder='Return to same location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguDropLoc' and @type='text' and @placeholder='Return to same location']").send_keys("washington")
    #     self.driver.find_element(By.XPATH, "//div[@id='DropLoc_dropdown']/div[3]/div[1]/div[3]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "res-home-vehicle-type").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='selectCar']/div[1]/div[2]/div[6]/div[1]/div[7]/div[1]/div[1]/div[4]/div[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #     self.driver.find_element(By.ID, "TABchk").click()
    #     self.driver.find_element(By.ID, "ADRchk").click()
    #     self.driver.find_element(By.ID, "res-extras-continue-top").click()
    #
    # def test_budget_a919aa15(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reservations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Make a Reservation')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='anguPicLoc' and @type='text' and @placeholder='Enter your pick-up location or zip code']").send_keys("AUCKLAND")
    #     self.driver.find_element(By.XPATH, "//div[@id='PicLoc_dropdown']/div[3]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "from").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'7')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.pickUpTime']").select("10 00 AM")
    #     self.driver.find_element(By.ID, "to").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'10')]").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='reservationModel.dropTime']").select("5 00 PM")
    #     self.driver.find_element(By.ID, "res-home-vehicle-type").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='selectCar']/div[1]/div[2]/div[6]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "res-home-select-car").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Pay Now')]").click()
    #     self.driver.find_element(By.ID, "res-extras-continue-top").click()
    #
    # def test_budget_b02e47ac(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[@id='bx-close-inside-1819757']/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reservations')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'View / Modify / Cancel')]").click()
    #     self.driver.find_element(By.ID, "countrylookup").clear()
    #     self.driver.find_element(By.ID, "countrylookup").select("AUSTRALIA")
    #     self.driver.find_element(By.ID, "res-view-lastName").clear()
    #     self.driver.find_element(By.ID, "res-view-lastName").send_keys("Walker")
    #     self.driver.find_element(By.ID, "res-view-confirmationNumber").clear()
    #     self.driver.find_element(By.ID, "res-view-confirmationNumber").send_keys("A987654")
    #     self.driver.find_element(By.XPATH, "//form[@id='res-viewModifyForm']/div[3]/div[1]/div[5]/button[1]").click()
    #
    # def test_budget_b5d47068(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'US Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='middle']/div[2]/div[1]/a[1]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'US Deals')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='middle']/div[2]/div[1]/a[2]/div[2]/button[1]").click()
    #
    # def test_budget_b8cfdd2c(self):
    #     # self.driver.get("https://www.budget.com/en/home")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
    #     self.driver.find_element(By.ID, "nav-d-1231").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Country')]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@role='searchbox' and @type='search' and @placeholder='Select a Country']").click()
    #     self.driver.find_element(By.ID, "select2-l-country-result-cprj-United States of America").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Team')]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@role='searchbox' and @type='search' and @placeholder='Select a Team']").click()
    #     self.driver.find_element(By.ID, "select2-l-team-result-4rku-Finance").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Time Type')]").click()
    #     self.driver.find_element(By.XPATH, "//textarea[@role='searchbox' and @type='search' and @placeholder='Select a Time Type']").click()
    #     self.driver.find_element(By.ID, "select2-l-type-result-txss-Full time").click()
    #     self.driver.find_element(By.ID, "js-main-job-search").click()
    