import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestNewegg:
    
    def test_newegg_e483a49f(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//a[@id='trendingBanner_671801']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[5]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/ul[1]/li[5]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[2]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[3]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[7]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[4]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[5]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[6]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[7]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[4]/td[7]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[8]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[6]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[9]/div[1]/a[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[5]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[10]/div[1]/a[1]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[10]/div[1]/a[1]/div[1]/i[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[17]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[7]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[10]/div[1]/a[1]/div[1]/i[4]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[3]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[10]/div[1]/a[1]/div[1]/i[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[4]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[7]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    
    def test_newegg_14d50319(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys('32" curved monitor')
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='24-012-049']/div[1]/a[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Add To List')]").click()
    
    def test_newegg_b674adf9(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Newegg Careers')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'SEE ALL JOB LISTINGS')]").click()
        self.driver.find_element(By.ID, "country_VVNB").click()
        self.driver.find_element(By.ID, "state_Q0E=").click()
        self.driver.find_element(By.XPATH, "//div[@id='accordiongroup-1755-555-panel']/div[1]/div[1]/fieldset[1]/table[1]/tbody[1]/tr[10]/td[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='on' and @type='checkbox']").click()
        self.driver.find_element(By.ID, "zzreqemployeeclass_SW50ZXJucw==").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Newegg Early Career Internship Program')]").click()
        self.driver.find_element(By.XPATH, "//i[@role='button' and @title='Bookmark This']").click()
    
    def test_newegg_03fd47fc(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//a[@id='trendingBanner_671801']/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='pc for playing games i7, rtx 3060, price $1300-1600']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='pc for playing games i7, rtx 3060, price $1300-1600']").send_keys("gaming pc ryzen 9 ,rtx 6950xt price $2000-2500")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/button[1]/i[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='item-list-swiper']/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]").click()
    
    def test_newegg_87ed4a0a(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("drone")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/div[1]/em[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[4]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[4]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/ul[1]/li[2]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[10]/dt[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[10]/dd[1]/ul[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[10]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[2]/a[3]").click()
    
    def test_newegg_f1986a5b(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("bluetooth vertical mouse")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").select("Most Reviews")
        self.driver.find_element(By.XPATH, "//img[@title='Perixx PERIMICE-804  Bluetooth Ergonomic Vertical Optical Mouse 800/1200/1600 DPI 6 Buttons Design']").click()
        self.driver.find_element(By.XPATH, "//button[@type='button']").click()
        self.driver.find_element(By.XPATH, "//button[@title='Add Perixx PERIMICE-804  Bluetooth Ergonomic Vertical Optical Mouse 800/1200/1600 DPI 6 Buttons Design to cart']").click()
    
    def test_newegg_75294fc6(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("ssd")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//button[@title='Add KingSpec Internal Solid State Drive 128GB SSD 2.5 Inch SATA III NAND Flash Data Storage Computer Disk File Transfer PC Desktop laptop Notebook Transfer for White-Collar Game-Player to cart']").click()
    
    def test_newegg_549a9805(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("wireless printer")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[11]/dt[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[11]/dd[1]/ul[1]/div[1]/div[1]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[11]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='28-120-036']/div[2]/div[2]/div[2]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='28-120-039']/div[2]/div[2]/div[2]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[4]/div[2]/div[1]/div[1]/div[3]/button[1]/span[1]").click()
    
    def test_newegg_747429fa(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("wireless keyboard")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[2]/dd[1]/ul[1]/li[6]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[2]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").send_keys("70")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//div[@id='9SIAET87AA7743']/div[1]/a[1]").click()
    
    def test_newegg_05c4da5b(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("xbox wireless controller")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[11]/dt[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[11]/dd[1]/ul[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[11]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//img[@title='Wired Gaming Controller, Joystick Gamepad with Dual-Vibration PC Game Controller Compatible with PS3, Switch, Windows 10/8/7 PC, Laptop, TV Box, Android Mobile Phones, 6.5 ft USB Cable']").click()
    
    def test_newegg_51d2bb04(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[2]/div[6]/a[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/button[1]").click()
    
    def test_newegg_8368b990(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[5]/div[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-builder-check']/div[1]/div[1]/div[2]/button[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[4]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[3]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[7]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[5]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[6]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[7]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[7]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[8]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[6]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[9]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[5]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[10]/div[2]/div[1]/a[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/a[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[4]/td[8]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-pc-content']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    
    def test_newegg_227054d0(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[6]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Tablets')]").click()
        self.driver.find_element(By.XPATH, "//img[@title='Samsung']").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[1]/dd[1]/ul[1]/li[4]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[1]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[1]/dd[1]/ul[1]/li[4]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[1]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[8]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[8]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//button[@title='Add Samsung Galaxy Tab S7 FE 5G SM-T738U Tablet - 12.4\" WQXGA - Qualcomm Kryo 570 Octa-core (8 Core) 2.20 GHz - 64 GB Storage - Android 11 - 5G - Mystic Black - Qualcomm SM7225 SoC - 2560 x 1600 - Ve to cart']").click()
    
    def test_newegg_effb9df8(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("projectors")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[6]/li[1]/div[2]/label[1]").click()
    
    def test_newegg_e84111f2(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gaming Desktops')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[2]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[2]/label[1]").click()
    
    def test_newegg_92cfe78f(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'TV & Home Theater')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'LED TV')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[9]/dt[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[9]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[9]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").send_keys("1000")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[9]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//img[@title='Samsung 65\" Class Q80B Series QLED 4K Smart TV (QN65Q80BAFXZA, 2022)']").click()
    
    def test_newegg_74e653f0(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[4]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[2]/div[1]/div[15]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[2]/div[1]/div[9]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/div[2]/p[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/button[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[2]/div[2]/button[2]").click()
    
    def test_newegg_10593972(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("lenovo laptop")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='9SIAWVGJSM4399']/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='0.00']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='0.00']").send_keys("400")
        self.driver.find_element(By.XPATH, "//div[@id='Popup_Price_Alert']/div[1]/div[1]/div[3]/button[2]").click()
    
    def test_newegg_1282a011(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("laptop")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").send_keys("700")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/dl[4]/dt[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/dl[4]/dd[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/dl[4]/dd[1]/ul[2]/li[4]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/dl[4]/dd[1]/div[1]/button[1]").click()
    
    def test_newegg_8eae88ef(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[7]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'PS5 Accessories')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[2]/dd[1]/ul[1]/li[4]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[2]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").select("Highest Price")
        self.driver.find_element(By.XPATH, "//button[@title='Add Brand New Sealed Dualsense Controller PS5 Wireless Controller - Compatible with PlayStation 5 to cart']").click()
    
    def test_newegg_13d78369(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("headphones")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/dl[3]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/div[2]/dl[3]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/div[1]/button[1]").click()
    
    def test_newegg_f4623be1(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[2]/div[6]/a[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//input[@value='1' and @type='text']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='1' and @type='text']").send_keys("10")
        self.driver.find_element(By.XPATH, "//input[@value='10' and @type='text']").click()
    
    def test_newegg_b467797c(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Printer Ink & Toner')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Xerox Toner')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[1]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[1]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/ul[1]/li[4]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[3]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[4]/dd[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[4]/dd[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[4]/label[1]/select[1]").select("Lowest Price")
    
    def test_newegg_987b25a8(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("Western Digital internal SSD 1 TB")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='20-250-217']/div[1]/a[1]").click()
        self.driver.find_element(By.XPATH, "//button[@title='Add Western Digital WD_BLACK SN770 M.2 2280 1TB PCIe Gen4 16GT/s, up to 4 Lanes Internal Solid State Drive (SSD) WDS100T3X0E to cart']").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-intermediary']/div[1]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-intermediary']/div[1]/div[1]/div[1]/button[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("8GB Ram")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//img[@title='8GB (1x8GB) DDR3L 1600 (PC3L-12800) Desktop Memory Module by Avarum Ram']").click()
        self.driver.find_element(By.XPATH, "//button[@title='Add 8GB (1x8GB) DDR3L 1600 (PC3L-12800) Desktop Memory Module by Avarum Ram to cart']").click()
        self.driver.find_element(By.XPATH, "//div[@id='modal-intermediary']/div[1]/div[1]/div[1]/div[3]/button[1]").click()
    
    def test_newegg_17fffbee(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("600w power supply")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/ul[1]/li[8]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/label[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[4]/label[1]/select[1]").select("Lowest Price")
        self.driver.find_element(By.XPATH, "//img[@title='Hercules DUAL FAN 600w-Max ATX Power Supply SATA, 20+4-pin, 6-Pin']").click()
    
    def test_newegg_2fc63250(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("wireless keyboard mouse")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").send_keys("100")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='9SIAFJ86WT7315']/div[1]/a[1]").click()
    
    def test_newegg_2a7f7732(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[4]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/button[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[2]/section[2]/div[1]/div[1]/div[2]/div[2]/button[2]").click()
    
    def test_newegg_e344b89e(self):
        # self.driver.get("https://newegg.com")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @title='Search Site']").send_keys("motherboard")
        self.driver.find_element(By.XPATH, "//div[@id='app']/header[1]/div[1]/div[1]/div[1]/div[5]/form[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[1]/label[1]/span[1]/span[3]/input[1]").send_keys("200")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[3]/section[1]/div[1]/div[1]/div[1]/div[1]/dl[5]/dd[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='13-145-164']/div[1]/a[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Processors - Desktops')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='item_cell_19-113-736_1_0']/div[2]/div[2]").click()
        self.driver.find_element(By.XPATH, "//button[@title='']").click()
    