import pytest
from selenium.webdriver.common.by import By

from browser_helper import calculate_dates_full_month_name


@pytest.mark.usefixtures("setup_class")
class TestTripadvisor:
    
    # def test_tripadvisor_be3b849b(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[4]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Johannesburg")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_50']/div[1]/div[8]/div[2]/div[2]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/svg[1]").click()
    #
    # def test_tripadvisor_c474e2a6(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").send_keys("Sedona, AZ")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[2]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='PERSISTENT_TRIP_SEARCH_BAR']/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/span[1]/span[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[4]/div[4]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[5]/div[4]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[3]/div[1]/button[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[4]/div[1]/div[1]/button[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[6]/div[1]/div[1]/div[1]/div[2]/button[10]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[5]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[2]/div[2]/span[1]/div[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[4]/div[2]/span[1]/div[1]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[4]/div[2]/span[1]/div[1]/div[2]/div[1]/div[1]").click()
    #
    # def test_tripadvisor_250ec75c(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[4]/a[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Central Park New York")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[2]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'More restaurants in Central Park')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_39']/div[1]/div[6]/div[2]/div[5]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[11]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[11]/div[1]/div[1]/div[3]/button[1]").click()
    #
    # def test_tripadvisor_f20aabaf(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[1]/div[1]/div[3]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Quepos, Costa Rica")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[5]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/button[1]/span[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_2-Rlacccl:']/div[1]/div[1]/span[3]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[1]/span[2]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='menu-item-PRICELOW']/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Guapinol Villanueva House')]").click()

    def test_tripadvisor_ffc01d9d(self):
        # self.driver.get("https://www.tripadvisor.com/")
        # TODO: Still being blocked by trip advisor, so can't evaluate whether the test can pass. Consider remove trip advisor from out subjects?
        # self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[16]/div[1]/button[1]/span[3]/svg[1]/circle[3]").click()
        # self.driver.find_element(By.XPATH, "//a[@id='menu-item-3']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[@data-automation='centralNav_flights']").click()

        # page logic changed, click one-way button is moved to below
        # self.driver.find_element(By.XPATH, "//div[@id='component_6']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]").click()

        # self.driver.find_element(By.XPATH, "//input[@name='From' and @value='Columbus (CMH)' and @type='text' and @placeholder='City or Airport']").clear()
        # self.driver.find_element(By.XPATH, "//input[@name='From' and @value='Columbus (CMH)' and @type='text' and @placeholder='City or Airport']").send_keys("SAN FRANSISCO")
        # self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[1]/div[1]/span[2]").click()
        # self.driver.find_element(By.XPATH, "//input[@name='To' and @value='Los Angeles (LAX)' and @type='text' and @placeholder='City or Airport']").clear()
        # self.driver.find_element(By.XPATH, "//input[@name='To' and @value='Los Angeles (LAX)' and @type='text' and @placeholder='City or Airport']").send_keys("SAN DIEGO")
        # self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[1]/div[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//input[@name='q' and @type='search' and @placeholder='Origin']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='q' and @type='search' and @placeholder='Origin']").send_keys("SAN FRANSISCO")
        self.driver.find_element(By.XPATH, "//div[text()='SFO International Airport (SFO)']").click()
        self.driver.find_element(By.XPATH, "//input[@name='q' and @type='search' and @placeholder='Destination']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='q' and @type='search' and @placeholder='Destination']").send_keys("SAN DIEGO")
        self.driver.find_element(By.XPATH, "//div[text()='San Diego International Airport (SAN)']").click()

        # time select logic changed, have to select depart time and return time at first then change to one way
        # self.driver.find_element(By.XPATH, "//div[@id='component_6']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]").click()
        # self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[7]").click()
        self.driver.find_element(By.XPATH, "//button[@type='button' and contains(@aria-label, 'Enter the date range.')]").click()
        start_date_str, end_date_str = calculate_dates_full_month_name(14, 21)
        self.driver.find_element(By.XPATH, f"//div[@aria-label='{start_date_str}']").click()
        self.driver.find_element(By.XPATH, f"//div[@aria-label='{end_date_str}']").click()
        self.driver.find_element(By.XPATH, "//span[text()='Apply']").click()

        # self.driver.find_element(By.ID, "OVERLAY").click()
        # self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/span[2]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/span[2]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='component_6']/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/span[1]/div[1]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='button' and contains(@aria-label, 'Enter the number of guests.')]").click()
        self.driver.find_element(By.XPATH, "//button[@type='button' and @title='Increase']").click()
        self.driver.find_element(By.XPATH, "//div[./div[1]/div[text()='Adults']]/div[2]/button[@title='Increase']").click()
        self.driver.find_element(By.XPATH, "//div[./div[1]/div[text()='Seniors']]/div[2]/button[@title='Increase']").click()
        self.driver.find_element(By.XPATH, "//span[text()='Apply']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='component_6']/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/button[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='leftRailFilter']/div[1]/div[1]/div[1]/div[1]/div[9]/div[5]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='leftRailFilter']/div[1]/div[1]/div[1]/div[1]/div[9]/div[8]/div[1]/label[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='leftRailFilter']/div[1]/div[1]/div[1]/div[1]/div[5]/div[2]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='MAIN']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='fareOptionsContainerId']/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[7]/td[2]/div[2]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//span[text()='Search']").click()
        # click on one-way here
        self.driver.find_element(By.XPATH, "//a[text()='One-way']").click()
        self.driver.find_element(By.XPATH, "//span[text()='Prefer nonstop']").click()
        self.driver.find_element(By.XPATH, "//button[@class='ui_button primary fullwidth']/div[text()='Search']").click()
        self.driver.find_element(By.XPATH, "//div[text()='Select all airlines']/following-sibling::div[1]//span[text()='Show more']").click()
        self.driver.find_element(By.XPATH, "//span[text()='United']").click()
        self.driver.find_element(By.XPATH, "//div[text()='Best Value']").click()
        self.driver.find_element(By.XPATH, "//div[text()='Earliest outbound departure']").click()
        self.driver.find_element(By.XPATH, "//div[./div[1]/span[contains(text(), 'Price per person is the average of all passengers')]]/div[2]/div[2]//div[text()='View Deal']").click()

    # def test_tripadvisor_4a023ef6(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/header[1]/div[1]/nav[1]/div[1]/div[2]/div[1]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='What would you like to review?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='What would you like to review?']").send_keys("Hotel Xcaret Mexico")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/button[1]/div[2]/div[1]").click()
    #
    # def test_tripadvisor_5cf2503b(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[16]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='menu-item-3']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='From' and @value='Columbus (CMH)' and @type='text' and @placeholder='City or Airport']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='From' and @value='Columbus (CMH)' and @type='text' and @placeholder='City or Airport']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='From' and @value='Columbus (CMH)' and @type='text' and @placeholder='City or Airport']").send_keys("Toronto, Canada")
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[1]/div[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='To' and @value='Toronto (YTO)' and @type='text' and @placeholder='City or Airport']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='To' and @value='Toronto (YTO)' and @type='text' and @placeholder='City or Airport']").send_keys("New York City")
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[1]/div[1]/span[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_6']/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='MAIN']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='MAIN']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='MAIN']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]/div[1]").click()
    #
    # def test_tripadvisor_634c62b6(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[4]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Paris")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'See all')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[5]/div[1]/a[1]/span[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_22']/div[1]/div[1]/div[1]/div[1]/div[3]/a[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Book')]").click()
    #
    # def test_tripadvisor_eb5a2532(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").send_keys("Pizzeria Mozza")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_55']/div[1]/div[1]/div[2]/div[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[2]/div[1]/div[2]/div[1]/form[1]/div[1]/span[1]/span[1]/label[5]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[2]/div[1]/div[2]/div[1]/form[1]/div[2]/div[2]/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='menu-item-2023-03-01']/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[2]/div[1]/div[2]/div[1]/form[1]/div[3]/label[1]/span[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[2]/div[1]/div[2]/div[1]/form[1]/div[4]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='menu-item-LUNCH']/div[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "review-text").clear()
    #     self.driver.find_element(By.ID, "review-text").send_keys("Perfect Pizza like never before")
    #     self.driver.find_element(By.ID, "review-title").clear()
    #     self.driver.find_element(By.ID, "review-title").send_keys("Best Taste")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[2]/div[1]/div[2]/div[1]/form[1]/button[1]").click()
    #
    # def test_tripadvisor_da77f831(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[1]/div[1]/div[4]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Big Sur, CA")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_40']/div[1]/div[3]/div[2]/div[4]/div[1]/label[1]").click()
    #
    # def test_tripadvisor_7efa64af(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").send_keys("Eiffel Tower")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Check Availability')]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Wed, 3/29')]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Reserve Now')]").click()
    #
    # def test_tripadvisor_818a7660(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[16]/div[1]/button[1]/span[3]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='menu-item-5']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Where to? E.g. Hawaii, Mexico' and @title='search']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Where to? E.g. Hawaii, Mexico' and @title='search']").send_keys("EGYPT")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/div[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[7]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[1]/label[9]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[2]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='childAge' and @value='' and @type='number' and @placeholder='0-17']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='childAge' and @value='' and @type='number' and @placeholder='0-17']").send_keys("8")
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/div[3]/div[1]/div[2]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[1]/label[4]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[1]/label[6]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[1]/label[10]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[1]/div[1]/label[12]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[1]/div[2]/div[1]/label[9]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='FATD.steps.body.content']/div[2]/div[1]/button[1]").click()
    #
    # def test_tripadvisor_659e07c8(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[3]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("kanha national park")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[5]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[9]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_2-R29acccl:']/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "menu-item-2").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_2-R2dacccl:']/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='menu-item-2']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='menu-item-PRICELOW']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/button[1]").click()
    #
    # def test_tripadvisor_a4ddf1b0(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("jaipur")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[6]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/button[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[4]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_14-Raacl:']/div[1]/div[1]/span[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_14-Raqcl:']/div[1]/div[1]/span[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_14-Rbacl:']/div[1]/div[1]/span[3]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[4]/div[2]/span[1]/div[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[4]/div[2]/span[1]/div[1]/div[2]/div[3]/div[1]").click()
    #
    # def test_tripadvisor_71732d99(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.NAME, "q").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Orlando")
    #     self.driver.find_element(By.XPATH, "//a[@role='option']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='PERSISTENT_TRIP_SEARCH_BAR']/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='PERSISTENT_TRIP_SEARCH_BAR']/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[2]/div[7]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[2]/div[2]/div[3]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[2]/div[2]/div[4]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[6]/div[1]/div[1]/div[1]/div[2]/button[5]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[2]/div[2]/div[5]/button[1]").click()
    #
    # def test_tripadvisor_7462a685(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @placeholder='Where to?' and @title='Search']").send_keys("Tokyo, Japan")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[4]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[5]/div[1]/div[1]/div[1]/div[1]/button[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[2]/div[1]/div[1]/div[4]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @title='Search']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='searchbox' and @name='q' and @value='' and @type='search' and @title='Search']").send_keys("rail tour")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[3]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[6]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='duration_filter_contents']/ul[1]/li[2]/div[1]/span[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='menu-item-DURATION_SHORT_TO_LONG']/div[1]/span[1]").click()
    #
    # def test_tripadvisor_9eb5970c(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Sedona, AZ")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/section[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]/span[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/article[1]/div[2]/header[1]/div[1]/div[1]/a[1]/h3[1]/div[1]/span[1]/div[1]").click()
    #
    # def test_tripadvisor_2c09555a(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[4]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("San Franciso")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_50']/div[1]/div[9]/div[2]/div[4]/div[1]/label[1]").click()
    #
    # def test_tripadvisor_34293a39(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("New York City")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[7]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='PERSISTENT_TRIP_SEARCH_BAR']/div[1]/div[1]/div[1]/div[2]/button[1]/div[1]/span[1]/span[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[4]/div[2]/span[1]/div[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_20']/div[4]/div[2]/span[1]/div[1]/div[2]/div[3]/div[1]").click()
    #     self.driver.find_element(By.ID, "property_23321304").click()
    #
    # def test_tripadvisor_45ffa5b5(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[4]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("los angeles")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_50']/div[1]/div[7]/div[2]/div[5]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[11]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[61]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[11]/div[1]/div[1]/div[3]/button[1]").click()
    #     self.driver.find_element(By.ID, "secondaryText").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_2']/div[1]/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/a[1]/span[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='component_56']/div[1]/div[1]/div[2]/div[2]/div[1]/span[1]/span[1]/span[2]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[11]/div[1]/div[2]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='tripName' and @value='' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='tripName' and @value='' and @type='text']").send_keys("Los Angeles")
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[11]/div[1]/div[2]/div[1]/div[1]/form[1]/div[3]/button[1]").click()
    #
    # def test_tripadvisor_cb304f60(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[3]/a[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Egypt")
    #     self.driver.find_element(By.XPATH, "//a[@role='option']").click()
    #
    # def test_tripadvisor_8af21150(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[2]/a[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Switzerland")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #
    # def test_tripadvisor_8b1560da(self):
    #     # self.driver.get("https://www.tripadvisor.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='lithium-root']/main[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.NAME, "q").clear()
    #     self.driver.find_element(By.NAME, "q").send_keys("Toronto")
    #     self.driver.find_element(By.XPATH, "//div[@id='typeahead_results']/a[1]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='PERSISTENT_TRIP_SEARCH_BAR']/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/span[1]/span[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[3]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[3]/div[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//body[@id='BODY_BLOCK_JQUERY_REFLOW']/div[5]/div[2]/div[1]/div[1]/div[2]/div[4]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id=':component_14-Raacl:']/div[1]/div[1]/span[3]/div[1]/label[1]/span[1]").click()
    