import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from browser_helper import switch_to_new_tab_and_close_old


@pytest.mark.usefixtures("setup_class")
class TestOhioGov:
    def test_ohiogov_77269ea5(self):
        # self.driver.get("https://ohio.gov/")
        self.driver.find_element(By.XPATH, "//nav[@id='main-nav-container']/ul[1]/li[3]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='odx-main-content']/article[1]/section[1]/div[2]/div[1]/div[2]/div[2]/a[1]/div[2]/h3[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='odx-main-content']/article[1]/div[1]/div[2]/aside[1]/section[1]/div[1]/a[1]/span[1]").click()

        switch_to_new_tab_and_close_old(self.driver)

        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Child Care Program Resources')]").click()
        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Search for Early Care and Education Programs')]").click()
        # page logic changed
        # scroll_down(self.driver, 500)
        # The section that contains the button below is dynamic, sometimes other button will be displayed, so will just remove this action and directly click search for care.
        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Apply for Child Care Assistance')]").click()
        # so first click on the span then click on the link
        self.driver.find_element(By.XPATH, "//span[contains(text(),'Search for Child Care')]").click()
        self.driver.find_element(By.XPATH, "//a[text()='Search for Child Care']").click()
        switch_to_new_tab_and_close_old(self.driver)

        # actions performed by the agent is wrong
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_ddlCounty").clear()
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_ddlCounty").select("ALL")
        country_dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_ddlCounty")
        country_select = Select(country_dropdown)
        country_select.select_by_visible_text("Clinton")

        # add extra step about Step Up To Quality Rating that is missed by the agent
        step_up_dropdown = self.driver.find_element(By.ID, "ContentPlaceHolder1_ddlRating")
        step_up_select = Select(step_up_dropdown)
        step_up_select.select_by_visible_text("ANY")

        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtCity").clear()
        self.driver.find_element(By.ID, "ContentPlaceHolder1_txtCity").send_keys("Midland")
        self.driver.find_element(By.ID, "ContentPlaceHolder1_chkSaturday").click()
        self.driver.find_element(By.ID, "ContentPlaceHolder1_chkSixNoon").click()
        self.driver.find_element(By.ID, "ContentPlaceHolder1_chkTransportation").click()
        self.driver.find_element(By.XPATH, "//div[@id='formActions']/a[1]/span[1]").click()

        # The actions generated by the agent does not align with the task requirement. Will ignore below actions
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_lnkStartOver").click()
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_txtCity").clear()
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_txtCity").send_keys("Midland")
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_chkMonday").click()
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_chkAfterSchoolCare").click()
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_chkTransportation").click()
        # self.driver.find_element(By.XPATH, "//div[@id='formActions']/a[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='programSearchResults']/a[1]/span[1]/span[1]").click()
        # self.driver.find_element(By.ID, "ContentPlaceHolder1_chkTransportation").click()
        # self.driver.find_element(By.XPATH, "//div[@id='formActions']/a[1]/span[1]").click()
