import time

import pytest
from selenium.webdriver.common.by import By


@pytest.mark.usefixtures("setup_class")
class TestThumbtack:
    
    # def test_thumbtack_db14f795(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("wedding dance")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("10005")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[7]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[3]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[1]/p[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId7']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId8']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId10']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId11']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId12']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId13']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId15']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[4]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId15']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='tel' and @placeholder='(555) 555-5555']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='tel' and @placeholder='(555) 555-5555']").send_keys("5214586525")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId18']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    
    def test_thumbtack_5a55aaa5(self):
        # self.driver.get("https://www.thumbtack.com/")
        # TODO looks like this website provide two interact logics regarding the time selection! So the test steps can be different for different run! Need to think about it! Consider remove.

        # self.driver.find_element(By.XPATH, "//div[@title='Phone or Tablet Repair']").click()
        self.driver.find_element(By.XPATH, "//input[@aria-label='Search on Thumbtack']").clear()
        self.driver.find_element(By.XPATH, "//input[@aria-label='Search on Thumbtack']").send_keys("Phone or Tablet Repair")

        # self.driver.find_element(By.XPATH, "//input[@value='43235' and @type='text' and @placeholder='Enter a zip code']").clear()
        # self.driver.find_element(By.XPATH, "//input[@value='43235' and @type='text' and @placeholder='Enter a zip code']").send_keys("89116")
        # self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[3]/div[1]/div[1]/div[3]/div[1]/form[1]/div[1]/button[1]").click()
        self.driver.find_element(By.NAME, "zip_code").clear()
        self.driver.find_element(By.NAME, "zip_code").send_keys("89116")
        # somehow need to wait for a few seconds before clicking on the search button otherwise the code will pass but the click action is not actually triggered
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//button[@aria-label='Search' and @type='button' and text()='Search']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/button[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[16]/label[1]/svg[1]/g[1]/circle[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
        # selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
        time.sleep(5)
        self.driver.find_element(By.XPATH, "//div[text()='iPad mini']").click()
        self.driver.find_element(By.XPATH, "//section//div[text()='Water damage']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[1]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@data-testid='pro-list-result-price-info']").click()

        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId7']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId8']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId9']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@data-testid='request-flow-step--active']//button[@type='submit' and ./span[text()='Next']]").click()
        # deselect the at my home option since we want it to be done at the pro's location
        self.driver.find_element(By.XPATH, "//span[text()='My home, venue, etc.']").click()
        self.driver.find_element(By.XPATH, "//div[@data-testid='request-flow-step--active']//button[@type='submit' and ./span[text()='Next']]").click()
        # choose "Flexible on timeline" to avoid extra steps
        self.driver.find_element(By.XPATH, "//span[text()='Flexible on timeline']").click()
        # logic changed, need to input the description here
        self.driver.find_element(By.XPATH, "//textarea[@data-test='request-flow-text-box']").clear()
        self.driver.find_element(By.XPATH, "//textarea[@data-test='request-flow-text-box']").send_keys("not turning on")
        self.driver.find_element(By.XPATH, "//div[@data-testid='request-flow-step--active']//button[@type='submit' and ./span[text()='Next']]").click()

        # need to input an email address in the new web app
        self.driver.find_element(By.XPATH, "//input[@data-test='request-flow-text-box']").clear()
        self.driver.find_element(By.XPATH, "//input[@data-test='request-flow-text-box']").send_keys("joe@joebloggs.com")
        self.driver.find_element(By.XPATH, "//div[@data-testid='request-flow-step--active']//button[@type='submit' and ./span[text()='Next']]").click()

        # logic changed, customize time to morning or afternoon is no longer available. Just select the flexible time option now
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId10']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[2]/label[1]/div[1]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId10']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId11']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId11']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[7]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId11']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[2]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId11']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId12']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[1]/label[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId12']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[2]/label[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId12']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[5]/label[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId12']/div[2]/div[1]/div[1]/button[1]/span[1]").click()

        # moved to above
        # self.driver.find_element(By.XPATH, "//textarea[@placeholder='Describe the task or project in more detail']").clear()
        # self.driver.find_element(By.XPATH, "//textarea[@placeholder='Describe the task or project in more detail']").send_keys("not turning on")

        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId13']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        # need to give a phone number and click on submit now. Just give a fake number and click on the "Back" button to avoid sending spam data
        self.driver.find_element(By.XPATH, "//input[@data-test='request-flow-text-box' and @type='tel']").clear()
        self.driver.find_element(By.XPATH, "//input[@data-test='request-flow-text-box' and @type='tel']").send_keys("1239990000")
        self.driver.find_element(By.XPATH, "//div[@data-testid='request-flow-step--active']//button[@type='button' and ./span[text()='Back']]").click()
    
    # def test_thumbtack_606fe671(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("RESUME")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[6]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[3]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[3]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/a[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[4]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId22']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[4]/div[5]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId22']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #
    # def test_thumbtack_66b46e1d(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[8]/div[1]/div[3]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[3]/a[1]/p[1]").click()
    #
    # def test_thumbtack_725d96cd(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("wedding photographer")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("10203")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[3]/div[5]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #
    # def test_thumbtack_7ecc687c(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("personal trainer")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='' and @placeholder='Zip code']").send_keys("10040")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[3]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[5]/div[1]/div[2]/div[1]/div[3]/label[1]/svg[1]/g[1]/circle[1]").click()
    #
    # def test_thumbtack_978c579a(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("electricians")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("10203")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #
    # def test_thumbtack_ac203015(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("software developers")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='' and @placeholder='Zip code']").send_keys("10080")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[3]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[1]/label[1]/svg[1]/g[1]/circle[1]").click()
    #
    # def test_thumbtack_bb1b14f8(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("house cleaning")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='' and @placeholder='Zip code']").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #
    # def test_thumbtack_bc32ce7e(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("plumber")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("13020")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/p[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[8]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[1]/p[1]/span[1]").click()
    #
    # def test_thumbtack_cbeb50dd(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[2]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("07718")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId3']/button[1]/span[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[2]/label[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "text-filter-input").clear()
    #     self.driver.find_element(By.ID, "text-filter-input").send_keys("best")
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[1]/p[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId7']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId8']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[2]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId9']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId10']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId11']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId13']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[1]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[3]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[4]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[2]/div[5]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId14']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #
    # def test_thumbtack_60dbde86(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("Lawn Mower Repair")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[2]/div[1]/p[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "462401268066762762_desktop").clear()
    #     self.driver.find_element(By.ID, "462401268066762762_desktop").select("Push (Walk-Behind)")
    #
    # def test_thumbtack_4be07b2e(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("accountant")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[4]/div[3]/div[1]/div[2]/div[1]/div[3]/label[1]/div[1]").click()
    #
    # def test_thumbtack_4e8162bd(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("07055")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("personal trainers")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #
    # def test_thumbtack_5366344b(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("electrician")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "400000000000000000_desktop").clear()
    #     self.driver.find_element(By.ID, "400000000000000000_desktop").select("Switch and Outlet Repair")
    #     self.driver.find_element(By.ID, "468969303886233606_desktop").clear()
    #     self.driver.find_element(By.ID, "468969303886233606_desktop").select("1 switch or outlet")
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[4]/div[2]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[4]/div[2]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/button[1]/span[1]/span[1]").click()
    #
    # def test_thumbtack_dcbcd57e(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("handymen")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("13020")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/button[1]").click()
    #     self.driver.find_element(By.ID, "text-filter-input").clear()
    #     self.driver.find_element(By.ID, "text-filter-input").send_keys("fastest")
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[3]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/main[1]/section[5]/div[1]/div[1]/div[1]/button[1]/span[1]/span[1]/span[2]").click()
    #
    # def test_thumbtack_255b6359(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("60504")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[6]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[1]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[4]/div[1]/div[2]/div[1]/div[1]/label[1]/svg[1]/g[1]/circle[1]").click()
    #
    # def test_thumbtack_27b8672e(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Job Board')]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='Department-Filter']/div[1]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='Location-Filter']/div[1]/div[1]/div[1]/label[1]/div[1]").click()
    #
    # def test_thumbtack_37c0dd01(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("07055")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("mold inspectors")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[5]/div[4]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[4]/label[1]/div[1]").click()
    #
    # def test_thumbtack_3f9f6a76(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("videographer")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[3]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[2]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[3]/div[2]/div[1]/div[1]/label[2]/span[1]").click()
    #     self.driver.find_element(By.ID, "462400931864944645_desktop").clear()
    #     self.driver.find_element(By.ID, "462400931864944645_desktop").select("Concert / performance")
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[4]/div[4]/div[1]/div[2]/div[1]/div[2]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #
    # def test_thumbtack_4228e61c(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("Plumber")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId3']/button[1]/span[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[4]").click()
    #
    # def test_thumbtack_0baad732(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Cost estimates')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/a[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='43235' and @type='text' and @placeholder='Enter a zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='43235' and @type='text' and @placeholder='Enter a zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='43235' and @type='text' and @placeholder='Enter a zip code']").send_keys("07055")
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[3]/div[1]/div[1]/div[3]/div[1]/form[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[7]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'See updated estimates')]").click()
    #
    # def test_thumbtack_1ad890b4(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("DOG TRAINING")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='zip_code' and @value='43235' and @placeholder='Zip code']").send_keys("90011")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId3']/button[1]/span[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[3]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[5]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/label[1]/svg[1]/g[1]/circle[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[4]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId25']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[4]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId25']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId26']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId27']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[3]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId28']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[3]/label[1]/figure[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId28']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId29']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId30']/div[1]/div[1]/ol[1]/li[1]/div[1]/div[1]/div[1]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId30']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId32']/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    #
    # def test_thumbtack_2077e3c4(self):
    #     # self.driver.get("https://www.thumbtack.com/")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='What’s on your to-do list?']").send_keys("landscaper")
    #     self.driver.find_element(By.XPATH, "//form[@id='uniqueId4']/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]/div[1]/div[2]/div[2]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/label[5]/span[1]").click()
    #     self.driver.find_element(By.ID, "462401582472601612_desktop").clear()
    #     self.driver.find_element(By.ID, "462401582472601612_desktop").select("Home")
    #     self.driver.find_element(By.XPATH, "//div[@id='app-page-root']/div[1]/div[1]/div[4]/div[1]/div[1]/aside[1]/div[1]/div[1]/div[1]/div[1]/div[3]/button[1]/span[1]/span[1]").click()
    