import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestMarriott:
    
    def test_marriott_5b888855(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-0b89d8d0f9']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'CHECK BALANCE')]").click()
        self.driver.find_element(By.ID, "cws_txt_gcNum").click()
        self.driver.find_element(By.ID, "cws_txt_gcNum").clear()
        self.driver.find_element(By.ID, "cws_txt_gcNum").send_keys("1234567")
        self.driver.find_element(By.ID, "cws_txt_gcPin").click()
        self.driver.find_element(By.ID, "cws_txt_gcPin").clear()
        self.driver.find_element(By.ID, "cws_txt_gcPin").send_keys("0001")
        self.driver.find_element(By.ID, "cws_btn_checkGcBalance").click()
    
    def test_marriott_6679ce8e(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.ID, "1680950992771-search-destination").clear()
        self.driver.find_element(By.ID, "1680950992771-search-destination").send_keys("Dubai")
        self.driver.find_element(By.XPATH, "//li[@id='1680951013755-search-destination-option-0']/p[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951019959-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951026754-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951035642-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[4]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951043093-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951052325-find-a-hotel-homePage-form']/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951052325-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951052325-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[3]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951052325-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680951052325-find-a-hotel-homePage-form']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='PropertyRecordsSearchToolBar76d6']/div[1]/div[2]/span[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='sort']/li[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SearchFilter15be']/div[1]/span[4]").click()
        self.driver.find_element(By.XPATH, "//a[@title='Marriott Hotels & Resorts (3)']").click()
        self.driver.find_element(By.XPATH, "//div[@id='accordion_brands']/fieldset[1]/div[2]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SearchFilter15be']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/form[1]/button[1]").click()
    
    def test_marriott_d494ed27(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-0b89d8d0f9']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Browse Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//label[@id='cws_lbl_407903']/img[1]").click()
    
    def test_marriott_bf866e4d(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-26d2e6af1a']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a Hotel')]").click()
        self.driver.find_element(By.ID, "QQW0BFZH_search-location").clear()
        self.driver.find_element(By.ID, "QQW0BFZH_search-location").send_keys("tallahassee")
        self.driver.find_element(By.XPATH, "//form[@id='advanced-search-form']/div[1]/div[1]/div[2]/ul[1]/li[2]/a[1]/strong[1]/strong[1]").click()
        self.driver.find_element(By.ID, "QQW0BFZH_hotel-fromDate").click()
        self.driver.find_element(By.XPATH, "//form[@id='advanced-search-form']/div[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/thead[1]/tr[1]/th[3]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'3')]").click()
        self.driver.find_element(By.ID, "QQW0BFZH_hotel-toDate").clear()
        self.driver.find_element(By.ID, "QQW0BFZH_hotel-toDate").send_keys("5")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'5')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'5')]").click()
        self.driver.find_element(By.XPATH, "//form[@id='advanced-search-form']/div[1]/div[5]/div[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='advanced-search-form']/div[1]/div[5]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/a[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='advanced-search-form']/div[1]/div[5]/div[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit' and @title='']").click()
        self.driver.find_element(By.XPATH, "//div[@id='property-record-map-TLHAC']/div[1]/div[2]/div[1]/div[1]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tab0']/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[2]/button[1]").click()
        self.driver.find_element(By.ID, "termsAndConditionsAPR").click()
        self.driver.find_element(By.XPATH, "//button[@name='submit' and @type='submit']").click()
    
    def test_marriott_9ba4e237(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Earn Points')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Learn More')]").click()
    
    def test_marriott_013faefc(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.ID, "1681863347042-search-destination").clear()
        self.driver.find_element(By.ID, "1681863347042-search-destination").send_keys("Carribbean")
        self.driver.find_element(By.XPATH, "//form[@id='1681863490938-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681863501387-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[6]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681863513971-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[3]/div[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681863522814-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681863528529-find-a-hotel-homePage-form']/button[1]").click()
    
    def test_marriott_06a6d90b(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.ID, "1681035762615-search-destination").clear()
        self.driver.find_element(By.ID, "1681035762615-search-destination").send_keys("NIAGRA FALLS")
        self.driver.find_element(By.XPATH, "//li[@id='1681035835783-search-destination-option-0']/p[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035840958-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035853756-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[3]/div[4]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035861955-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[3]/div[7]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035868051-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[3]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/div[2]/div[1]/div[1]/div[2]/div[5]/div[1]/div[2]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1681035873889-find-a-hotel-homePage-form']/button[1]").click()
        self.driver.find_element(By.ID, "Show rates with taxes and all fees").click()
        self.driver.find_element(By.ID, "availabilityFilterToggle").click()
        self.driver.find_element(By.XPATH, "//div[@id='SuggestedFilters2642']/div[1]/form[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SuggestedFiltersdfdd']/div[1]/form[1]/div[1]/div[1]/ul[1]/li[4]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SearchFilter6058']/div[1]/span[5]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='price-list']/li[3]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SearchFilter6058']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/form[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='PropertyRecordsSearchToolBard941']/div[1]/div[2]/span[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='sort']/li[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='property-record-map-YYZTO']/div[1]/div[2]/div[1]/div[1]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tab1']/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tile-global-privacy-consent']/div[2]/div[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//button[@name='submit' and @type='submit']").click()
    
    def test_marriott_b49f0d3e(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-0b89d8d0f9']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[7]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Group Travel')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Group Travel for Students')]").click()
        self.driver.find_element(By.ID, "PDHTNM2C_destination").clear()
        self.driver.find_element(By.ID, "PDHTNM2C_destination").send_keys("washington")
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[2]/div[2]/ul[1]/li[2]/a[1]").click()
        self.driver.find_element(By.ID, "PDHTNM2C_hotel-fromDate").click()
        self.driver.find_element(By.XPATH, "//div[@role='button' and @title='Next month']").click()
        self.driver.find_element(By.XPATH, "//table[@id='PDHTNM2C_hotel-fromToDate_table']/tbody[1]/tr[2]/td[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//table[@id='PDHTNM2C_hotel-fromToDate_table']/tbody[1]/tr[2]/td[6]/div[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[6]/div[1]/div[2]").click()
        self.driver.find_element(By.ID, "selectric-opt03").click()
        self.driver.find_element(By.ID, "guestRooms_PDHTNM2C").clear()
        self.driver.find_element(By.ID, "guestRooms_PDHTNM2C").send_keys("7")
        self.driver.find_element(By.ID, "eventSpace_PDHTNM2C").clear()
        self.driver.find_element(By.ID, "eventSpace_PDHTNM2C").send_keys("50")
        self.driver.find_element(By.XPATH, "//input[@name='submit' and @value='Find' and @type='submit' and @title='Find']").click()
        self.driver.find_element(By.XPATH, "//div[@id='GroupSearchFiltercd25']/div[1]/span[4]").click()
        self.driver.find_element(By.XPATH, "//div[@id='accordion_brands']/fieldset[1]/div[1]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    
    def test_marriott_e48f848d(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.ID, "abcd-item-8640b3fae9-button").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Students & Grads')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Internship')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Hotel Internships')]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/section[1]/div[1]/div[1]/div[1]/div[2]/div[1]/article[1]/div[1]/section[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/search-filters-panel-horizontal[1]/div[1]/div[1]/search-filters-horizontal[1]/div[1]/ul[1]/search-facet-dropdown[1]/div[1]/dropdown-trigger[1]/search-facet-horizontal[1]/li[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@title='Germany']").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Posting Dates')]").click()
        self.driver.find_element(By.XPATH, "//button[@title='Less than 7 days']").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Voyage Program, European Union Member States')]").click()
        self.driver.find_element(By.XPATH, "//oj-dialog[@id='ui-id-11']/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/job-details-checker[1]/job-details-loader[1]/job-details-page[1]/div[1]/job-details-content[1]/div[1]/article[1]/div[1]/section[1]/div[1]/div[8]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
    
    def test_marriott_c9740663(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.ID, "1680950086709-search-destination").clear()
        self.driver.find_element(By.ID, "1680950086709-search-destination").send_keys("Los Angeles")
        self.driver.find_element(By.XPATH, "//li[@id='1680950122737-search-destination-option-0']/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950128779-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950148061-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950155900-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[3]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950166323-find-a-hotel-homePage-form']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950172840-find-a-hotel-homePage-form']/div[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950178785-find-a-hotel-homePage-form']/div[2]/div[2]/div[1]/fieldset[1]/div[1]/div[3]/label[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='1680950195566-find-a-hotel-homePage-form']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='PropertyRecordsSearchToolBar28ec']/div[1]/div[2]/span[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='sort']/li[5]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SuggestedFilters8c43']/div[1]/form[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SuggestedFilters40fd']/div[1]/form[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SuggestedFilters109a']/div[1]/form[1]/div[1]/div[1]/ul[1]/li[4]/a[1]/span[1]").click()
    
    def test_marriott_8e4dbb21(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-26d2e6af1a']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Book Meetings & Events')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='CardArticle5f9c']/section[1]/div[2]/div[1]/h3[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[6]/div[1]/div[2]/label[1]").click()
        self.driver.find_element(By.ID, "selectric-opt02").click()
        self.driver.find_element(By.ID, "IL0L0YJ4_destination").clear()
        self.driver.find_element(By.ID, "IL0L0YJ4_destination").send_keys("Venice Beach")
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[2]/div[2]/ul[1]/li[2]/a[1]").click()
        self.driver.find_element(By.ID, "eventSpace_IL0L0YJ4").clear()
        self.driver.find_element(By.ID, "eventSpace_IL0L0YJ4").send_keys("100")
        self.driver.find_element(By.ID, "IL0L0YJ4_hotel-fromDate").click()
        self.driver.find_element(By.XPATH, "//div[@role='button' and @title='Next month']").click()
        self.driver.find_element(By.XPATH, "//div[@role='button' and @title='Next month']").click()
        self.driver.find_element(By.XPATH, "//div[@role='button' and @title='Next month']").click()
        self.driver.find_element(By.XPATH, "//table[@id='IL0L0YJ4_hotel-fromToDate_table']/tbody[1]/tr[2]/td[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@name='submit' and @value='Find' and @type='submit' and @title='Find']").click()
        self.driver.find_element(By.XPATH, "//div[@id='property-record-map-LAXDM']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/a[1]/h2[1]/span[1]").click()
    
    def test_marriott_8eef04e2(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-26d2e6af1a']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Deals')]").click()
        self.driver.find_element(By.XPATH, "//li[@id='idmarriottpicksforyou-slide01']/div[1]/div[1]/a[1]/h3[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='offer-variation-mbo-mpo-hero-details-text']/div[1]/div[2]/div[1]/div[1]/div[2]/ul[1]/li[4]").click()
    
    def test_marriott_acc13b3d(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.ID, "abcd-item-20c0ec852f-button").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Browse Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cardCategories']/button[2]").click()
        self.driver.find_element(By.XPATH, "//label[@id='cws_lbl_407881']/img[1]").click()
        self.driver.find_element(By.ID, "cws_txt_gcBuyAmt").clear()
        self.driver.find_element(By.ID, "cws_txt_gcBuyAmt").send_keys("150")
        self.driver.find_element(By.XPATH, "//label[@id='cws_lbl_408200']/span[1]").click()
        self.driver.find_element(By.ID, "cws_txt_gcBuyTo").clear()
        self.driver.find_element(By.ID, "cws_txt_gcBuyTo").send_keys("Clara")
        self.driver.find_element(By.ID, "cws_txt_gcBuyFrom").clear()
        self.driver.find_element(By.ID, "cws_txt_gcBuyFrom").send_keys("James")
        self.driver.find_element(By.ID, "cws_txt_gcMsg_1").clear()
        self.driver.find_element(By.ID, "cws_txt_gcMsg_1").send_keys("Happy Christmas")
        self.driver.find_element(By.ID, "cws_btn_gcBuyAdd").click()
        self.driver.find_element(By.ID, "cws_btn_gcBuyCheckout").click()
    
    def test_marriott_56d210ec(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-0b89d8d0f9']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[7]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Book An Event')]").click()
        self.driver.find_element(By.ID, "S8JGJ4NA_destination").clear()
        self.driver.find_element(By.ID, "S8JGJ4NA_destination").send_keys("Boston")
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[2]/div[2]/ul[1]/li[2]/a[1]").click()
        self.driver.find_element(By.ID, "S8JGJ4NA_hotel-fromDate").click()
        self.driver.find_element(By.XPATH, "//div[@role='button' and @title='Next month']").click()
        self.driver.find_element(By.XPATH, "//table[@id='S8JGJ4NA_hotel-fromToDate_table']/tbody[1]/tr[5]/td[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//table[@id='S8JGJ4NA_hotel-fromToDate_table']/tbody[1]/tr[5]/td[5]/div[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[6]/div[1]/div[2]/label[1]").click()
        self.driver.find_element(By.ID, "selectric-opt01").click()
        self.driver.find_element(By.ID, "guestRooms_S8JGJ4NA").clear()
        self.driver.find_element(By.ID, "guestRooms_S8JGJ4NA").send_keys("1")
        self.driver.find_element(By.ID, "eventSpace_S8JGJ4NA").clear()
        self.driver.find_element(By.ID, "eventSpace_S8JGJ4NA").send_keys("20")
        self.driver.find_element(By.XPATH, "//input[@name='submit' and @value='Find' and @type='submit' and @title='Find']").click()
    
    def test_marriott_69065697(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Redeem Points')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Learn More')]").click()
    
    def test_marriott_76514d5c(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//div[@id='container-0b89d8d0f9']/div[1]/div[1]/header[1]/div[2]/div[2]/div[1]/div[2]/nav[2]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Shop Marriott')]").click()
        self.driver.find_element(By.XPATH, "//a[@id='TN_l1_PillowsLink']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[@id='CD_MAR-107-1']/div[1]/h2[1]/span[1]").click()
        self.driver.find_element(By.ID, "MAR-107-1Mar_PillowProtector").clear()
        self.driver.find_element(By.ID, "MAR-107-1Mar_PillowProtector").select("Queen")
        self.driver.find_element(By.XPATH, "//input[@name='quantity' and @value='1' and @type='number' and @title='quantity']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='quantity' and @value='1' and @type='number' and @title='quantity']").send_keys("2")
        self.driver.find_element(By.XPATH, "//button[@id='addToCartBtn']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Checkout')]").click()
    
    def test_marriott_2ef470ab(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//button[@id='abcd-item-20c0ec852f-button']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Activities')]").click()
        self.driver.find_element(By.ID, "locationSearch:input").clear()
        self.driver.find_element(By.ID, "locationSearch:input").send_keys("New York")
        self.driver.find_element(By.XPATH, "//li[@id='q']/a[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Select Activities')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Cultural Tours')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Any')]").click()
        self.driver.find_element(By.XPATH, "//li[@value='5']").click()
        self.driver.find_element(By.ID, "price:input").clear()
        self.driver.find_element(By.ID, "price:input").send_keys("75")
        self.driver.find_element(By.XPATH, "//span[contains(.,'mm/dd/yyyy-mm/dd/yyyy')]").click()
        self.driver.find_element(By.XPATH, "//abbr[contains(.,'7')]").click()
        self.driver.find_element(By.XPATH, "//abbr[contains(.,'7')]").click()
    
    def test_marriott_4d311ce8(self):
        # self.driver.get("https://www.marriott.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Business Meetings')]").click()
        self.driver.find_element(By.ID, "LQUPKTMY_destination").clear()
        self.driver.find_element(By.ID, "LQUPKTMY_destination").send_keys("new delhi")
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[2]/div[2]/ul[1]/li[2]/a[1]").click()
        self.driver.find_element(By.ID, "LQUPKTMY_hotel-fromDate").click()
        self.driver.find_element(By.XPATH, "//table[@id='LQUPKTMY_hotel-fromToDate_table']/tbody[1]/tr[5]/td[7]/div[1]").click()
        self.driver.find_element(By.XPATH, "//table[@id='LQUPKTMY_hotel-fromToDate_table']/tbody[1]/tr[6]/td[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[6]/div[1]/div[2]/label[1]").click()
        self.driver.find_element(By.ID, "selectric-opt01").click()
        self.driver.find_element(By.XPATH, "//form[@id='group-search-form']/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/span[6]").click()
        self.driver.find_element(By.ID, "guestRooms_LQUPKTMY").clear()
        self.driver.find_element(By.ID, "guestRooms_LQUPKTMY").send_keys("1")
        self.driver.find_element(By.ID, "eventSpace_LQUPKTMY").clear()
        self.driver.find_element(By.ID, "eventSpace_LQUPKTMY").send_keys("7")
        self.driver.find_element(By.XPATH, "//input[@name='submit' and @value='Find' and @type='submit' and @title='Find']").click()
        self.driver.find_element(By.XPATH, "//div[@id='GroupSearchFiltereda6']/div[1]/a[1]/span[2]").click()
        self.driver.find_element(By.ID, "label-amenities").click()
        self.driver.find_element(By.XPATH, "//ul[@id='amenities-list']/li[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='amenities-list']/li[6]/label[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//div[@id='GroupSearchFiltere2bd']/div[1]/span[5]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='distance-list']/li[2]/label[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Add to RFP')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Create RFP')]").click()
    