import time
import pytest
from selenium.webdriver.common.by import By


@pytest.mark.usefixtures("setup_class")
class TestAa:
    
    # def test_aa_c8d65dd7(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//div[@id='bookingCheckboxContainer']/div[1]/div[2]/label[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").send_keys("mumbai")
    #     self.driver.find_element(By.ID, "ui-id-8").click()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").send_keys("washington")
    #     self.driver.find_element(By.ID, "ui-id-10").click()
    #     self.driver.find_element(By.ID, "flightSearchForm.adultOrSeniorPassengerCount").clear()
    #     self.driver.find_element(By.ID, "flightSearchForm.adultOrSeniorPassengerCount").select("5")
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.ID, "flightSearchForm.button.reSubmit").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='slice0Flight12MainCabin']/div[1]/div[2]/span[1]").click()
    #     self.driver.find_element(By.ID, "btn-main-cabin").click()
    #     self.driver.find_element(By.ID, "button_continue").click()
    #
    # def test_aa_fe471e16(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").send_keys("new york")
    #     self.driver.find_element(By.ID, "ui-id-9").click()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").send_keys("new orleans")
    #     self.driver.find_element(By.ID, "ui-id-23").click()
    #     self.driver.find_element(By.ID, "flightSearchForm.adultOrSeniorPassengerCount").clear()
    #     self.driver.find_element(By.ID, "flightSearchForm.adultOrSeniorPassengerCount").select("3")
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'14')]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='reservationFlightSearchForm']/div[4]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'16')]").click()
    #     self.driver.find_element(By.ID, "flightSearchForm.button.reSubmit").click()
    #
    # def test_aa_0c7a69f9(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").send_keys("Chicago")
    #     time.sleep(2)
    #     # self.driver.find_element(By.XPATH, "//a[contains(text(),'CHI - Chicago, IL')]").click()
    #     self.driver.find_element(By.ID, "ui-id-8").click()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").send_keys("London")
    #     self.driver.find_element(By.ID, "ui-id-10").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'20')]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='reservationFlightSearchForm']/div[4]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'23')]").click()
    #     self.driver.find_element(By.ID, "flightSearchForm.button.reSubmit").click()
    #
    # def test_aa_0f63c624(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),\"We're hiring! Join our team\")]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/div[4]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'View All Jobs')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='q' and @type='text' and @placeholder='Search by Keyword']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='q' and @type='text' and @placeholder='Search by Keyword']").send_keys("developer")
    #     self.driver.find_element(By.XPATH, "//input[@name='locationsearch' and @type='text' and @placeholder='Search by Location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='locationsearch' and @type='text' and @placeholder='Search by Location']").send_keys("dallas")
    #     self.driver.find_element(By.XPATH, "//input[@value='Search Jobs' and @type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Developer/ Senior Developer, IT')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@role='spinbutton' and @name='frequency' and @value='7' and @type='number']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@role='spinbutton' and @name='frequency' and @value='7' and @type='number']").send_keys("8")
    #     self.driver.find_element(By.ID, "savesearch-link").click()
    #
    # def test_aa_16e81dcf(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//form[@id='reservationFlightSearchForm']/div[1]/div[1]/ul[1]/li[2]/label[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.originAirport").send_keys("san francisco")
    #     self.driver.find_element(By.ID, "ui-id-8").click()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").clear()
    #     self.driver.find_element(By.ID, "reservationFlightSearchForm.destinationAirport").send_keys("new york")
    #     self.driver.find_element(By.ID, "ui-id-9").click()
    #     self.driver.find_element(By.ID, "flightSearchForm.adultOrSeniorPassengerCount").clear()
    #     self.driver.find_element(By.ID, "flightSearchForm.adultOrSeniorPassengerCount").select("2")
    #     self.driver.find_element(By.ID, "aa-leavingOn").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='reservationFlightSearchForm']/div[4]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'9')]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='reservationFlightSearchForm']/div[4]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'19')]").click()
    #     self.driver.find_element(By.ID, "fhServiceClass").clear()
    #     self.driver.find_element(By.ID, "fhServiceClass").select("First")
    #     self.driver.find_element(By.ID, "flightSearchForm.button.vacationSubmit").click()
    #
    # def test_aa_26fff471(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Receipts and refunds')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Check the status of a refund')]").click()
    #     self.driver.find_element(By.ID, "ticketNumber-text").click()
    #     self.driver.find_element(By.ID, "ticketNumber-text").clear()
    #     self.driver.find_element(By.ID, "ticketNumber-text").send_keys("1234567890123")
    #     self.driver.find_element(By.ID, "firstName-text").click()
    #     self.driver.find_element(By.ID, "firstName-text").clear()
    #     self.driver.find_element(By.ID, "firstName-text").send_keys("John")
    #     self.driver.find_element(By.ID, "lastName-text").click()
    #     self.driver.find_element(By.ID, "lastName-text").clear()
    #     self.driver.find_element(By.ID, "lastName-text").send_keys("Davis")
    #     self.driver.find_element(By.ID, "submitButton").click()
    #
    # def test_aa_4947d606(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Receipts and refunds')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Receipts for tickets and fees')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@type='text' and @placeholder='13-digit number']").click()
    #     self.driver.find_element(By.XPATH, "//input[@type='text' and @placeholder='13-digit number']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@type='text' and @placeholder='13-digit number']").send_keys("1234567890123")
    #     self.driver.find_element(By.XPATH, "//input[@type='text' and @placeholder='']").click()
    #     self.driver.find_element(By.XPATH, "//input[@type='text' and @placeholder='']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@type='text' and @placeholder='']").send_keys("Davis")
    #     self.driver.find_element(By.ID, "button").click()
    #
    # def test_aa_c175fe34(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-flightStatus").click()
    #     self.driver.find_element(By.ID, "originAirport").clear()
    #     self.driver.find_element(By.ID, "originAirport").send_keys("London")
    #     self.driver.find_element(By.ID, "ui-id-8").click()
    #     self.driver.find_element(By.ID, "destinationAirport").clear()
    #     self.driver.find_element(By.ID, "destinationAirport").send_keys("New York")
    #     self.driver.find_element(By.ID, "ui-id-18").click()
    #     self.driver.find_element(By.ID, "travelDateDropdown").clear()
    #     self.driver.find_element(By.ID, "travelDateDropdown").select("Friday, April 7")
    #     self.driver.find_element(By.ID, "flightSchedulesSearchButton").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Check status')]").click()
    #
    # def test_aa_f804150b(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Hotel')]").click()
    #     self.driver.find_element(By.ID, "ss").clear()
    #     self.driver.find_element(By.ID, "ss").send_keys("New York City")
    #     self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[2]/td[6]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[2]/td[7]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[4]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Price (lowest first)')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/h3[1]/a[1]/span[1]").click()
    #
    # def test_aa_4b2bb9e4(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-flightStatus").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Create flight status notification')]").click()
    #     self.driver.find_element(By.ID, "originAirport").clear()
    #     self.driver.find_element(By.ID, "originAirport").send_keys("bhz")
    #     time.sleep(2)
    #     self.driver.find_element(By.ID, "ui-id-6").click()
    #     self.driver.find_element(By.ID, "destinationAirport").clear()
    #     self.driver.find_element(By.ID, "destinationAirport").send_keys("ewn")
    #     self.driver.find_element(By.ID, "ui-id-7").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'30')]").click()
    #     self.driver.find_element(By.ID, "flightSchedulesSearchButton").click()
    #     self.driver.find_element(By.XPATH, "//tbody[@id='resultsTableBody']/tr[3]/td[6]/div[2]/button[1]").click()
    #     self.driver.find_element(By.ID, "emailMessageContactId").clear()
    #     self.driver.find_element(By.ID, "emailMessageContactId").send_keys("lin.lon@gmail.com")
    #     self.driver.find_element(By.ID, "confirmEmailMessageContactId").clear()
    #     self.driver.find_element(By.ID, "confirmEmailMessageContactId").send_keys("lin.lon@gmail.com")
    #     self.driver.find_element(By.XPATH, "//button[@id='createFsnDialogButton0']/span[1]").click()
    #
    # def test_aa_63529dc2(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-flightStatus").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='flightStatusView']/div[1]/div[1]/ul[1]/li[2]/label[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "flightNumber").clear()
    #     self.driver.find_element(By.ID, "flightNumber").send_keys("12345678")
    #     self.driver.find_element(By.ID, "travelDateDropdown").clear()
    #     self.driver.find_element(By.ID, "travelDateDropdown").select("Friday, April 7")
    #     self.driver.find_element(By.ID, "flightSchedulesSearchButton").click()

    def test_aa_6c28458c(self):
        # self.driver.get("https://www.aa.com/homePage.do")
        # self.driver.find_element(By.ID, "plan-travel-expander").click()
        adc_header_element = self.driver.find_element(By.CSS_SELECTOR, "adc-header")
        main_navigation_element = adc_header_element.shadow_root.find_element(By.ID, "main-navigation")
        plan_travel_element = main_navigation_element.find_element(By.CSS_SELECTOR, "adc-tab[label='Plan travel']")
        plan_travel_element.click()

        # wrapped click with wait for element to be clickable, no need to use thread sleep here
        # time.sleep(3)
        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Flights')]").click()
        new_adc_header_element = self.driver.find_element(By.CSS_SELECTOR, "adc-header")
        new_main_navigation_element = new_adc_header_element.shadow_root.find_element(By.ID, "main-navigation")
        hp_header_link_element = new_main_navigation_element.find_element(By.CSS_SELECTOR, "hp-header-link[href*='/reservation/roundTripSearchAccess.do'][class='panel-links adc-link']")
        # https://stackoverflow.com/questions/49906451/web-driver-click-on-element-within-shadowdom-is-returning-error-messageunk
        # selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'defaultView')
        # seems like a bug with the framework: https://issues.chromium.org/issues/42322743
        self.driver.execute_script("arguments[0].click()", hp_header_link_element.shadow_root.find_element(By.CSS_SELECTOR, "a"))
        # hp_header_link_element.shadow_root.find_element(By.CSS_SELECTOR, "a").click()

        # wrapped click with wait for element to be clickable, no need to use thread sleep here
        # time.sleep(5)
        self.driver.find_element(By.XPATH, "//span[contains(.,'Multi city')]").click()
        self.driver.find_element(By.ID, "segments0.origin").click()
        self.driver.find_element(By.ID, "segments0.origin").clear()
        self.driver.find_element(By.ID, "segments0.origin").send_keys("JFK")
        self.driver.find_element(By.XPATH, "//a[contains(.,'JFK - New York John F Kennedy Intl, NY')]").click()
        self.driver.find_element(By.ID, "segments0.destination").click()
        self.driver.find_element(By.ID, "segments0.destination").clear()
        self.driver.find_element(By.ID, "segments0.destination").send_keys("Heathrow")
        self.driver.find_element(By.XPATH, "//a[contains(., 'LHR - London Heathrow, United Kingdom')]").click()
        self.driver.find_element(By.ID, "segments0.travelDate").clear()
        self.driver.find_element(By.ID, "segments0.travelDate").send_keys("04/19/2025")
        self.driver.find_element(By.ID, "segments1.origin").click()
        self.driver.find_element(By.ID, "segments1.origin").clear()
        self.driver.find_element(By.ID, "segments1.origin").send_keys("Heathrow")
        self.driver.find_element(By.XPATH, "/html/body/ul[3]/li/a").click()
        self.driver.find_element(By.ID, "segments1.destination").click()
        self.driver.find_element(By.ID, "segments1.destination").clear()
        self.driver.find_element(By.ID, "segments1.destination").send_keys("CDG")
        self.driver.find_element(By.XPATH, "//a[contains(., 'CDG - Paris Charles de Gaulle, France')]").click()
        self.driver.find_element(By.ID, "segments1.travelDate").clear()
        self.driver.find_element(By.ID, "segments1.travelDate").send_keys("04/21/2025")
        self.driver.find_element(By.ID, "addFlightLink").click()
        self.driver.find_element(By.ID, "segments2.origin").click()
        self.driver.find_element(By.ID, "segments2.origin").clear()
        self.driver.find_element(By.ID, "segments2.origin").send_keys("CDG")
        self.driver.find_element(By.XPATH, "/html/body/ul[5]/li/a").click()
        self.driver.find_element(By.ID, "segments2.destination").click()
        self.driver.find_element(By.ID, "segments2.destination").clear()
        self.driver.find_element(By.ID, "segments2.destination").send_keys("JFK")
        self.driver.find_element(By.XPATH, "/html/body/ul[6]/li/a").click()
        self.driver.find_element(By.ID, "segments2.travelDate").clear()
        self.driver.find_element(By.ID, "segments2.travelDate").send_keys("04/23/2025")
        self.driver.find_element(By.ID, "flightSearchSubmitBtn").click()

        # wrapped click with wait for element to be clickable, no need to use thread sleep here. Need to set the maximum timeout to 60s
        # time.sleep(60)
        self.driver.find_element(By.ID, "btn-sort-by-duration").click()

    # def test_aa_708cbe51(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-flightStatus").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Create flight status notification')]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='flightScheduleSearchView']/div[2]/div[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "originAirport").clear()
    #     self.driver.find_element(By.ID, "originAirport").send_keys("bhz")
    #     self.driver.find_element(By.ID, "ui-id-6").click()
    #     self.driver.find_element(By.ID, "destinationAirport").clear()
    #     self.driver.find_element(By.ID, "destinationAirport").send_keys("ewn")
    #     self.driver.find_element(By.ID, "ui-id-7").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'30')]").click()
    #     self.driver.find_element(By.ID, "flightSchedulesSearchButton").click()
    #
    # def test_aa_7b05f537(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-flightStatus").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='flightStatusView']/div[1]/div[1]/ul[1]/li[2]/label[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "flightNumber").click()
    #     self.driver.find_element(By.ID, "flightNumber").clear()
    #     self.driver.find_element(By.ID, "flightNumber").send_keys("6944")
    #     # self.driver.find_element(By.ID, "travelDateDropdown").clear()
    #     self.driver.find_element(By.ID, "travelDateDropdown").select("Thursday, April 6")
    #     self.driver.find_element(By.ID, "flightSchedulesSearchButton").click()
    #
    # def test_aa_8888ebb8(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "plan-travel-expander").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Flights')]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='ui-id-4']/span[2]").click()
    #     self.driver.find_element(By.ID, "segments0.origin").click()
    #     self.driver.find_element(By.ID, "segments0.origin").clear()
    #     self.driver.find_element(By.ID, "segments0.origin").send_keys("JFK")
    #     self.driver.find_element(By.ID, "ui-id-11").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='airportSection']/div[2]/div[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "segments0.destination").click()
    #     self.driver.find_element(By.ID, "segments0.destination").clear()
    #     self.driver.find_element(By.ID, "segments0.destination").send_keys("Heathrow")
    #     self.driver.find_element(By.ID, "ui-id-12").click()
    #     self.driver.find_element(By.ID, "segments0.travelDate").click()
    #     self.driver.find_element(By.ID, "segments0.travelDate").clear()
    #     self.driver.find_element(By.ID, "segments0.travelDate").send_keys("04/22/2023")
    #     self.driver.find_element(By.ID, "passengerCount").clear()
    #     self.driver.find_element(By.ID, "passengerCount").select("1")
    #     self.driver.find_element(By.ID, "passengers0.passengerType").clear()
    #     self.driver.find_element(By.ID, "passengers0.passengerType").select("Adult (16-64)")
    #     self.driver.find_element(By.ID, "revenueSearchOption").clear()
    #     self.driver.find_element(By.ID, "revenueSearchOption").select("Lowest fare")
    #     self.driver.find_element(By.ID, "flightSearchSubmitBtn").click()
    #
    # def test_aa_895f32c1(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),\"We're hiring! Join our team\")]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Search open jobs')]").click()
    #     self.driver.find_element(By.ID, "location").clear()
    #     self.driver.find_element(By.ID, "location").send_keys("TX")
    #     self.driver.find_element(By.ID, "searchfilter-submit").click()
    #
    # def test_aa_8b130a70(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-myTripsCheckIn").click()
    #     self.driver.find_element(By.ID, "findReservationForm.lastName").clear()
    #     self.driver.find_element(By.ID, "findReservationForm.lastName").send_keys("Smith")
    #     self.driver.find_element(By.ID, "findReservationForm.recordLocator").clear()
    #     self.driver.find_element(By.ID, "findReservationForm.recordLocator").send_keys("X899987799")
    #     self.driver.find_element(By.ID, "findReservationForm.submit").click()
    #
    # def test_aa_8b39c9ac(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "jq-flightStatus").click()
    #     self.driver.find_element(By.ID, "originAirport").clear()
    #     self.driver.find_element(By.ID, "originAirport").send_keys("san antonio")
    #     # self.driver.find_element(By.ID, "ui-id-8").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'SAT - San Antonio International, TX')]").click()
    #     self.driver.find_element(By.ID, "destinationAirport").clear()
    #     self.driver.find_element(By.ID, "destinationAirport").send_keys("washington")
    #     self.driver.find_element(By.ID, "ui-id-10").click()
    #     self.driver.find_element(By.ID, "flightSchedulesSearchButton").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Check status')]").click()
    #
    # def test_aa_a51b649f(self):
    #     # self.driver.get("https://www.aa.com/homePage.do")
    #     self.driver.find_element(By.ID, "aa-search-field").clear()
    #     self.driver.find_element(By.ID, "aa-search-field").send_keys("travel credit")
    #     self.driver.find_element(By.ID, "aa-search-field").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='search-results']/ul[1]/li[2]/a[1]/h2[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='lastName' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='lastName' and @type='text']").send_keys("sin")
    #     self.driver.find_element(By.XPATH, "//input[@name='ticketNumber' and @type='text' and @placeholder='Ex. 001234567890']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='ticketNumber' and @type='text' and @placeholder='Ex. 001234567890']").send_keys("1234567")
    #     self.driver.find_element(By.XPATH, "//adc-button[@type='submit']").click()
    