import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestThetrainline:
    
    def test_thetrainline_d56df06a(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-24T23").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-24T23").send_keys("Leeds")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='stations_to']/div[2]/li[6]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title3-25").click()
        self.driver.find_element(By.ID, "38196e4d-85f7-49a7-af6a-556fb3d4f82d").clear()
        self.driver.find_element(By.ID, "38196e4d-85f7-49a7-af6a-556fb3d4f82d").select("08")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[3]/fieldset[2]/div[5]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.inbound.title3-25").click()
        self.driver.find_element(By.ID, "ea0a8f5a-c636-4ae9-af37-bbf894ed5c48").clear()
        self.driver.find_element(By.ID, "ea0a8f5a-c636-4ae9-af37-bbf894ed5c48").select("23")
        self.driver.find_element(By.XPATH, "//button[@id='passenger-summary-btn']/div[3]/svg[1]").click()
        self.driver.find_element(By.ID, "9d2f2bef-f14e-43f8-b1a2-73509aa4dd1f").clear()
        self.driver.find_element(By.ID, "9d2f2bef-f14e-43f8-b1a2-73509aa4dd1f").select("2")
        self.driver.find_element(By.ID, "ddf22baf-c159-42bb-b741-fe593eb3a6e0").clear()
        self.driver.find_element(By.ID, "ddf22baf-c159-42bb-b741-fe593eb3a6e0").select("5-15")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[4]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'OK, got it')]").click()
    
    def test_thetrainline_daec5481(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-24T12").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-24T12").send_keys("edinburg")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "to.search_2023-03-24T12").clear()
        self.driver.find_element(By.ID, "to.search_2023-03-24T12").send_keys("manchester")
        self.driver.find_element(By.XPATH, "//ul[@id='stations_to']/div[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "return").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title4-2").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.inbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.inbound.title4-2").click()
        self.driver.find_element(By.ID, "4276d801-d9a2-48e1-9291-84948687f303").clear()
        self.driver.find_element(By.ID, "4276d801-d9a2-48e1-9291-84948687f303").select("17")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]/span[1]").click()
    
    def test_thetrainline_09660a8d(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/header[1]/button[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='overlay-currency-language']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='overlay-currency-language']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/select[1]").select("🇬🇧 English (UK)")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[2]/header[1]/button[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='overlay-currency-language']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='overlay-currency-language']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/select[1]").select("Euro (EUR/€)")
    
    def test_thetrainline_3110612f(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "Burger").click()
        self.driver.find_element(By.XPATH, "//div[@id='secondary-menu']/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Spain train tickets')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Renfe fare types')]").click()
    
    def test_thetrainline_35646414(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-25T10").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-25T10").send_keys("BRISTOL")
        self.driver.find_element(By.XPATH, "//ul[@id='stations_from']/div[1]/li[3]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "to.search_2023-03-25T10").clear()
        self.driver.find_element(By.ID, "to.search_2023-03-25T10").send_keys("LONDON")
        self.driver.find_element(By.XPATH, "//ul[@id='stations_to']/div[1]/li[3]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title4-8").click()
        self.driver.find_element(By.ID, "e41761dd-8934-477a-82b5-9d4c6892910a").clear()
        self.driver.find_element(By.ID, "e41761dd-8934-477a-82b5-9d4c6892910a").select("14")
        self.driver.find_element(By.ID, "d570b8fc-4085-42d9-a4e7-46d98b017dd7").clear()
        self.driver.find_element(By.ID, "d570b8fc-4085-42d9-a4e7-46d98b017dd7").select("00")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]/span[1]/span[1]").click()
        self.driver.find_element(By.ID, "direction").clear()
        self.driver.find_element(By.ID, "direction").select("Forward facing")
        self.driver.find_element(By.ID, "position").clear()
        self.driver.find_element(By.ID, "position").select("Window")
        self.driver.find_element(By.XPATH, "//form[@id='seat-reservation-form']/div[1]/div[1]/div[1]/fieldset[1]/div[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/label[4]/div[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='seat-reservation-form']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]/span[1]/span[1]/span[1]").click()
    
    def test_thetrainline_44dcda68(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-17T06").click()
        self.driver.find_element(By.ID, "from.search_2023-03-17T06").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-17T06").send_keys("Edinburgh")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "to.search_2023-03-17T06").click()
        self.driver.find_element(By.ID, "to.search_2023-03-17T06").clear()
        self.driver.find_element(By.ID, "to.search_2023-03-17T06").send_keys("Glasgow")
        self.driver.find_element(By.XPATH, "//ul[@id='stations_to']/div[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[3]/fieldset[1]/div[2]/div[2]/div[1]/div[2]/div[1]/button[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title5-18").click()
        self.driver.find_element(By.ID, "0543526c-1ef7-4055-b4a1-55377d23d0db").clear()
        self.driver.find_element(By.ID, "0543526c-1ef7-4055-b4a1-55377d23d0db").select("15")
        self.driver.find_element(By.XPATH, "//button[@id='passenger-summary-btn']/div[3]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[4]/div[1]/div[1]/ul[1]/li[1]/div[1]/button[1]/span[2]").click()
        self.driver.find_element(By.ID, "railcardRow0").clear()
        self.driver.find_element(By.ID, "railcardRow0").select("Veterans Railcard")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[4]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
    
    def test_thetrainline_f122e4c9(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-16T19").click()
        self.driver.find_element(By.ID, "from.search_2023-03-16T19").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-16T19").send_keys("Manchester")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title4-8").click()
        self.driver.find_element(By.ID, "f4011582-59af-4a96-8e56-989d3fa59e33").clear()
        self.driver.find_element(By.ID, "f4011582-59af-4a96-8e56-989d3fa59e33").select("10")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
    
    def test_thetrainline_5b37d2e1(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-25T10").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-25T10").send_keys("PARIS")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "to.search_2023-03-25T10").clear()
        self.driver.find_element(By.ID, "to.search_2023-03-25T10").send_keys("MILAN")
        self.driver.find_element(By.XPATH, "//ul[@id='stations_to']/div[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[3]/fieldset[1]/div[2]/div[2]/div[1]/div[1]/div[1]/button[1]/svg[1]/rect[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title3-26").click()
        self.driver.find_element(By.XPATH, "//button[@id='passenger-summary-btn']/div[1]/div[3]/svg[1]/polyline[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[4]/div[1]/div[4]/div[1]/div[2]/button[1]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "58c4c283-ee3e-4922-9179-1cd7d0cc5cea").clear()
        self.driver.find_element(By.ID, "58c4c283-ee3e-4922-9179-1cd7d0cc5cea").select("16")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[4]/div[1]/div[4]/button[1]").click()
        self.driver.find_element(By.ID, "e438c2ea-2f02-4853-918f-284d88784002").clear()
        self.driver.find_element(By.ID, "e438c2ea-2f02-4853-918f-284d88784002").select("12")
        self.driver.find_element(By.ID, "98ee47a2-ed52-42d9-b94d-3c9ec1784da0").clear()
        self.driver.find_element(By.ID, "98ee47a2-ed52-42d9-b94d-3c9ec1784da0").select("00")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[1]/div[1]/button[1]/h3[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/label[2]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/label[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/section[1]/article[14]/button[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/section[1]/article[13]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[5]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[2]/button[1]/div[1]").click()
    
    def test_thetrainline_b48c9974(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-24T12").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-24T12").send_keys("london")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "to.search_2023-03-24T12").clear()
        self.driver.find_element(By.ID, "to.search_2023-03-24T12").send_keys("sheffield")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title3-29").click()
        self.driver.find_element(By.ID, "4e8bcfe7-a4ae-434b-866d-48ee14f856b9").clear()
        self.driver.find_element(By.ID, "4e8bcfe7-a4ae-434b-866d-48ee14f856b9").select("Leaving at")
        self.driver.find_element(By.ID, "da39d4dd-e7b9-426d-a32b-c2c104a0ad50").clear()
        self.driver.find_element(By.ID, "da39d4dd-e7b9-426d-a32b-c2c104a0ad50").select("10")
        self.driver.find_element(By.ID, "fb1e4751-824a-4c92-9a16-3c656497ea4d").clear()
        self.driver.find_element(By.ID, "fb1e4751-824a-4c92-9a16-3c656497ea4d").select("45")
        self.driver.find_element(By.XPATH, "//button[@id='passenger-summary-btn']/div[3]/svg[1]").click()
        self.driver.find_element(By.ID, "72153158-1b9f-470a-b934-19f280897e0f").clear()
        self.driver.find_element(By.ID, "72153158-1b9f-470a-b934-19f280897e0f").select("2")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[4]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'OK, got it')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]").click()
    
    def test_thetrainline_c5a0a291(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "Burger").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Railcards')]").click()
        self.driver.find_element(By.ID, "age").clear()
        self.driver.find_element(By.ID, "age").select("18-25")
        self.driver.find_element(By.ID, "travellers").clear()
        self.driver.find_element(By.ID, "travellers").select("Couple")
        self.driver.find_element(By.ID, "londonAndSouthEast").clear()
        self.driver.find_element(By.ID, "londonAndSouthEast").select("Yes")
    
    def test_thetrainline_cd4df5fa(self):
        # self.driver.get("https://thetrainline.com")
        self.driver.find_element(By.ID, "from.search_2023-03-25T10").clear()
        self.driver.find_element(By.ID, "from.search_2023-03-25T10").send_keys("BERLIN")
        self.driver.find_element(By.XPATH, "//li[@id='selected_option']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "to.search_2023-03-25T10").clear()
        self.driver.find_element(By.ID, "to.search_2023-03-25T10").send_keys("ZURICH")
        self.driver.find_element(By.XPATH, "//ul[@id='stations_to']/div[1]/li[2]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title").click()
        self.driver.find_element(By.ID, "page.journeySearchForm.outbound.title3-31").click()
        self.driver.find_element(By.ID, "89f758b1-63a0-4343-b71f-1d41c61176dd").clear()
        self.driver.find_element(By.ID, "89f758b1-63a0-4343-b71f-1d41c61176dd").select("08")
        self.driver.find_element(By.ID, "cff0c433-8a72-477a-9790-dbfc73204fe3").clear()
        self.driver.find_element(By.ID, "cff0c433-8a72-477a-9790-dbfc73204fe3").select("00")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/main[1]/div[1]/div[4]/div[1]/div[1]/div[1]/section[1]/form[1]/div[5]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[5]/div[1]/div[3]/div[1]/label[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/span[1]/div[1]/div[1]/button[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/label[3]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/label[3]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/label[3]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train']/div[1]/div[2]/div[1]/div[2]/button[1]/div[1]/span[1]/span[1]").click()
    