import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestCarmax:
    
    def test_carmax_923fd4e0(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-inventory-search").clear()
        self.driver.find_element(By.ID, "header-inventory-search").send_keys("Truck")
        self.driver.find_element(By.XPATH, "//ul[@id='suggestions']/li[1]/a[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").clear()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").send_keys("fremont")
        self.driver.find_element(By.XPATH, "//form[@id='store-chooser-keyword-search-form']/button[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='store-chooser-modal-body']/ul[1]/li[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='EngineType']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='YearFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[7]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[14]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='MileageFilter']/button[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").send_keys("80000")
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[8]/button[1]").click()
    
    def test_carmax_b59b1997(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Search Cars')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").clear()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").send_keys("49512")
        self.driver.find_element(By.XPATH, "//form[@id='store-chooser-keyword-search-form']/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='store-chooser-modal-body']/ul[1]/li[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Make']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[26]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[13]/span[1]/span[1]").click()
    
    def test_carmax_ba5c335f(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-inventory-search").clear()
        self.driver.find_element(By.ID, "header-inventory-search").send_keys("Chevrolet Silverado")
        self.driver.find_element(By.XPATH, "//button[@id='header-search-button']/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='PriceFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[14]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ExteriorColor']/button[1]").click()
        self.driver.find_element(By.XPATH, "//li[@role='presentation']").click()
    
    def test_carmax_d496bbbe(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Search Jobs')]").click()
        self.driver.find_element(By.XPATH, "//font[contains(.,'SEARCH JOBS')]").click()
        self.driver.find_element(By.ID, "JobCategoryAccordion").click()
        self.driver.find_element(By.XPATH, "//div[@id='JobCategoryBody']/div[1]/div[2]/ul[1]/li[2]/label[1]/span[1]").click()
        self.driver.find_element(By.ID, "CityAccordion").click()
        self.driver.find_element(By.XPATH, "//div[@id='CityBody']/div[1]/div[2]/ul[1]/li[3]/label[1]/span[1]").click()
        self.driver.find_element(By.ID, "JobTypeAccordion").click()
        self.driver.find_element(By.XPATH, "//div[@id='JobTypeBody']/div[1]/div[2]/ul[1]/li[1]/label[1]/span[2]").click()
        self.driver.find_element(By.ID, "sortselect").clear()
        self.driver.find_element(By.ID, "sortselect").select("Most recent")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Apply Now')]").click()
    
    def test_carmax_f485ddf4(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-inventory-search").clear()
        self.driver.find_element(By.ID, "header-inventory-search").send_keys("tesla")
        self.driver.find_element(By.XPATH, "//ul[@id='suggestions']/li[2]/a[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='YearFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/button[1]").click()
    
    def test_carmax_610fe8c0(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-inventory-search").clear()
        self.driver.find_element(By.ID, "header-inventory-search").send_keys("Toyota Corolla")
        self.driver.find_element(By.XPATH, "//ul[@id='suggestions']/li[1]/a[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='YearFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='YearFilter']/button[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[6]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ExteriorColor']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[5]").click()
    
    def test_carmax_706d0ccd(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-mobile-drawer-focus-start").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-by-type-carousel']/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/a[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Make']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Model']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[4]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.ID, "switch-Compare").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[1]/article[1]/div[1]/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[2]/article[1]/div[1]/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='results-header-wrapper']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='compare-root']/div[2]/div[4]/div[2]/div[1]/div[2]/div[7]/div[1]/div[1]").click()
    
    def test_carmax_76294719(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a store')]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='list']/li[3]/a[1]/div[1]/div[1]/p[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='list']/li[8]/button[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[@id='storeInfo-7196']/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'shop local cars')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[1]/article[1]/div[1]/div[1]/div[1]/button[1]/img[1]").click()
    
    def test_carmax_8710addc(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//button[@id='header-helpful-links-button']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Service & Repairs')]").click()
        self.driver.find_element(By.XPATH, "//section[@id='service-options']/div[2]/div[1]/div[1]/div[1]/button[1]/span[3]").click()
    
    def test_carmax_8ab1c90f(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-mobile-drawer-focus-start").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-by-type-carousel']/div[1]/div[1]/div[1]/div[1]/div[1]/div[8]/div[1]/a[1]/img[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Sort']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='EngineType']/button[1]").click()
        self.driver.find_element(By.XPATH, "//li[@role='presentation']").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='YearFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[6]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ExteriorColor']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Transmission']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@role='menuitem' and @type='button']").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "switch-Compare").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[1]/article[1]/div[1]/div[1]/button[1]/svg[1]/path[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[2]/article[1]/div[1]/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='results-header-wrapper']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='compare-root']/div[2]/div[3]/button[1]").click()
    
    def test_carmax_b7082615(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-my-store-button-zipCode").click()
        self.driver.find_element(By.ID, "header-store-search-form-input").click()
        self.driver.find_element(By.ID, "header-store-search-form-input").clear()
        self.driver.find_element(By.ID, "header-store-search-form-input").send_keys("07055")
        self.driver.find_element(By.XPATH, "//button[@id='header-store-search-button']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='store-chooser-modal-body']/ul[1]/li[2]/div[2]/button[1]").click()
    
    def test_carmax_cdd9ef05(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Sell/Trade')]").click()
        self.driver.find_element(By.ID, "select-wtb-selected-state").clear()
        self.driver.find_element(By.ID, "select-wtb-selected-state").select("New Jersey")
        self.driver.find_element(By.ID, "radio-wtb-makingPayments-Yes").click()
        self.driver.find_element(By.ID, "radio-wtb-multipleTitleOwners-No").click()
        self.driver.find_element(By.ID, "radio-wtb-titleOwnersCanCome-Yes").click()
        self.driver.find_element(By.XPATH, "//section[@id='what-to-bring']/div[1]/div[2]/div[2]/button[1]").click()
    
    def test_carmax_0790c8be(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//button[@id='header-helpful-links-button']/span[1]").click()
        self.driver.find_element(By.ID, "careers-link--desktop").click()
        self.driver.find_element(By.ID, "keywordSearch").clear()
        self.driver.find_element(By.ID, "keywordSearch").send_keys("Accounting")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Accounting & Finance')]").click()
        self.driver.find_element(By.ID, "StateAccordion").click()
        self.driver.find_element(By.XPATH, "//div[@id='StateBody']/div[1]/div[2]/ul[1]/li[1]/label[1]/span[2]").click()
        self.driver.find_element(By.ID, "CityAccordion").click()
        self.driver.find_element(By.XPATH, "//div[@id='CityBody']/div[1]/div[2]/ul[1]/li[1]/label[1]/span[2]").click()
    
    def test_carmax_10e17667(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Search Cars')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Sort']/button[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").click()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").clear()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").send_keys("07055")
        self.driver.find_element(By.XPATH, "//form[@id='store-chooser-keyword-search-form']/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='store-chooser-modal-body']/ul[1]/li[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Make']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[3]/span[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Series']/button[1]").click()
        self.driver.find_element(By.XPATH, "//li[@role='presentation']").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[4]").click()
    
    def test_carmax_e104a4ef(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Finance')]").click()
        self.driver.find_element(By.ID, "car-calculator-link").click()
        self.driver.find_element(By.ID, "text-field-vehicle-budget-textfield").click()
        self.driver.find_element(By.ID, "text-field-vehicle-budget-textfield").clear()
        self.driver.find_element(By.ID, "text-field-vehicle-budget-textfield").send_keys("10000")
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").click()
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").clear()
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").send_keys("500")
        self.driver.find_element(By.ID, "state-location-select").clear()
        self.driver.find_element(By.ID, "state-location-select").select("New Jersey")
        self.driver.find_element(By.ID, "credit-rating-select").clear()
        self.driver.find_element(By.ID, "credit-rating-select").select("Challenged (< 580 FICO® Score)")
        self.driver.find_element(By.ID, "term-length-select").clear()
        self.driver.find_element(By.ID, "term-length-select").select("72 months")
    
    def test_carmax_957878ba(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//button[@id='header-helpful-links-button']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Service & Repairs')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'find a shop near you')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='header']/nav[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/li[1]").clear()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/li[1]").send_keys("49107")
        self.driver.find_element(By.XPATH, "//input[@name='Autocomplete Zip Code Selector' and @value='' and @type='text' and @placeholder='ZIP Code']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='Autocomplete Zip Code Selector' and @value='' and @type='text' and @placeholder='ZIP Code']").send_keys("49107")
        self.driver.find_element(By.XPATH, "//li[@id='react-autowhatever-1--item-0']/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//button[contains(.,'Request Appointment')]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'7')]").click()
    
    def test_carmax_9e3d2edb(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-my-store-button-text").click()
        self.driver.find_element(By.ID, "header-store-search-form-input").clear()
        self.driver.find_element(By.ID, "header-store-search-form-input").send_keys("08817")
        self.driver.find_element(By.XPATH, "//button[@id='header-store-search-button']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='store-chooser-modal-body']/ul[1]/li[2]/div[2]/button[1]").click()
        self.driver.find_element(By.ID, "header-mobile-drawer-focus-start").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'SHOP ALL CARS')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Sort']/button[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Make']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[6]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='PriceFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[11]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[10]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[1]/article[1]/div[1]/div[2]").click()
    
    def test_carmax_8bfeeb54(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Search Cars')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").click()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").clear()
        self.driver.find_element(By.ID, "store-chooser-keyword-input").send_keys("07470")
        self.driver.find_element(By.XPATH, "//div[@id='store-chooser-modal-body']/ul[1]/li[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Distance']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[4]/button[1]").click()
        self.driver.find_element(By.ID, "switch-Pk738UI-").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Make']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[13]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Model']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='YearFilter']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[7]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[7]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Features']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[5]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ExteriorColor']/button[1]").click()
        self.driver.find_element(By.XPATH, "//li[@role='presentation']").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Sort']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter-panel']/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/label[1]").click()
    
    def test_carmax_29fde741(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Finance')]").click()
        self.driver.find_element(By.ID, "car-calculator-link").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[1]/button[2]").click()
        self.driver.find_element(By.ID, "text-field-monthly-payment-textfield").clear()
        self.driver.find_element(By.ID, "text-field-monthly-payment-textfield").send_keys("250")
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").clear()
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").send_keys("3000")
        self.driver.find_element(By.ID, "state-location-select").clear()
        self.driver.find_element(By.ID, "state-location-select").select("Tennessee")
        self.driver.find_element(By.ID, "credit-rating-select").clear()
        self.driver.find_element(By.ID, "credit-rating-select").select("Challenged (< 580 FICO® Score)")
    
    def test_carmax_5c91b907(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find a store')]").click()
        self.driver.find_element(By.ID, "searchFormInput").clear()
        self.driver.find_element(By.ID, "searchFormInput").send_keys("california")
        self.driver.find_element(By.XPATH, "//button[@id='submit']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[2]/div[1]/div[1]/div[1]/div[9]/div[1]").click()
        self.driver.find_element(By.ID, "store-details-7159").click()
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[1]/div[1]/article[1]/div[1]/section[1]/button[1]").click()
    
    def test_carmax_5d69e640(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Finance')]").click()
        self.driver.find_element(By.ID, "car-calculator-link").click()
        self.driver.find_element(By.ID, "text-field-vehicle-budget-textfield").clear()
        self.driver.find_element(By.ID, "text-field-vehicle-budget-textfield").send_keys("15000")
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").clear()
        self.driver.find_element(By.ID, "text-field-down-payment-text-field").send_keys("5000")
        self.driver.find_element(By.ID, "state-location-select").clear()
        self.driver.find_element(By.ID, "state-location-select").select("Michigan")
        self.driver.find_element(By.ID, "credit-rating-select").clear()
        self.driver.find_element(By.ID, "credit-rating-select").select("Fair (580-669 FICO® Score)")
        self.driver.find_element(By.ID, "term-length-select").clear()
        self.driver.find_element(By.ID, "term-length-select").select("48 months")
        self.driver.find_element(By.ID, "calc-button-shop-cars").click()
        self.driver.find_element(By.XPATH, "//div[@id='cars-listing']/div[3]/div[1]/article[1]/div[1]/div[1]/div[1]/button[1]/img[1]").click()
    
    def test_carmax_8e721b00(self):
        # self.driver.get("https://carmax.com")
        self.driver.find_element(By.ID, "header-inventory-search").clear()
        self.driver.find_element(By.ID, "header-inventory-search").send_keys("jaguar xf")
        self.driver.find_element(By.XPATH, "//ul[@id='suggestions']/li[1]/a[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Availability']/button[1]").click()
        self.driver.find_element(By.ID, "nofinement-search-bar-input").clear()
        self.driver.find_element(By.ID, "nofinement-search-bar-input").send_keys("black")
        self.driver.find_element(By.XPATH, "//span[@role='button']").click()
        self.driver.find_element(By.XPATH, "//aside[@id='sidebar']/div[1]/div[1]/div[4]/button[1]").click()
        self.driver.find_element(By.ID, "text-field-save-search-name").clear()
        self.driver.find_element(By.ID, "text-field-save-search-name").send_keys("Jaguar")
        self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
        self.driver.find_element(By.ID, "radio-desN3TDg").click()
        self.driver.find_element(By.XPATH, "//button[contains(.,'Continue')]").click()
    