import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestJetblue:
    
    def test_jetblue_c4380ce9(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").send_keys("SALT LAKE CITY")
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").send_keys("PARIS")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-4-option-item-0']/span[1]/span[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//g[@id='chevron']/polygon[1]").click()
        self.driver.find_element(By.XPATH, "//g[@id='chevron']/polygon[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[2]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[1]/jb-calendar-day[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[2]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[2]/jb-calendar-day[4]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[3]/div[1]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='auto-flight-quickest-or-lowest-0']/div[1]/div[1]/div[3]/div[1]/jb-fare-class-card[1]/div[1]/div[2]/jb-offer-block[1]/button[1]/jb-offer-block-value[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-itinerary-panel[@id='auto-flight-card0']/jb-expandable-container[1]/div[1]/jb-expandable-section[1]/div[1]/jb-fare-type-tiles-panel[1]/div[1]/div[2]/jb-fare-type-tile[1]/div[1]/div[2]/div[1]/span[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='auto-flight-quickest-or-lowest-0']/div[1]/div[1]/div[3]/div[1]/jb-fare-class-card[1]/div[1]/div[2]/jb-offer-block[1]/button[1]/jb-offer-block-value[1]/div[1]/div[1]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-itinerary-panel[@id='auto-flight-card0']/jb-expandable-container[1]/div[1]/jb-expandable-section[1]/div[1]/jb-fare-type-tiles-panel[1]/div[1]/div[2]/jb-fare-type-tile[1]/div[1]/div[2]/div[1]/span[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='add-to-cart']/span[1]").click()
    
    def test_jetblue_7f90189b(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.ID, "jb-autocomplete-9-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-9-search").send_keys("MIAMI")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-9-option-item-2']/span[1]/span[1]/div[1]/strong[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-10-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-10-search").send_keys("NAIROBI")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-10-option-item-0']/span[1]/span[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//g[@id='chevron']/polygon[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-16']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[2]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[1]/jb-calendar-day[4]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-16']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[2]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[2]/jb-calendar-day[2]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-16']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[1]/div[1]/dot-traveler-selector[1]/div[1]/jb-form-field-container[1]/jb-select-button[1]/div[1]/jb-select-simple-button[1]/button[1]/jb-expandable-indicator[1]/div[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-16']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[1]/div[1]/dot-traveler-selector[1]/div[1]/jb-form-field-container[1]/jb-select-button[1]/jb-flyout-inner[1]/div[1]/div[1]/dot-traveler-group[1]/ul[1]/li[1]/jb-incrementer[1]/div[1]/div[2]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-16']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[3]/div[1]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Sort & Filter')]").click()
        self.driver.find_element(By.XPATH, "//jb-select[@id='auto-sort-options']/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-select-option[@id='jb-select-0-option-1']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Apply')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='auto-flight-quickest-or-lowest-0']/div[1]/div[1]/div[3]/div[1]/jb-fare-class-card[1]/div[1]/div[1]/jb-offer-block[1]/button[1]/jb-offer-block-value[1]/div[1]/div[1]/div[1]/span[1]/span[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//jb-itinerary-panel[@id='auto-flight-card0']/jb-expandable-container[1]/div[1]/jb-expandable-section[1]/div[1]/jb-fare-type-tiles-panel[1]/div[1]/div[1]/jb-fare-type-tile[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='auto-flight-quickest-or-lowest-0']/div[1]/div[1]/div[3]/div[1]/jb-fare-class-card[1]/div[1]/div[1]/jb-offer-block[1]/button[1]/jb-offer-block-value[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-itinerary-panel[@id='auto-flight-card0']/jb-expandable-container[1]/div[1]/jb-expandable-section[1]/div[1]/jb-fare-type-tiles-panel[1]/div[1]/div[1]/jb-fare-type-tile[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='add-to-cart']/span[1]").click()
    
    def test_jetblue_f2b311ad(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").send_keys("New York")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-3-option-item-2']/span[1]/span[1]/div[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").send_keys("Toronto")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-4-option-item-0']/span[1]/span[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[1]/div[1]/jb-select[1]/div[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-select-option[@id='jb-select-1-option-1']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "jb-date-picker-input-id-2").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-calendar[1]/div[1]/div[1]/div[1]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[5]/jb-calendar-day[7]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[3]/div[1]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Continue to flight results')]").click()
        self.driver.find_element(By.ID, "sort-filter-link").click()
        self.driver.find_element(By.XPATH, "//jb-select[@id='auto-sort-options']/div[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-select-option[@id='jb-select-1-option-1']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Apply')]").click()
        self.driver.find_element(By.XPATH, "//span[@role='button']").click()
    
    def test_jetblue_81b6bba7(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//jb-header-desktop[@id='jb-header-theme']/div[1]/div[1]/div[1]/jb-subnav-desktop[1]/nav[1]/ul[1]/li[1]/a[1]/jb-expandable-indicator[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-book-subnav-template[@id='subnav-wrapper_o3gj0loal-0']/div[1]/div[1]/div[2]/ul[1]/li[3]/jb-icon-link[1]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-5-search").click()
        self.driver.find_element(By.ID, "jb-autocomplete-5-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-5-search").send_keys("Los Angeles")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-5-option-item-0']/span[1]/span[1]/div[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-6-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-6-search").send_keys("Miami")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-6-option-item-0']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[@id='exploreFlightsButton']/span[1]").click()
        self.driver.find_element(By.XPATH, "//td[@id='04-12-2023']/div[4]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//button[@id='see-flights-btn-bff']/span[1]").click()
    
    def test_jetblue_85706225(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//jb-header-desktop[@id='jb-header-theme']/div[1]/div[1]/div[1]/jb-subnav-desktop[1]/nav[1]/ul[1]/li[4]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-travel-info-subnav-template[@id='subnav-wrapper_bfnlsnwbg-3']/div[1]/div[2]/div[4]/jb-icon-link[1]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-23-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-23-search").send_keys("Los Angeles")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-23-option-item-0']/span[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-24-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-24-search").send_keys("Boston")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-24-option-item-0']/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-38']/div[1]/div[1]/form[1]/div[1]/div[2]/jb-select[1]/div[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-select-option[@id='jb-select-12-option-2']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-38']/div[1]/div[1]/form[1]/button[1]/span[1]/span[1]").click()
    
    def test_jetblue_5c52af02(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").send_keys("New York")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-3-option-item-2']/span[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").send_keys("Aruba")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-4-option-item-0']/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[2]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[1]/jb-calendar-day[1]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[2]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[1]/jb-calendar-day[5]/button[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[1]/div[2]/jb-checkbox[1]/label[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[3]/div[1]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.ID, "sort-filter-link").click()
        self.driver.find_element(By.XPATH, "//button[@type='button' and @title='Default']").click()
        self.driver.find_element(By.XPATH, "//jb-select-option[@id='jb-select-1-option-1']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Apply')]").click()
    
    def test_jetblue_18a104dc(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='content']/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]").click()
    
    def test_jetblue_1ee63f83(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//button[@id='jb-tab-id-20']/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-20']/div[1]/jb-renderer-template[1]/dot-booker-hotel-points[1]/jb-static-booker-pod[1]/div[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='google-city-search']/div[1]/div[1]/div[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='google-city-search']/div[1]/div[1]/div[1]").send_keys("TEXAS CITY")
        self.driver.find_element(By.ID, "react-select-3-option-0").click()
        self.driver.find_element(By.XPATH, "//input[@name='' and @value='Sun, Mar 26 – Sun, Apr 2' and @type='text' and @placeholder='Select dates']").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[4]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[4]/div[7]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[5]/div[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='details-room-composition']/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//li[@id='bui264val-6']/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hotel_results_search_button']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ba6402-41a-0e11-edf1-d517027da63']/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_hotel_rating']/div[2]/label[5]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_hotel_amenities']/div[2]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_hotel_amenities']/div[2]/label[3]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_hotel_amenities']/div[2]/label[9]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@value='RECOMMENDED']").click()
        self.driver.find_element(By.XPATH, "//li[@id='bui8val-1']/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='jtp_hotel_search_results']/div[2]/a[1]/div[1]/div[2]/div[1]/div[1]/h2[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='order-summary-reserve-button']/div[1]").click()
    
    def test_jetblue_3c49d9c8(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Press Room')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'View all releases')]").click()
        self.driver.find_element(By.ID, "newsYear").clear()
        self.driver.find_element(By.ID, "newsYear").select("2020")
        self.driver.find_element(By.ID, "newsCat").clear()
        self.driver.find_element(By.ID, "newsCat").select("Press Releases")
    
    def test_jetblue_c73b1674(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-3-search").send_keys("new york")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-3-option-item-3']/span[1]/span[1]/div[1]/strong[1]").click()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").clear()
        self.driver.find_element(By.ID, "jb-autocomplete-4-search").send_keys("miami")
        self.driver.find_element(By.XPATH, "//li[@id='jb-autocomplete-4-option-item-2']/span[1]/span[1]/div[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[1]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[5]/jb-calendar-day[2]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.ID, "jb-date-picker-input-id-3").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[1]/dot-date-range-picker[1]/jb-date-picker[1]/jb-flyout-inner[1]/div[1]/jb-range-calendar[1]/div[1]/div[1]/div[1]/div[2]/div[8]/jb-calendar-month[1]/jb-calendar-week[5]/jb-calendar-day[6]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-0']/div[1]/jb-renderer-template[1]/dot-booker-air[1]/div[1]/dot-booker-air-v2[1]/form[1]/div[1]/div[2]/div[3]/div[1]/button[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/jb-booker-air-warning-dialog[1]/jb-dialog[1]/div[1]/div[2]/div[2]/jb-dialog-actions[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Sort & Filter')]").click()
        self.driver.find_element(By.XPATH, "//jb-button-close[@id='jb-button-close-0']/button[1]/jb-icon[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app-container-div']/jb-fares[1]/div[3]/div[1]/div[1]/div[1]/div[1]/jb-flight-details[1]/div[2]/div[1]/div[3]/div[2]/div[1]/jb-alter-flight-result-panel[1]/jb-segmented-control[1]/fieldset[1]/div[1]/jb-segment[2]/label[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Sort & Filter')]").click()
        self.driver.find_element(By.XPATH, "//jb-select[@id='auto-sort-options']/div[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//jb-select-option[@id='jb-select-1-option-1']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Apply')]").click()
    
    def test_jetblue_b7003092(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search-wrapper']/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/input[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search-wrapper']/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='search-wrapper']/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/input[1]").send_keys("New York")
        self.driver.find_element(By.XPATH, "//div[@id='search-wrapper']/div[1]/form[1]/div[1]/div[1]/div[2]/div[2]/div[1]/input[1]").click()
    
    def test_jetblue_bdc1f69a(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Check In')]").click()
        self.driver.find_element(By.ID, "firstName").clear()
        self.driver.find_element(By.ID, "firstName").send_keys("John")
        self.driver.find_element(By.ID, "lastName").clear()
        self.driver.find_element(By.ID, "lastName").send_keys("Smith")
        self.driver.find_element(By.ID, "choose").clear()
        self.driver.find_element(By.ID, "choose").select("Ticket Number")
        self.driver.find_element(By.ID, "ticketNumber").clear()
        self.driver.find_element(By.ID, "ticketNumber").send_keys("123456780")
        self.driver.find_element(By.XPATH, "//span[@id='left_buttons']/button[1]").click()
    
    def test_jetblue_c5d1ecbe(self):
        # self.driver.get("https://www.jetblue.com/")
        self.driver.find_element(By.XPATH, "//button[@id='jb-tab-id-10']/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//jb-tab-panel[@id='jb-tabpanel-id-10']/div[1]/jb-renderer-template[1]/dot-booker-hotel-points[1]/jb-static-booker-pod[1]/div[1]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "mat-input-6").clear()
        self.driver.find_element(By.ID, "mat-input-6").send_keys("ATLANTA")
        self.driver.find_element(By.XPATH, "//mat-option[@id='mat-option-26']/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='mat-select-value-3']/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//mat-option[@id='mat-option-21']/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='jtp-booker-cruise-submit']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c-panel-saildate']/vtemplate[5]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c-panel-nights']/vtemplate[1]/label[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c-panel-startport']/vtemplate[2]/label[1]").click()
        self.driver.find_element(By.XPATH, "//article[@id='cruise-result-b0f96057-daa7-4df4-a2c0-8426dd0b06b5']/div[8]/label[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Select package')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='amazearea_14341639']/ul[1]/li[5]/span[2]").click()
    