import time

import pytest
from selenium.webdriver.common.by import By

from browser_helper import calculate_dates_slash_format


@pytest.mark.usefixtures("setup_class")
class TestDelta:
    
    # def test_delta_0572899e(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headPrimary3").click()
    #     self.driver.find_element(By.ID, "searchOption-val").click()
    #     self.driver.find_element(By.ID, "ui-list-searchOption0").click()
    #     self.driver.find_element(By.ID, "confirmationNo").clear()
    #     self.driver.find_element(By.ID, "confirmationNo").send_keys("SFTBAO")
    #     self.driver.find_element(By.ID, "firstName").clear()
    #     self.driver.find_element(By.ID, "firstName").send_keys("Joe")
    #     self.driver.find_element(By.ID, "lastName").clear()
    #     self.driver.find_element(By.ID, "lastName").send_keys("Lukeman")
    #     self.driver.find_element(By.ID, "btn-mytrip-submit").click()
    #
    # def test_delta_1b4859f4(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headPrimary4").click()
    #     self.driver.find_element(By.ID, "input_departureDate_1").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'25')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@value='done' and @type='button']").click()
    #     self.driver.find_element(By.ID, "departcitylink").click()
    #     self.driver.find_element(By.ID, "search_input").clear()
    #     self.driver.find_element(By.ID, "search_input").send_keys("New York")
    #     self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "arrivalcitylink").click()
    #     self.driver.find_element(By.ID, "search_input").clear()
    #     self.driver.find_element(By.ID, "search_input").send_keys("Columbus")
    #     self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]").click()
    #     self.driver.find_element(By.ID, "btn-flight-sts-submit").click()
    
    def test_delta_295380ed(self):
        # self.driver.get("https://www.delta.com")
        time.sleep(30)
        self.driver.find_element(By.XPATH, "//a[@id='fromAirportName']/span[1]").click()
        self.driver.find_element(By.ID, "search_input").clear()
        self.driver.find_element(By.ID, "search_input").send_keys("LGA")
        self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//a[@id='toAirportName']/span[1]").click()
        self.driver.find_element(By.ID, "search_input").clear()
        self.driver.find_element(By.ID, "search_input").send_keys("PHL")
        self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
        self.driver.find_element(By.ID, "selectTripType-val").click()
        self.driver.find_element(By.ID, "ui-list-selectTripType1").click()

        # Somehow can't use ID "departureDate" since it will cause selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted:
        self.driver.find_element(By.ID, "calDepartLabelCont").click()
        flight_date, _ = calculate_dates_slash_format(21, 37)
        self.driver.find_element(By.XPATH, f"//a[contains(@data-date,'{flight_date}')]").click()

        self.driver.find_element(By.XPATH, "//button[@value='done' and @type='button']").click()
        self.driver.find_element(By.ID, "adv-search").click()
        self.driver.find_element(By.ID, "faresFor-val").click()
        self.driver.find_element(By.ID, "ui-list-faresFor3").click()
        self.driver.find_element(By.ID, "btnSubmit").click()
    
    # def test_delta_e1b0fb9c(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.XPATH, "//a[@id='fromAirportName']/span[1]").click()
    #     self.driver.find_element(By.ID, "search_input").clear()
    #     self.driver.find_element(By.ID, "search_input").send_keys("Seattle")
    #     self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='toAirportName']/span[1]").click()
    #     self.driver.find_element(By.ID, "search_input").clear()
    #     self.driver.find_element(By.ID, "search_input").send_keys("New York")
    #     self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "selectTripType-val").click()
    #     self.driver.find_element(By.ID, "ui-list-selectTripType1").click()
    #     self.driver.find_element(By.ID, "input_departureDate_1").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='booking']/form[1]/div[1]/div[1]/div[1]/div[1]/div[3]/date-selection-view[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/a[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'5')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@value='done' and @type='button']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='booking']/form[1]/div[1]/div[1]/div[1]/div[2]/ngc-search-options[1]/fieldset[1]/div[1]/div[2]/label[1]").click()
    #     self.driver.find_element(By.ID, "btn-book-submit").click()
    #
    # def test_delta_e4cf5835(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headSectab2").click()
    #     self.driver.find_element(By.ID, "secondary-static-link-5").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[2]/flight-deals[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/span[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//li[@id='ui-list-fromAirportCode17']/span[2]").click()
    #     self.driver.find_element(By.ID, "toAirportCode-val").click()
    #     self.driver.find_element(By.XPATH, "//li[@id='ui-list-toAirportCode1']/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='expandFliterButton']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='filterExpandedSection']/div[1]/div[4]/div[1]/span[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "ui-list-regionType1").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='filterExpandedSection']/div[1]/div[5]/button[1]").click()
    #
    # def test_delta_e783cb30(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headPrimary4").click()
    #     self.driver.find_element(By.XPATH, "//span[@id='calDepartLabelCont']/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'21')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@value='done' and @type='button']").click()
    #     self.driver.find_element(By.ID, "flightNo").click()
    #     self.driver.find_element(By.ID, "flightNo").clear()
    #     self.driver.find_element(By.ID, "flightNo").send_keys("DL145")
    #     self.driver.find_element(By.ID, "btn-flight-sts-submit").click()
    #
    # def test_delta_e92a2c89(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headSectab1").click()
    #     self.driver.find_element(By.ID, "secondary-static-link-14").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-locn-menu']/div[1]/div[1]/div[1]/button[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-locn-menu']/div[1]/div[1]/div[1]/button[1]").send_keys("Brooklyn")
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-locn-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.ID, "premium").click()
    #     self.driver.find_element(By.ID, "AUTO_TRANSMISSION").click()
    #     self.driver.find_element(By.XPATH, "//button[@name='textonly' and @type='button']").click()
    #
    # def test_delta_42f64db7(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.XPATH, "//a[@id='fromAirportName']/span[1]").clear()
    #     self.driver.find_element(By.XPATH, "//a[@id='fromAirportName']/span[1]").send_keys("Mumbai")
    #     self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='toAirportName']/span[1]").click()
    #     self.driver.find_element(By.ID, "search_input").clear()
    #     self.driver.find_element(By.ID, "search_input").send_keys("New York City")
    #     self.driver.find_element(By.XPATH, "//div[@id='airport-serach-panel']/div[1]/div[2]/div[1]/ul[1]/li[1]/a[1]/span[2]").click()
    #     self.driver.find_element(By.ID, "selectTripType-val").click()
    #     self.driver.find_element(By.ID, "ui-list-selectTripType1").click()
    #     self.driver.find_element(By.ID, "input_departureDate_1").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'21')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@value='done' and @type='button']").click()
    #     self.driver.find_element(By.ID, "btn-book-submit").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Refundable Economy Classic')]").click()
    #
    # def test_delta_93f3a9a1(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headPrimary4").click()
    #     self.driver.find_element(By.ID, "input_departureDate_1").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'18')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@value='done' and @type='button']").click()
    #     self.driver.find_element(By.ID, "flightNo").clear()
    #     self.driver.find_element(By.ID, "flightNo").send_keys("2819")
    #     self.driver.find_element(By.ID, "btn-flight-sts-submit").click()
    #
    # def test_delta_be5bae8d(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headSectab1").click()
    #     self.driver.find_element(By.ID, "secondary-static-link-15").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/div[1]/div[1]/div[1]/button[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/div[1]/div[1]/div[1]/button[1]").send_keys("New Delhi")
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.ID, "d2-btn").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[4]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.ID, "sort-filter-dropdown-sort").clear()
    #     self.driver.find_element(By.ID, "sort-filter-dropdown-sort").select("Price  low to high")
    #     self.driver.find_element(By.XPATH, "//div[@id='app-layer-base']/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/section[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/svg[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-layer-base']/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/section[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/svg[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app-layer-base']/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/section[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/svg[2]").click()
    #
    # def test_delta_cf89b0ae(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Shop Hotels')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/div[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.ID, "location-field-destination").clear()
    #     self.driver.find_element(By.ID, "location-field-destination").send_keys("Ohio")
    #     self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.ID, "d1-btn").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[2]/td[7]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_delta_f84075a2(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headPrimary3").click()
    #     self.driver.find_element(By.XPATH, "//span[@role='combobox']").click()
    #     self.driver.find_element(By.ID, "ui-list-searchOption2").click()
    #     self.driver.find_element(By.ID, "eTicketNo").clear()
    #     self.driver.find_element(By.ID, "eTicketNo").send_keys("3329456534543")
    #     self.driver.find_element(By.ID, "firstName").clear()
    #     self.driver.find_element(By.ID, "firstName").send_keys("John")
    #     self.driver.find_element(By.ID, "lastName").clear()
    #     self.driver.find_element(By.ID, "lastName").send_keys("Green")
    #     self.driver.find_element(By.ID, "btn-mytrip-submit").click()
    #
    # def test_delta_1860601a(self):
    #     # self.driver.get("https://www.delta.com")
    #     self.driver.find_element(By.ID, "headSectab1").click()
    #     self.driver.find_element(By.ID, "secondary-static-link-0").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Find Your Destination')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Explore Destinations & Travel Requirements')]").click()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-origin").click()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-origin").clear()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-origin").send_keys("New York")
    #     self.driver.find_element(By.XPATH, "//li[@id='smt-combobox-result-0']/div[1]/div[2]/p[1]").click()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-destination").click()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-destination").clear()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-destination").send_keys("Tokyo")
    #     self.driver.find_element(By.XPATH, "//li[@id='smt-combobox-result-0']/div[1]/div[2]/p[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-nationality").click()
    #     self.driver.find_element(By.XPATH, "//ul[@id='smt-combobox-results-nationality']/li[1]").click()
    #     self.driver.find_element(By.ID, "smt-combobox-labeledby-vaccinated").click()
    #     self.driver.find_element(By.ID, "smt-combobox-result-0").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='smt-covwidget-filters_search']/i[1]").click()
    