import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestTrip:
    
    def test_trip_f0b4af1a(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[5]/span[1]").click()
        self.driver.find_element(By.ID, "tnt-online-input").clear()
        self.driver.find_element(By.ID, "tnt-online-input").send_keys("phuket")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/i[1]").click()
        self.driver.find_element(By.ID, "ibuact-10650012671-filter-sort-364-4-0").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibuact-10650012671-filter-select-364-0-Activity Location-8-725']/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ottd-smart-platform']/section[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[3]/i[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='date_2023-04-15']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibuact-10650012671-filter-tab-364-Ticket2']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ottd-smart-platform']/section[1]/div[2]/div[3]/div[2]/div[1]/div[1]/div[2]/div[2]/ul[1]/li[1]/a[1]/div[5]").click()
        self.driver.find_element(By.XPATH, "//div[@id='poi.detail.overview']/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@title='Andamanda Phuket TicketPurchase']").click()
        self.driver.find_element(By.XPATH, "//section[@id='imageContainer']/section[1]/div[1]/div[1]/div[1]/div[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='date_2023-04-15']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SelectQuantity_plus_0']/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SelectQuantity_plus_0']/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SelectQuantity_plus_0']/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SelectQuantity_plus_1']/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='SelectQuantity_plus_1']/i[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='imageContainer']/section[1]/div[1]/div[1]/div[1]/div[3]/div[1]").click()
    
    def test_trip_8065f313(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[3]/span[1]").click()
        self.driver.find_element(By.ID, "sb_1679923538336_city_departure").click()
        self.driver.find_element(By.ID, "sb_1679923538336_city_departure").clear()
        self.driver.find_element(By.ID, "sb_1679923538336_city_departure").send_keys("Shanghai")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/ul[1]/li[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[2]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/button[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[2]/div[4]/div[1]/div[4]/div[3]/div[3]/button[1]").click()
    
    def test_trip_8997e608(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("New York")
        self.driver.find_element(By.XPATH, "//span[contains(.,'John F. Kennedy International Airport')]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("Bangkok")
        self.driver.find_element(By.XPATH, "/html/body[1]/div[3]/div[2]/ul[1]/li[1]/div[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Thu, Apr 20' and @type='text' and @placeholder='']").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[5]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/div[2]/div[1]/ul[3]/li[7]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[4]/div[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='J_resultList']/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/span[1]/span[1]/span[1]").click()
    
    def test_trip_9da529e3(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "hotels-destination").clear()
        self.driver.find_element(By.ID, "hotels-destination").send_keys("PUNE")
        self.driver.find_element(By.XPATH, "//div[@id='3838']/div[1]/div[1]/p[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[5]/li[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[5]/li[3]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[1]/div[1]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[2]/div[1]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[2]/div[1]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[3]/div[1]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[4]/div[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[4]/div[1]/select[1]").select("4")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[5]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/div[1]/div[2]/span[3]/em[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[5]/div[1]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[5]/div[1]/div[2]/ul[1]/li[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[7]/div[1]/div[2]/ul[1]/li[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='list_hotel_sort']/div[1]/div[1]/div[2]/span[1]").click()
    
    def test_trip_9ec92afd(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[3]/div[2]/ul[1]/li[6]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("hong kong")
        self.driver.find_element(By.XPATH, "//b[contains(.,'Hong Kong')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Taipei')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/div[1]/div[1]/ul[3]/li[5]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/div[1]/div[1]/ul[3]/li[6]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/span[1]").click()
    
    def test_trip_a4bfaf1d(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[4]/i[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='Airport, city, station, region, district...']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='Airport, city, station, region, district...']").send_keys("Los Angeles")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Thu, Apr 20' and @placeholder='Please provide a pick-up date']").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[5]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='10:00' and @placeholder='Please provide a drop-off time']").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[2]/div[2]/div[2]/div[2]/div[2]/div[29]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[2]/div[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/button[1]").click()
    
    def test_trip_039969ee(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[6]/span[1]").click()
        self.driver.find_element(By.ID, "from").clear()
        self.driver.find_element(By.ID, "from").send_keys("ahmedabad")
        self.driver.find_element(By.XPATH, "//b[contains(.,'Ahmedabad')]").click()
        self.driver.find_element(By.ID, "to").clear()
        self.driver.find_element(By.ID, "to").send_keys("dubai")
        self.driver.find_element(By.XPATH, "/html/body[1]/div[3]/div[2]/ul[1]/li[1]/div[2]/span[1]").click()
        self.driver.find_element(By.ID, "depart").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'5')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'6')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[2]/div[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[2]/div[5]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[2]/div[5]/div[1]/div[1]/div[1]/div[2]/div[4]/div[1]/div[3]/div[2]/span[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hotel-filter-group-id']/div[2]/div[1]/span[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hotel-filter-group-id']/div[2]/div[1]/span[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[2]/div[5]/div[1]/div[2]/div[2]/div[4]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__next']/div[2]/div[5]/div[1]/div[2]/div[2]/div[5]/div[1]/div[1]/div[3]/div[1]/div[2]/button[1]/span[1]").click()
    
    def test_trip_ccf3639f(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("London")
        self.driver.find_element(By.XPATH, "//b[contains(.,'London')]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("New York City")
        self.driver.find_element(By.XPATH, "//span[contains(.,'New York (All Airports)')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[2]/dl[1]/div[1]/dd[2]/dl[1]/dd[1]/dl[1]/dd[1]/div[1]/label[1]/span[1]/i[1]").click()
    
    def test_trip_ced2919a(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "hotels-destination").clear()
        self.driver.find_element(By.ID, "hotels-destination").send_keys("Tokyo")
        self.driver.find_element(By.XPATH, "//div[@id='228']/div[1]/div[1]/p[1]/strong[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[3]/li[6]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[2]/div[2]/ul[4]/li[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[4]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/ul[1]/li[5]/div[1]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//i[@type='checkbox']").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[9]/div[1]/div[2]/ul[1]/li[1]/i[1]").click()
    
    def test_trip_aa835369(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "header_action_nav_sales").click()
        self.driver.find_element(By.XPATH, "//div[@id='foxpage-app']/div[2]/div[1]/ul[1]/li[3]/div[1]").click()
    
    def test_trip_b40ebcd9(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "hotels-destination").clear()
        self.driver.find_element(By.ID, "hotels-destination").send_keys("Miami")
        self.driver.find_element(By.XPATH, "//div[@id='3798']/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[4]/li[6]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[5]/li[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[4]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[5]/div[1]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='showAll']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[17]/div[1]/div[2]/ul[1]/li[3]/i[1]").click()
    
    def test_trip_b51de4da(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "hotels-destination").clear()
        self.driver.find_element(By.ID, "hotels-destination").send_keys("las vegas")
        self.driver.find_element(By.XPATH, "//div[@id='26282']/div[1]/div[1]/p[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[3]/li[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[5]/li[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[2]/div[1]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[3]/div[1]/div[3]/div[1]/div[1]/span[3]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[5]/div[1]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//i[@type='checkbox']").click()
    
    def test_trip_b5b427a3(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "hotels-destination").clear()
        self.driver.find_element(By.ID, "hotels-destination").send_keys("New Yark")
        self.driver.find_element(By.XPATH, "//input[@value='Fri, Mar 10' and @type='text']").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[2]/ul[3]/li[4]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[1]/div[1]/ul[1]/li[5]/div[1]/p[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='list_hotel_sort']/div[1]/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//i[@type='checkbox']").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/ul[1]/li[2]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/ul[1]/li[4]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[3]/div[1]/ul[1]/li[6]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ibu_hotel_container']/section[1]/article[1]/div[1]/section[1]/div[2]/div[1]/div[10]/div[1]/div[2]/ul[1]/li[2]/i[1]").click()
    
    def test_trip_b5cabe51(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[3]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/ul[1]/li[3]/div[1]").click()
        self.driver.find_element(By.ID, "sb_1679500847714_city_departure").clear()
        self.driver.find_element(By.ID, "sb_1679500847714_city_departure").send_keys("BUSAN")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Seoul')]").click()
        self.driver.find_element(By.ID, "sb_1679500847714_date_depart").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[7]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[3]/div[2]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='train-card-list']/div[1]/div[22]/div[1]/table[1]/tbody[1]/tr[1]/td[5]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Book')]").click()
        self.driver.find_element(By.XPATH, "//input[@name='SurName' and @type='text' and @placeholder='e.g.SMITH']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='SurName' and @type='text' and @placeholder='e.g.SMITH']").send_keys("SMITH")
        self.driver.find_element(By.XPATH, "//input[@name='GivenName' and @type='text' and @placeholder='e.g.MARY ISABELLE']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='GivenName' and @type='text' and @placeholder='e.g.MARY ISABELLE']").send_keys("AGENT")
        self.driver.find_element(By.XPATH, "//div[@id='book-page']/div[4]/div[2]/div[1]/form[1]/div[3]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@name='year' and @value='1988']").click()
        self.driver.find_element(By.XPATH, "//div[@id='book-page']/div[4]/div[2]/div[1]/form[1]/div[3]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@name='month' and @value='01']").click()
        self.driver.find_element(By.XPATH, "//div[@id='book-page']/div[4]/div[2]/div[1]/form[1]/div[3]/div[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@name='day' and @value='01']").click()
        self.driver.find_element(By.XPATH, "//span[@name='nationality']").click()
        self.driver.find_element(By.XPATH, "//li[@name='nationality' and @value='AU']").click()
        self.driver.find_element(By.XPATH, "//input[@name='lastname' and @type='text' and @placeholder='e.g.SMITH']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='lastname' and @type='text' and @placeholder='e.g.SMITH']").send_keys("SMITH")
        self.driver.find_element(By.XPATH, "//input[@name='firstname' and @type='text' and @placeholder='e.g.MARY ISABELLE']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='firstname' and @type='text' and @placeholder='e.g.MARY ISABELLE']").send_keys("AGENT")
        self.driver.find_element(By.XPATH, "//div[@id='book-page']/div[4]/div[4]/div[1]/form[1]/div[2]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@value='+61']").click()
        self.driver.find_element(By.XPATH, "//input[@name='phone-number' and @type='text' and @placeholder='Phone number']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='phone-number' and @type='text' and @placeholder='Phone number']").send_keys("710101111")
        self.driver.find_element(By.XPATH, "//input[@name='email' and @type='text' and @placeholder='Email address']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='email' and @type='text' and @placeholder='Email address']").send_keys("AGENT.SMITH@MATRIX.COM")
        self.driver.find_element(By.ID, "go-payment-btn").click()
    
    def test_trip_2673300d(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("MUMBAI")
        self.driver.find_element(By.XPATH, "//span[contains(.,'Chhatrapati Shivaji Airport')]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='City or airport']").send_keys("TORONTO")
        self.driver.find_element(By.XPATH, "//b[contains(.,'Toronto')]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Fri, Mar 24' and @type='text' and @placeholder='']").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[3]/div[1]/div[1]/div[1]/div[1]/ul[5]/li[3]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/i[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/form[1]/div[1]/div[2]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[2]/dl[1]/div[1]/dd[2]/dl[1]/dd[1]/dl[1]/dd[2]/div[1]/label[1]/span[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[2]/dl[1]/div[1]/dd[1]/dl[1]/dd[2]/dl[1]/dd[1]/div[1]/label[1]/span[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[2]/dl[1]/div[1]/dd[7]/dl[1]/dt[1]/i[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main']/div[2]/div[7]/div[1]/div[2]/dl[1]/div[1]/dd[7]/dl[1]/dd[1]/dl[1]/dd[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='J_resultList']/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/span[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='J_resultList']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/span[1]/span[1]/span[1]").click()
    
    def test_trip_5b5d29e1(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.ID, "header_action_nav_ttd").click()
        self.driver.find_element(By.ID, "tnt-online-input").click()
        self.driver.find_element(By.XPATH, "//li[@id='ibuact-10650012750-destarea-dest-undefined-4-38']/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ticket_header_pic']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='ticket_header_pic']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").send_keys("Park")
        self.driver.find_element(By.XPATH, "//div[@id='ticket_header_pic']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]").click()
        self.driver.find_element(By.ID, "ibuact-10650012671-filter-sort-38-4-0").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Shanghai Wild Animal Park')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tabs-list']/div[1]/div[1]/span[3]").click()
    
    def test_trip_6bd5466e(self):
        # self.driver.get("https://us.trip.com/?locale=en-us")
        self.driver.find_element(By.XPATH, "//div[@id='main-search-box']/div[2]/div[1]/div[1]/ul[1]/li[5]/span[1]").click()
        self.driver.find_element(By.ID, "tnt-online-input").clear()
        self.driver.find_element(By.ID, "tnt-online-input").send_keys("seoul")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]").send_keys("amusement park")
        self.driver.find_element(By.XPATH, "//div[@id='searchBoxCon']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/i[1]").click()
        self.driver.find_element(By.ID, "ibuact-10650012671-filter-sort-234-2-0").click()
        self.driver.find_element(By.XPATH, "//div[@id='ottd-smart-platform']/section[1]/div[2]/div[3]/div[2]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='poi.detail.overview']/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/i[1]").click()
    