import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from browser_helper import calculate_dates_with_suffix


@pytest.mark.usefixtures("setup_class")
class TestExploretock:
    
    # def test_exploretock_e56ef366(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.ID, "delivery-city-search-type").clear()
    #     self.driver.find_element(By.ID, "delivery-city-search-type").select("Dine in")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH, US' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH, US' and @type='search' and @placeholder='Find a location']").send_keys("Buchanan, MI")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_107']/ul[1]/li[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='date-picker-reservations-city-search-date']/div[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[7]/button[1]").click()
    #     self.driver.find_element(By.ID, "reservations-city-search-time").clear()
    #     self.driver.find_element(By.ID, "reservations-city-search-time").select("8 00 PM")
    #     self.driver.find_element(By.ID, "reservations-city-search-guests").clear()
    #     self.driver.find_element(By.ID, "reservations-city-search-guests").select("2 guests")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[6]/a[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[4]/span[1]").click()
    #     self.driver.find_element(By.ID, "Spanish").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Submit')]").click()
    #
    # def test_exploretock_3e472e41(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[2]/button[1]/span[2]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[1]/a[1]/span[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='content_234']/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").send_keys("NEW DELHI")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_234']/ul[1]/li[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[3]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'22')]").click()
    #     self.driver.find_element(By.ID, "Size").clear()
    #     self.driver.find_element(By.ID, "Size").select("5 guests")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Update search')]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[4]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Outdoors')]").click()
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[5]/div[3]/div[1]/form[1]/div[3]").click()
    #     self.driver.find_element(By.XPATH, "//li[@id='availability-list-business-32200']/div[1]/ul[1]/li[1]/div[1]/div[2]/div[1]/div[3]/button[1]/span[1]/div[1]/span[1]").click()
    #
    # def test_exploretock_f4dcbd09(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='content_107']/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").send_keys("NEW YORK")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_107']/ul[1]/li[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "reservations-city-search-type").clear()
    #     self.driver.find_element(By.ID, "reservations-city-search-type").select("Events")
    #     self.driver.find_element(By.ID, "events-city-search-event-date").clear()
    #     self.driver.find_element(By.ID, "events-city-search-event-date").select("Next month")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[4]/a[1]/span[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[4]/span[1]").click()
    #     self.driver.find_element(By.ID, "Pizza").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Submit')]").click()
    #     self.driver.find_element(By.XPATH, "//li[@id='availability-list-business-31655']/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
    #
    # def test_exploretock_1efdcd9d(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[3]/button[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Find a business, cuisine, or experience']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Find a business, cuisine, or experience']").send_keys("Alinea")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Chicago, IL - Lincoln Park')]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/div[1]/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/div[1]/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[4]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[5]/button[4]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[3]/select[1]").select("5 00 PM")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]").click()
    #
    # def test_exploretock_61fa0552(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.ID, "reservations-city-search-type").clear()
    #     self.driver.find_element(By.ID, "reservations-city-search-type").select("Delivery")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH, US' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH, US' and @type='search' and @placeholder='Find a location']").send_keys("detroit")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_107']/ul[1]/li[1]/button[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='date-picker-delivery-city-search-date']/div[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[4]/td[7]/button[1]").click()
    #     self.driver.find_element(By.ID, "delivery-city-search-time").clear()
    #     self.driver.find_element(By.ID, "delivery-city-search-time").select("6 00 PM")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[5]/a[1]/span[1]/svg[1]").click()
    #
    # def test_exploretock_6e565708(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[2]/button[1]/span[2]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[3]/a[1]/span[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='content_147']/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").send_keys("CHICAGO")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_147']/ul[1]/li[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[3]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'30')]").click()
    #     self.driver.find_element(By.ID, "time").clear()
    #     self.driver.find_element(By.ID, "time").select("8 15 PM")
    #     self.driver.find_element(By.ID, "Size").clear()
    #     self.driver.find_element(By.ID, "Size").select("10 guests")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Update search')]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[4]/span[1]").click()
    #     self.driver.find_element(By.ID, "Pizza").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Submit')]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[5]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Dining package')]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_exploretock_d311891e(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[3]/button[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Find a business, cuisine, or experience']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Find a business, cuisine, or experience']").send_keys("Matthews winery")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Matthews Winery')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Indoor Reservation')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='experience-dialog-content']/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[7]/button[6]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='experience-dialog-content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/div[1]/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='experience-dialog-content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/div[1]/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='experience-dialog-content']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/div[1]/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='experience-dialog-content']/div[1]/div[2]/div[2]/div[1]/div[1]/button[21]").click()
    #
    # def test_exploretock_dadb0251(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[2]/button[1]/span[2]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='Root']/div[1]/div[2]/div[1]/header[1]/div[3]/div[1]/div[2]/div[1]/div[1]/ul[1]/li[2]/a[1]/span[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='content_147']/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").send_keys("NEW YORK")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_147']/ul[1]/li[1]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[3]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[contains(.,'20')]").click()
    #     self.driver.find_element(By.ID, "time").clear()
    #     self.driver.find_element(By.ID, "time").select("8 00 PM")
    #     self.driver.find_element(By.ID, "Size").clear()
    #     self.driver.find_element(By.ID, "Size").select("4 guests")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Update search')]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[4]/span[1]").click()
    #     self.driver.find_element(By.ID, "American").click()
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Submit')]").click()
    #
    # def test_exploretock_7bda9645(self):
    #     # self.driver.get("https://exploretock.com")
    #     self.driver.find_element(By.ID, "reservations-city-search-type").clear()
    #     self.driver.find_element(By.ID, "reservations-city-search-type").select("Pickup")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH, US' and @type='search' and @placeholder='Find a location']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='Columbus, OH, US' and @type='search' and @placeholder='Find a location']").send_keys("Boston")
    #     self.driver.find_element(By.XPATH, "//div[@id='content_107']/ul[1]/li[3]/button[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='date-picker-pickup-city-search-date']/div[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[7]/button[1]").click()
    #     self.driver.find_element(By.ID, "pickup-city-search-time").clear()
    #     self.driver.find_element(By.ID, "pickup-city-search-time").select("5 00 PM")
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[5]/a[1]/span[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[3]/span[1]/span[3]").click()
    #     self.driver.find_element(By.ID, "Size").clear()
    #     self.driver.find_element(By.ID, "Size").select("1 guest")
    #     self.driver.find_element(By.XPATH, "//span[contains(.,'Update search')]").click()
    
    def test_exploretock_a6372f23(self):
        # self.driver.get("https://exploretock.com")
        # time.sleep(30)
        # self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='content_107']/div[1]/div[1]/button[1]/span[1]/svg[1]").click()

        # self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").clear()
        # self.driver.find_element(By.XPATH, "//input[@value='' and @type='search' and @placeholder='Find a location']").send_keys("NAPA VALLEY")
        # self.driver.find_element(By.XPATH, "//div[@id='content_107']/ul[1]/li[1]/button[1]/span[1]/span[1]").click()
        # self.driver.find_element(By.ID, "reservations-city-search-type").clear()
        # self.driver.find_element(By.ID, "reservations-city-search-type").select("Wineries")
        # Logic changed
        reservation_type_dropdown = self.driver.find_element(By.ID, "reservations-city-search-type")
        reservation_type_select = Select(reservation_type_dropdown)
        reservation_type_select.select_by_value('wineries')

        # self.driver.find_element(By.ID, "city-search-location").click()
        # self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div/div[1]/div[1]/div/div/div[2]/div").click()
        self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div/div[1]/div[1]/div/div/div[2]/div/div/button").click()
        self.driver.find_element(By.XPATH, "//input[@type='search' and @placeholder='Find a location']").clear()
        self.driver.find_element(By.XPATH, "//input[@type='search' and @placeholder='Find a location']").send_keys("NAPA VALLEY")
        self.driver.find_element(By.XPATH, "//ul[@aria-label='Location search results']//span[text()='Napa Valley']").click()

        # self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]/span[1]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='date-picker-wineries-city-search-date']/div[3]/div[1]/div[1]/div[1]/div[1]/button[2]/span[1]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='date-picker-wineries-city-search-date']/div[3]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[7]/button[1]").click()
        # self.driver.find_element(By.ID, "wineries-city-search-time").clear()
        # self.driver.find_element(By.ID, "wineries-city-search-time").select("10 00 AM")
        # self.driver.find_element(By.ID, "wineries-city-search-guests").clear()
        # self.driver.find_element(By.ID, "wineries-city-search-guests").select("4 guests")
        # self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[1]/div[2]/div[1]/div[6]/a[1]/span[1]/svg[1]").click()
        # self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[4]/span[1]").click()
        # self.driver.find_element(By.ID, "Mediterranean").click()
        # self.driver.find_element(By.XPATH, "//span[contains(.,'Submit')]").click()

        self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div/div[1]/div[1]/div/div/div[3]/div/div").click()
        start_date_str, end_date_str = calculate_dates_with_suffix(7, 7)
        self.driver.find_element(By.XPATH, f"//button[@aria-label='{start_date_str}']").click()

        reservation_time_dropdown = self.driver.find_element(By.ID, "wineries-city-search-time")
        reservation_time_select = Select(reservation_time_dropdown)
        reservation_time_select.select_by_value('10:00')
        # BE CAREFUL! These IDs are depending on the previous selection of the reservation type!
        guest_size_dropdown = self.driver.find_element(By.ID, "wineries-city-search-guests")
        guest_zise_select = Select(guest_size_dropdown)
        guest_zise_select.select_by_value('4')
        self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div/div[1]/div[1]/div/div/div[6]/a").click()

        # self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div[1]/div[2]/button[5]/span[2]").click()
        # self.driver.find_element(By.ID, "Outdoors").click()
        # self.driver.find_element(By.ID, "Wine tasting").click()
        # self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        # self.driver.find_element(By.XPATH, "//li[@id='availability-list-business-25303']/div[1]/ul[1]/li[1]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div/div[2]/button[4]").click()
        self.driver.find_element(By.XPATH, "//span[text()='Outdoors']").click()
        self.driver.find_element(By.XPATH, "//span[text()='Wine tasting']").click()
        self.driver.find_element(By.XPATH, "//span[text()='Update search']").click()

        # may lead to failure if click too quick:selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//main[@id='maincontent']/div/div[3]/div[1]/div/div/div[1]/div/ul/li[1]/div/a").click()
