import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select


@pytest.mark.usefixtures("setup_class")
class TestOhiomeansjobsOhioGov:
    def test_ohiomeansjobsohiogov_63b039d1(self):
        # self.driver.get("https://ohiomeansjobs.ohio.gov")
        self.driver.find_element(By.XPATH, "//input[@type='search' and contains(@placeholder, 'Search by job title, skill or company') and @title='Enter Keywords']").clear()
        self.driver.find_element(By.XPATH, "//input[@type='search' and contains(@placeholder, 'Search by job title, skill or company') and @title='Enter Keywords']").send_keys("auto mechanic")
        self.driver.find_element(By.XPATH, "//form[@id='job-search-bar']/button[1]").click()
        self.driver.find_element(By.ID, "location").clear()
        self.driver.find_element(By.ID, "location").send_keys("Delaware, Ohio")

        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Search')]").click()
        self.driver.find_element(By.XPATH, "//a[text()='Search ']").click()

        self.driver.find_element(By.XPATH, "//a[@id='filtersSearchLink']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Career/Education Level')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Job Type')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Salary')]").click()
        self.driver.find_element(By.ID, "_ctl0_PageTemplateContent__ctlRefineSearch__ctlRefineSalary_rptFacet__ctl1_lnkFacet").click()
        self.driver.find_element(By.ID, "_ctl0_PageTemplateContent_msgRefine").click()

        # skip inputting the job title otherwise no result will return
        # self.driver.find_element(By.ID, "jobTitle").clear()
        # self.driver.find_element(By.ID, "jobTitle").send_keys("auto mechanic")
        # self.driver.find_element(By.ID, "ui-id-5").click()
        # self.driver.find_element(By.XPATH, "//div[contains(@id, 'ui-id-') and text()='Automotive Master Mechanic']").click()

        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Search')]").click()
        # selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
        # need to wait for several seconds since it takes several seconds for the filter popup to disappear and the page to become stable
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//a[text()='Search ']").click()

        # self.driver.find_element(By.ID, "radius").clear()
        # self.driver.find_element(By.ID, "radius").select("20 miles")
        radius_dropdown = self.driver.find_element(By.ID, "radius")
        radius_select = Select(radius_dropdown)
        radius_select.select_by_visible_text("20 miles")

        # remove redundant actions generated by the agent
        # self.driver.find_element(By.XPATH, "//a[@id='filtersSearchLink']/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='filtersButtonSection']/div[1]").click()
    