import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestBooking:
    
    def test_booking_94f88670(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.ID, ":Ra9:").clear()
        self.driver.find_element(By.ID, ":Ra9:").send_keys("seoul")
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[4]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[2]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[4]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_popular_:Rsq:']/div[7]/label[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_review_score_:R44q:']/div[7]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_fc_:R2cq:']/div[5]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_hotelfacility_:R4cq:']/div[3]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[3]/div[5]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[2]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "hprt_nos_select_25626201_189122660_0_2_0").clear()
        self.driver.find_element(By.ID, "hprt_nos_select_25626201_189122660_0_2_0").select("1 (US$217)")
        self.driver.find_element(By.XPATH, "//form[@id='hprt-form']/div[10]/div[2]/div[2]/div[6]/button[1]/span[2]").click()
    
    def test_booking_e37f9fa1(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='flights']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[2]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/span[2]/span[1]/span[1]/b[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/span[2]/span[1]/span[1]/b[1]").send_keys("banglore")
        self.driver.find_element(By.XPATH, "//div[@id='__bui-12']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[3]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-12']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[3]/div[1]/span[2]/span[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[3]/div[1]/span[2]/span[1]/span[1]").send_keys("goa")
        self.driver.find_element(By.XPATH, "//div[@id='__bui-14']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/span[3]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/div[1]/span[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-16']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[5]/td[3]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/button[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-10']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-10']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[3]/button[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='0']/div[1]/div[5]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='flight-card-0']/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Select')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/div[1]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]").click()
    
    def test_booking_b73503a7(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='airport_taxis']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "pickupLocation").clear()
        self.driver.find_element(By.ID, "pickupLocation").send_keys("O'hare Airport")
        self.driver.find_element(By.XPATH, "//ul[@id='pickupLocation-items']/li[2]/button[1]/div[1]/h4[1]").click()
        self.driver.find_element(By.ID, "dropoffLocation").clear()
        self.driver.find_element(By.ID, "dropoffLocation").send_keys("123 Main St, West Chicago, IL")
        self.driver.find_element(By.XPATH, "//ul[@id='dropoffLocation-items']/li[2]/button[1]/div[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='booking-taxi-searchbar__container']/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'29')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='booking-taxi-searchbar__container']/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='booking-taxi-searchbar__container']/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.ID, "passengers").clear()
        self.driver.find_element(By.ID, "passengers").select("2")
        self.driver.find_element(By.XPATH, "//div[@id='booking-taxi-searchbar__container']/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[contains(.,'Choose a standard-size taxi costing US$126.84')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Continue to book')]").click()
    
    def test_booking_c51cc2c0(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='attractions']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@name='query' and @value='' and @type='search' and @placeholder='Where are you going?']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='query' and @value='' and @type='search' and @placeholder='Where are you going?']").send_keys("Aquarium of Paris")
        self.driver.find_element(By.XPATH, "//div[contains(.,'Aquarium of Paris')]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'Select your dates')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'5')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Search')]").click()
        self.driver.find_element(By.XPATH, "//h4[contains(.,'Aquarium of Paris')]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
    
    def test_booking_dfa415d9(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='cars']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "ss_origin").clear()
        self.driver.find_element(By.ID, "ss_origin").send_keys("mexico city")
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[2]/div[4]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.ID, "__bui-42").clear()
        self.driver.find_element(By.ID, "__bui-42").select("Low to High")
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[3]/div[2]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[7]/div[1]/div[2]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//main[@id='main']/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/section[1]/div[1]/div[1]/div[3]/div[1]/button[1]/span[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='insurance-portal-root']/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]/div[1]/div[1]/span[1]").click()
    
    def test_booking_a83c14aa(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.ID, ":Ra9:").clear()
        self.driver.find_element(By.ID, ":Ra9:").send_keys("Timesqure New York")
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[4]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_popular_:Rsq:']/div[7]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_class_:R1cq:']/div[10]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h3[1]/a[1]/div[1]").click()
    
    def test_booking_754c8c29(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Hostels')]").click()
        self.driver.find_element(By.ID, "ss").clear()
        self.driver.find_element(By.ID, "ss").send_keys("udupi")
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/table[1]/tbody[1]/tr[3]/td[5]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/table[1]/tbody[1]/tr[4]/td[3]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//label[@id='xp__guests__toggle']/span[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='xp__guests__inputs-container']/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[4]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_used_filters_:Rcq:']/div[15]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_pri_:Rkq:']/div[2]/div[3]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_used_filters_:Rcq:']/div[7]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_used_filters_:Rcq:']/div[5]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_roomfacility_:R4kq:']/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_roomfacility_:R4kq:']/div[8]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[1]/span[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':R9:']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[3]/div[5]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='hprt-form']/div[6]/div[2]/div[2]/div[7]/button[1]/span[2]").click()
    
    def test_booking_14b72eb6(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='packages']/div[1]/span[1]").click()
        self.driver.find_element(By.ID, ":R56:").clear()
        self.driver.find_element(By.ID, ":R56:").send_keys("SHANGHAI")
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, ":R5a:").clear()
        self.driver.find_element(By.ID, ":R5a:").send_keys("SEOUL")
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':Re:']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]/span[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':Re:']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[3]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':Re:']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[5]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[3]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Choose Another Hotel')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[2]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[3]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='rates-table-2863505']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[2]/div[1]/div[1]/div[1]/div[1]/label[1]/div[1]/svg[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/div[2]/div[1]/div[2]/div[1]/div[1]/label[1]/div[1]/svg[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/div[2]/div[2]/div[1]/button[1]").click()
    
    def test_booking_3d76a0fc(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.ID, "packages").click()
        self.driver.find_element(By.ID, ":r5:").clear()
        self.driver.find_element(By.ID, ":r5:").send_keys("KATHMANDU")
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, ":r6:").clear()
        self.driver.find_element(By.ID, ":r6:").send_keys("SHANGHAI")
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[2]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':r7:']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':r7:']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[5]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='bodyconstraint-inner']/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='option1']/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[1]/div[1]/div[3]/div[2]/div[1]/div[7]/div[1]/div[1]/div[1]/label[1]/div[1]/div[1]/div[1]/svg[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[2]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[2]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='rates-table-59933804']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/div[1]/label[1]/div[1]/svg[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[2]/div[1]/div[1]/label[1]/div[1]/svg[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[2]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[1]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/div[3]/div[1]/button[1]/div[1]").click()
    
    def test_booking_4272e233(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='attractions']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Asia')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='8']/div[1]/div[1]/div[61]/div[1]/a[1]/div[1]/figure[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'Select your dates')]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'25')]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/fieldset[1]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[4]/div[1]/fieldset[1]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//label[contains(.,'Most popular')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'See availability')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Show more dates')]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[2]/div[1]/button[1]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'25')]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "/html/body[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[1]/div[2]/button[2]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    
    def test_booking_6ab8130f(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.ID, ":Ra9:").clear()
        self.driver.find_element(By.ID, ":Ra9:").send_keys("GOA")
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[5]/td[3]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[5]/td[7]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='indexsearch']/div[2]/div[1]/div[1]/form[1]/div[1]/div[4]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_class_:R1cq:']/div[8]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_ht_id_:R2sq:']/div[6]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_ht_id_:R2sq:']/div[10]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_popular_:Rsq:']/div[15]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_used_filters_:Rcq:']/div[5]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_popular_activities_:R1kq:']/div[10]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_popular_:Rsq:']/div[17]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_pri_:Rkq:']/div[2]/div[5]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[1]/span[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id=':R9:']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/button[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='hp_book_now_button']/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='hprt-form']/div[6]/div[2]/div[2]/div[7]/button[1]/span[2]").click()
    
    def test_booking_fc552b69(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[@id='flights']/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/span[2]/span[1]/span[1]/b[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/div[1]/span[2]/span[1]/span[1]/b[1]").send_keys("NEW YORK")
        self.driver.find_element(By.XPATH, "//div[@id='__bui-12']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[3]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-12']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[3]/div[1]/span[2]/span[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[3]/div[1]/span[2]/span[1]/span[1]").send_keys("TOKYO")
        self.driver.find_element(By.XPATH, "//div[@id='__bui-14']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[3]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[3]/label[1]/span[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/div[1]/span[2]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-16']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[4]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/div[1]/span[2]/span[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/div[1]/span[2]/span[1]/span[1]").send_keys("TOKYO")
        self.driver.find_element(By.XPATH, "//div[@id='__bui-46']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[3]/div[1]/span[2]/span[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[3]/div[1]/span[2]/span[1]/span[1]").send_keys("NEW DELHI")
        self.driver.find_element(By.XPATH, "//div[@id='__bui-48']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/span[1]/b[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='__bui-50']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/button[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/nav[1]/div[1]/ul[1]/li[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='flight-card-0']/div[1]/div[1]/div[2]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,'Select')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/div[1]/div[1]/div[1]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='basiclayout']/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    
    def test_booking_fdd4fc92(self):
        # self.driver.get("https://booking.com")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Homes')]").click()
        self.driver.find_element(By.ID, "ss").clear()
        self.driver.find_element(By.ID, "ss").send_keys("MANILA")
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/span[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/table[1]/tbody[1]/tr[1]/td[5]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[2]/table[1]/tbody[1]/tr[2]/td[5]").click()
        self.driver.find_element(By.XPATH, "//form[@id='frm']/div[1]/div[4]/div[2]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_class_:R14q:']/div[12]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_hotelfacility_:R44q:']/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_hotelfacility_:R44q:']/div[3]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_roomfacility_:R4cq:']/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_accessible_room_facilities_:R5cq:']/div[15]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_tdb_:R3kq:']/div[5]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='filter_group_mealplan_:R2cq:']/div[3]/label[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='search_results_table']/div[2]/div[1]/div[1]/div[3]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='hp_book_now_button']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='hprt-ws--reserve-column']/div[2]/div[6]/button[1]/span[2]").click()
    