import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestKayak:
    
    def test_kayak_f38789fb(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='EOo7']/div[1]/div[2]/nav[2]/div[2]/a[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").send_keys("United States")
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text']").send_keys("Cambodia")
        self.driver.find_element(By.ID, "kh").click()
    
    def test_kayak_3b0a3ed2(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("little ferry")
        self.driver.find_element(By.XPATH, "//li[@id='23441_city_Little Ferry, New Jersey, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'23')]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'4')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/span[2]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[contains(.,'2:00 pm')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[2]/button[1]/div[1]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='horizontalFilters']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='mapListWrapper']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]").click()
    
    def test_kayak_eb03aa9f(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='dOOn']/div[1]/div[2]/nav[2]/div[2]/a[2]/div[1]").click()
        self.driver.find_element(By.ID, "c4a-Z-flightNumberTrackForm-airline").clear()
        self.driver.find_element(By.ID, "c4a-Z-flightNumberTrackForm-airline").send_keys("Qatar Airways")
        self.driver.find_element(By.XPATH, "//li[@id='al-QR']/div[1]/b[1]").click()
        self.driver.find_element(By.ID, "c4a-Z-flightNumberTrackForm-flight-number").clear()
        self.driver.find_element(By.ID, "c4a-Z-flightNumberTrackForm-flight-number").send_keys("D145")
        self.driver.find_element(By.ID, "c4a-Z-flightNumberTrackForm-submit").click()
    
    def test_kayak_628e5ce1(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='g0Rt']/div[1]/div[2]/nav[1]/div[1]/a[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Narita, Tokyo, Tokyo Prefecture, Japan' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Narita, Tokyo, Tokyo Prefecture, Japan' and @type='text' and @placeholder='From?']").send_keys("Las Vegas")
        self.driver.find_element(By.XPATH, "//li[@id='35107_city_Las Vegas, Nevada, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/span[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'5')]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'12')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/span[1]/div[1]/div[3]/span[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='horizontalFilters']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/img[1]").click()
    
    def test_kayak_13b786ab(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='lFNy']/div[1]/div[2]/nav[1]/div[1]/a[5]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='gEeT']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='oneway']/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Columbus' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Columbus' and @type='text' and @placeholder='From?']").send_keys("ALEXANDRIA")
        self.driver.find_element(By.XPATH, "//li[@id='29793_city_Alexandria, Virginia, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("PENN STATION")
        self.driver.find_element(By.XPATH, "//li[@id='ZYP_rail_Penn Station, New York, United States']/div[1]/div[3]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='gEeT']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/span[1]/span[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='oEge']/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[4]").click()
        self.driver.find_element(By.XPATH, "//div[@id='gEeT']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/button[1]/div[1]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='dhWM-sorting-display']/svg[1]/path[1]").click()
        self.driver.find_element(By.ID, "dhWM-sorting-option-4").click()
        self.driver.find_element(By.XPATH, "//div[@id='V06Z']/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c_5d8']/a[1]/span[1]/span[1]").click()
    
    def test_kayak_31dc6f28(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("Japan")
        self.driver.find_element(By.XPATH, "//input[@value='false' and @type='checkbox']").click()
        self.driver.find_element(By.XPATH, "//div[@id='Kus3']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//body[@id='knPo']/div[8]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[20]").click()
        self.driver.find_element(By.XPATH, "//body[@id='knPo']/div[8]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[27]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Kus3']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/button[1]").click()
    
    def test_kayak_8dc49f67(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='U9qF']/div[1]/div[2]/nav[1]/div[1]/a[2]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").send_keys("Chennai")
        self.driver.find_element(By.XPATH, "//li[@id='13827_city_Chennai, Tamil Nadu, India']/div[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c4vu4']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[23]").click()
        self.driver.find_element(By.XPATH, "//button[@role='button' and @type='submit' and @title='']").click()
        self.driver.find_element(By.XPATH, "//div[@id='ResultsListSortDropdownLabel']/div[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='userrating_b']/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-freeinternet").click()
        self.driver.find_element(By.ID, "valueSetFilter-freecancellation").click()
    
    def test_kayak_6d5c4d19(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='B3UT']/div[1]/div[2]/nav[1]/div[1]/a[2]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Los Angeles, California, United States' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Los Angeles, California, United States' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").send_keys("Los Angeles")
        self.driver.find_element(By.XPATH, "//li[@id='16078_city_Los Angeles, California, United States']/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c58Mm']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[22]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c58Mm']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[24]").click()
        self.driver.find_element(By.XPATH, "//div[@id='h31f']/div[1]/div[1]/div[2]/button[1]/div[1]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='peYi']/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[4]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='UFe1']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]/span[1]/span[1]/svg[1]").click()
    
    def test_kayak_7c2ab1ed(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='c6BR5']/div[1]/div[2]/nav[1]/div[1]/a[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("madurai")
        self.driver.find_element(By.XPATH, "//body[@id='YkSy']/div[7]/div[1]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='zG2Z']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//button[@role='button' and @type='submit' and @title='']").click()
        self.driver.find_element(By.XPATH, "//div[@id='c4TEL-providers-title']/div[1]/svg[1]").click()
        self.driver.find_element(By.ID, "c4TEL-providers-5467-AI-check-label").click()
        self.driver.find_element(By.ID, "c4TEL-providers-5467-AI-only").click()
        self.driver.find_element(By.XPATH, "//div[@id='I-9I']/div[1]/div[1]/div[1]").click()
    
    def test_kayak_913b902b(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='pBYt']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='oneway']/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("new york")
        self.driver.find_element(By.XPATH, "//li[@id='JFK_ap_John F Kennedy Intl, New York, United States, (JFK)']/div[1]/div[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("male")
        self.driver.find_element(By.XPATH, "//li[@id='MLE_ap_Male, Malé, Maldives, (MLE)']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//span[@role='button']").click()
        self.driver.find_element(By.XPATH, "//body[@id='f4B6']/div[8]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[16]").click()
        self.driver.find_element(By.XPATH, "//button[@role='button' and @type='submit' and @title='']").click()
        self.driver.find_element(By.ID, "JUB0-stops-3845-2-check-icon").click()
        self.driver.find_element(By.XPATH, "//div[@id='HNMB']/div[1]/div[3]/div[1]/div[1]").click()
    
    def test_kayak_9ab66035(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='V5rC']/div[1]/div[2]/nav[1]/div[1]/a[4]/div[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Hawaii Vacations')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='jl1W-dateRangeInput-display-start']/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='fu0N-next']/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='fu0N-202306']/div[1]/div[3]/div[4]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='fu0N-202306']/div[1]/div[3]/div[4]/div[4]/div[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='jl1W-submit']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='leftRail']/div[1]/div[1]/div[1]/div[1]/div[3]/div[9]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-amenities-beachfront").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-amenities-hottub").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-amenities-pool").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-amenities-towels").click()
        self.driver.find_element(By.XPATH, "//div[@id='leftRail']/div[1]/div[1]/div[1]/div[1]/div[3]/div[10]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-ambiance-ha:beach").click()
        self.driver.find_element(By.XPATH, "//div[@id='ResultsListSortDropdownLabel']/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='price_a']/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='packagePrice_providerSelect_3309008']/div[1]/button[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='app-layer-base']/div[2]/div[4]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/button[1]").click()
    
    def test_kayak_f8027aa8(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='sIqV']/div[1]/div[2]/nav[1]/div[1]/a[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").send_keys("Las Vegas")
        self.driver.find_element(By.XPATH, "//li[@id='35107_city_Las Vegas, Nevada, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='UZAo']/div[1]/div[1]/div[2]/button[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-freeairportshuttle").click()
    
    def test_kayak_d88f70e8(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[1]/div[1]/div[2]/nav[1]/div[1]/a[2]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Las Vegas, Nevada, United States' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Las Vegas, Nevada, United States' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").send_keys("Santa Fe")
        self.driver.find_element(By.XPATH, "//li[@id='9720_city_Santa Fe, New Mexico, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='JSW6']/div[15]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[20]").click()
        self.driver.find_element(By.XPATH, "//body[@id='JSW6']/div[15]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[22]").click()
        self.driver.find_element(By.XPATH, "//body[@id='JSW6']/div[15]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//body[@id='JSW6']/div[15]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='E5eb']/div[1]/div[1]/div[2]/button[1]/div[1]/div[1]/svg[1]/path[1]").click()
    
    def test_kayak_e7fbd3a3(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[1]/div[1]/div[2]/nav[1]/div[1]/a[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c09F5']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='oneway']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c09F5']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c3Wtr']/div[7]/div[1]/div[2]/div[1]/div[2]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c3Wtr']/div[7]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='']").send_keys("new york")
        self.driver.find_element(By.XPATH, "//div[@id='c09F5']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='NYC_ap_All airports, New York, United States, (NYC)']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("london")
        self.driver.find_element(By.XPATH, "//li[@id='LON_ap_All airports, London, England, United Kingdom, (LON)']/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c09F5']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c3Wtr']/div[7]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[29]").click()
        self.driver.find_element(By.XPATH, "//div[@id='c09F5']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/button[1]/div[1]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='svJp']/div[1]/div[1]/div[1]/div[1]/span[1]").click()
    
    def test_kayak_f3bf7fe9(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='lixd']/div[1]/div[2]/nav[1]/div[1]/a[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("Seattle")
        self.driver.find_element(By.XPATH, "//li[@id='7054_city_Seattle, Washington, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/span[1]/div[1]/span[1]/button[1]/div[1]/div[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='mapListWrapper']/div[1]/div[1]/div[2]/div[4]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='score_b']/span[1]").click()
    
    def test_kayak_f7c2c65f(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='tc7n']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='oneway']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tc7n']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='jwfT']/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tc7n']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("NEW YORK")
        self.driver.find_element(By.XPATH, "//li[@id='NYC_ap_All airports, New York, United States, (NYC)']/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("PARIS")
        self.driver.find_element(By.XPATH, "//li[@id='PAR_ap_All airports, Paris, France, (PAR)']/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tc7n']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/span[1]/span[1]/span[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='jwfT']/div[8]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[8]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tc7n']/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='jwfT']/div[8]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='jwfT']/div[8]/div[1]/div[2]/div[1]/div[2]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='tc7n']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/button[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ItPj']/div[1]/div[3]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.ID, "S1Lt-cabin-title").click()
        self.driver.find_element(By.ID, "S1Lt-cabin-6987-bfbe-check-icon").click()
        self.driver.find_element(By.ID, "S1Lt-cabin-8573-e-check-icon").click()
        self.driver.find_element(By.ID, "S1Lt-cabin-8063-p-check-icon").click()
        self.driver.find_element(By.ID, "S1Lt-cabin-4139--check-icon").click()
        self.driver.find_element(By.XPATH, "//div[@id='arT_']/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/a[1]/div[1]/div[1]").click()
    
    def test_kayak_26d3a803(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='W8Qe']/div[1]/div[2]/nav[1]/div[1]/a[4]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Hawaii Vacations')]").click()
        self.driver.find_element(By.XPATH, "//button[@id='Fw2F-submit']/span[1]").click()
    
    def test_kayak_38fe67f7(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='DrTD']/div[1]/div[2]/nav[1]/div[1]/a[2]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").send_keys("kashi vishwanath temple")
        self.driver.find_element(By.XPATH, "//li[@id='49920_lm_Kashi Vishwanath Temple, Varanasi, Uttar Pradesh, India']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[2]/div[1]/div[1]/div[3]/button[1]/div[1]/div[1]/span[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[10]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[14]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").clear()
        self.driver.find_element(By.XPATH, "//body[@id='ko_A']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").send_keys("7")
        self.driver.find_element(By.XPATH, "//li[@id='7']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='V-pg']/div[1]/div[1]/div[2]/button[1]/div[1]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='S6QL']/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[2]/div[4]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='S6QL']/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[3]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-freebies-freeinternet").click()
        self.driver.find_element(By.XPATH, "//div[@id='S6QL']/div[1]/div[1]/div[1]/div[1]/div[1]/div[15]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-ambiance-ha:familyfriendly").click()
        self.driver.find_element(By.XPATH, "//div[@id='S6QL']/div[1]/div[1]/div[1]/div[1]/div[1]/div[14]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-vertical-amenities-ac").click()
        self.driver.find_element(By.XPATH, "//div[@id='ResultsListSortDropdownLabel']/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='price_a']/div[1]").click()
    
    def test_kayak_e9f5f0d0(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='J0hn']/div[1]/div[2]/nav[1]/div[1]/a[3]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/div[1]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='oneway']/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("Miami Airport")
        self.driver.find_element(By.XPATH, "//li[@id='MIA_ap_Miami, Miami, Florida, United States, (MIA)']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("Miami")
        self.driver.find_element(By.XPATH, "//li[@id='14305_city_Miami, Florida, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[2]/button[1]/div[1]/div[1]/svg[1]").click()
    
    def test_kayak_eee72e78(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='c_V_B']/div[1]/div[2]/nav[1]/div[1]/a[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter a city, hotel, airport, address or landmark']").send_keys("Le maraise")
        self.driver.find_element(By.XPATH, "//li[@id='217159_hood_Le Marais, Paris, France']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='sY06']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[30]").click()
        self.driver.find_element(By.XPATH, "//body[@id='sY06']/div[16]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[8]").click()
        self.driver.find_element(By.XPATH, "//button[@role='button' and @type='submit' and @title='']").click()
        self.driver.find_element(By.XPATH, "//div[@id='aCfi']/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[4]/span[3]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c1BUH']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c1BUH']/div[16]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchFormDialog']/section[2]/div[1]/div[1]/div[2]/button[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ResultsListSortDropdownLabel']/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='price_a']/div[1]").click()
    
    def test_kayak_82f654ab(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='kaO-']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='oneway']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='kaO-']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("New York City")
        self.driver.find_element(By.XPATH, "//input[@value='false' and @type='checkbox']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("London")
        self.driver.find_element(By.XPATH, "//input[@value='false' and @type='checkbox']").click()
        self.driver.find_element(By.XPATH, "//div[@id='kaO-']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/button[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.ID, "NRB--stops-7727-1-check-icon").click()
        self.driver.find_element(By.ID, "NRB--stops-7666-2-check-icon").click()
    
    def test_kayak_837989e0(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='rA68']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='From?']").send_keys("Mumbai")
        self.driver.find_element(By.XPATH, "//li[@id='BOM_ap_Chhatrapati Shivaji Intl, Mumbai, Maharashtra, India, (BOM)']/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='To?']").send_keys("Dubai")
        self.driver.find_element(By.XPATH, "//li[@id='DXB_ap_All airports, Dubai, United Arab Emirates, (DXB)']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='rA68']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.ID, "oneway").click()
        self.driver.find_element(By.XPATH, "//div[@id='rA68']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//body[@id='ULyL']/div[8]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[25]").click()
        self.driver.find_element(By.XPATH, "//div[@id='rA68']/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='iww_']/div[1]/div[1]/div[1]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='ZOCr']/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/a[1]/div[1]/div[1]").click()
    
    def test_kayak_67648411(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='thaI']/div[1]/div[2]/nav[1]/div[1]/a[3]").click()
        self.driver.find_element(By.XPATH, "//input[@value='New Orleans, Louisiana, United States' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='New Orleans, Louisiana, United States' and @type='text' and @placeholder='From?']").send_keys("new orleans")
        self.driver.find_element(By.XPATH, "//li[@id='22085_city_New Orleans, Louisiana, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='New York, New York, United States' and @type='text' and @placeholder='To?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='New York, New York, United States' and @type='text' and @placeholder='To?']").send_keys("new york")
        self.driver.find_element(By.XPATH, "//li[@id='15830_city_New York, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'25')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[3]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'1')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/span[2]/div[1]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//li[contains(.,'2:00 pm')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[2]/div[2]/button[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//label[@id='carclass-label']/div[2]").click()
        self.driver.find_element(By.ID, "valueSetFilter-SUV").click()
        self.driver.find_element(By.XPATH, "//div[@id='leftRail']/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//label[@id='caragency-label']/div[2]").click()
        self.driver.find_element(By.ID, "valueSetFilter-avis").click()
        self.driver.find_element(By.XPATH, "//div[@id='leftRail']/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-doors4+").click()
        self.driver.find_element(By.XPATH, "//div[@id='priceFilterSection_v']/div[1]/div[2]/div[2]/div[1]/input[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='priceFilterSection_v']/div[1]/div[2]/div[2]/div[1]/input[1]").send_keys("1000")
        self.driver.find_element(By.XPATH, "//div[contains(.,'Show results')]").click()
    
    def test_kayak_b20e1dc4(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='cpDa']/div[1]/div[2]/nav[1]/div[1]/a[3]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Los Angeles, California, United States' and @type='text' and @placeholder='From?']").click()
        self.driver.find_element(By.XPATH, "//input[@value='Los Angeles, California, United States' and @type='text' and @placeholder='From?']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Los Angeles, California, United States' and @type='text' and @placeholder='From?']").send_keys("Brooklyn")
        self.driver.find_element(By.XPATH, "//li[@id='1579_city_Brooklyn, New York, United States']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//li[@id='roundtrip']/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/span[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[contains(.,'22')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-search-form']/div[1]/div[1]/span[1]/div[1]/div[3]/span[1]/button[1]/div[1]/div[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='horizontalFilters']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[4]/img[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='mapListWrapper']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='providerSelect_ae041be8f6b958c5ab034781166e09a7']/button[1]/div[1]/div[1]").click()
    
    def test_kayak_d63b1715(self):
        # self.driver.get("https://www.kayak.com/")
        self.driver.find_element(By.XPATH, "//div[@id='zkuT']/div[1]/div[2]/nav[1]/div[1]/a[4]/div[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='Columbus (CMH)' and @type='text' and @placeholder='From']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='Columbus (CMH)' and @type='text' and @placeholder='From']").send_keys("Birmingham")
        self.driver.find_element(By.XPATH, "//li[@id='BHX_ap_Birmingham, Birmingham, England, United Kingdom, (BHX)']/div[1]/div[2]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter destination or airport']").clear()
        self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Enter destination or airport']").send_keys("Paris")
        self.driver.find_element(By.XPATH, "//li[@id='36014_city_Paris, France']/div[1]/div[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchForm']/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c3IAI']/div[6]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[13]").click()
        self.driver.find_element(By.XPATH, "//body[@id='c3IAI']/div[6]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[17]").click()
        self.driver.find_element(By.XPATH, "//div[@id='searchForm']/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]/div[1]/div[1]/svg[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-freeInternet").click()
        self.driver.find_element(By.XPATH, "//div[@id='leftRail']/div[1]/div[1]/div[1]/div[1]/div[3]/div[9]/div[1]/div[1]").click()
        self.driver.find_element(By.ID, "valueSetFilter-casino").click()
        self.driver.find_element(By.ID, "valueSetFilter-restaurant").click()
        self.driver.find_element(By.ID, "valueSetFilter-fitness").click()
    