import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select


@pytest.mark.usefixtures("setup_class")
class TestCargurus:
    
    # def test_cargurus_4056a671(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch']/label[2]/span[1]").click()
    #     self.driver.find_element(By.ID, "carPickerUsed_makerSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerUsed_makerSelect").select("Honda")
    #     self.driver.find_element(By.ID, "carPickerUsed_modelSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerUsed_modelSelect").select("Crosstour")
    #     self.driver.find_element(By.ID, "dealFinderZipUsedId_dealFinderForm").clear()
    #     self.driver.find_element(By.ID, "dealFinderZipUsedId_dealFinderForm").send_keys("49102")
    #     self.driver.find_element(By.ID, "dealFinderForm_0").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[2]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[2]/div[1]/select[1]").select("2013")
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.ID, "sort-listing").clear()
    #     self.driver.find_element(By.ID, "sort-listing").select("Lowest mileage first")
    #
    # def test_cargurus_c44cfc8c(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_finance']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//nav[@id='headerNav']/div[1]/ul[1]/li[3]/div[1]/div[1]/div[4]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='price' and @value='$0' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='price' and @value='$0' and @type='text']").send_keys("25000")
    #     self.driver.find_element(By.XPATH, "//input[@name='downPayment' and @value='$0' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='downPayment' and @value='$0' and @type='text']").send_keys("5000")
    #     self.driver.find_element(By.XPATH, "//input[@name='rate' and @value='0.00%']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='rate' and @value='0.00%']").send_keys("12")
    #     self.driver.find_element(By.XPATH, "//div[@id='monthlyPaymentPortal']/div[1]/div[1]/fieldset[1]/fieldset[1]/div[2]/label[2]").click()
    #
    # def test_cargurus_cc643c1f(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch']/label[4]/span[1]").click()
    #     self.driver.find_element(By.ID, "carPickerCpo_makerSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerCpo_makerSelect").select("Lexus")
    #     self.driver.find_element(By.ID, "carPickerCpo_modelSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerCpo_modelSelect").select("RX")
    #     self.driver.find_element(By.ID, "dealFinderZipCPOId").clear()
    #     self.driver.find_element(By.ID, "dealFinderZipCPOId").send_keys("90012")
    #     self.driver.find_element(By.ID, "dealFinderFormCPO_0").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[1]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[1]/div[1]/select[1]").select("2017")
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[2]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[2]/div[1]/select[1]").select("2017")
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[7]/ul[1]/li[11]/label[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "sort-listing").clear()
    #     self.driver.find_element(By.ID, "sort-listing").select("Lowest price first")
    #
    # def test_cargurus_998e55fb(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_buy']/span[1]").click()
    #     self.driver.find_element(By.ID, "Select Make").clear()
    #     self.driver.find_element(By.ID, "Select Make").select("BMW")
    #     self.driver.find_element(By.ID, "Select Model").clear()
    #     self.driver.find_element(By.ID, "Select Model").select("i3")
    #     self.driver.find_element(By.ID, "postal-code-input").clear()
    #     self.driver.find_element(By.ID, "postal-code-input").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//div[@id='search-form']/form[1]/button[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "sort-listing").clear()
    #     self.driver.find_element(By.ID, "sort-listing").select("Lowest price first")
    #
    # def test_cargurus_99b9a850(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.ID, "carPickerUsed_makerSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerUsed_makerSelect").select("Tesla")
    #     self.driver.find_element(By.ID, "dealFinderZipUsedId_dealFinderForm").clear()
    #     self.driver.find_element(By.ID, "dealFinderZipUsedId_dealFinderForm").send_keys("10017")
    #     self.driver.find_element(By.ID, "dealFinderForm_0").click()
    #
    # def test_cargurus_b1eb6602(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_buy']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//nav[@id='headerNav']/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='categories']/ul[1]/li[2]/a[1]/div[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "zip").clear()
    #     self.driver.find_element(By.ID, "zip").send_keys("10017")
    #     self.driver.find_element(By.XPATH, "//div[@id='react-tabs-7']/form[1]/div[2]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[3]/div[1]/div[1]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[3]/div[1]/div[1]/div[1]/select[1]").select("2022")
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[3]/div[1]/div[2]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[3]/div[1]/div[2]/div[1]/select[1]").select("2023")
    #     self.driver.find_element(By.ID, "select-filter").clear()
    #     self.driver.find_element(By.ID, "select-filter").select("50 mi")
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[5]/ul[1]/li[11]/label[1]/p[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[6]/ul[1]/li[1]/label[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[9]/ul[1]/li[23]/label[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[12]/ul[1]/li[13]/label[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "sort-listing").clear()
    #     self.driver.find_element(By.ID, "sort-listing").select("Newest first (by car year)")
    #     self.driver.find_element(By.XPATH, "//h4[@title='New 2023 Lexus NX 350 AWD']").click()
    #
    # def test_cargurus_0dd6fbb7(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_research']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//nav[@id='headerNav']/div[1]/ul[1]/li[4]/div[1]/div[1]/div[4]/ul[1]/li[2]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='trendsDates']/fieldset[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@title='Previous Month']").click()
    #     self.driver.find_element(By.XPATH, "//span[@title='Previous Month']").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='trendsDates']/fieldset[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='trendsDates']/fieldset[1]/div[1]/div[2]/div[1]/div[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//span[@title='Previous Month']").click()
    #     self.driver.find_element(By.XPATH, "//span[@title='Previous Month']").click()
    #     self.driver.find_element(By.XPATH, "//span[@title='Previous Month']").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='trendsDates']/fieldset[1]/div[1]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/table[1]/tbody[1]/tr[5]/td[3]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='Update Chart' and @type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='m1' and @type='checkbox']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='m2' and @type='checkbox']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='m32' and @type='checkbox']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='m7' and @type='checkbox']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='m112' and @type='checkbox']").click()
    #
    # def test_cargurus_69661946(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch']/label[2]/span[1]").click()
    #     self.driver.find_element(By.ID, "carPickerUsed_makerSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerUsed_makerSelect").select("Toyota")
    #     self.driver.find_element(By.ID, "carPickerUsed_modelSelect").clear()
    #     self.driver.find_element(By.ID, "carPickerUsed_modelSelect").select("Corolla")
    #     self.driver.find_element(By.ID, "dealFinderZipUsedId_dealFinderForm").clear()
    #     self.driver.find_element(By.ID, "dealFinderZipUsedId_dealFinderForm").send_keys("10019")
    #     self.driver.find_element(By.ID, "dealFinderForm_0").click()
    #     self.driver.find_element(By.ID, "sort-listing").clear()
    #     self.driver.find_element(By.ID, "sort-listing").select("Lowest price first")
    #
    # def test_cargurus_82c5913d(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_finance']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//nav[@id='headerNav']/div[1]/ul[1]/li[3]/div[1]/div[1]/div[4]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='price' and @value='$50,000' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='price' and @value='$50,000' and @type='text']").send_keys("50000")
    #     self.driver.find_element(By.XPATH, "//input[@name='downPayment' and @value='$10,000' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='downPayment' and @value='$10,000' and @type='text']").send_keys("10000")
    #     self.driver.find_element(By.XPATH, "//input[@name='rate' and @value='0.00%']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='rate' and @value='']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='rate' and @value='']").send_keys("4")
    #     self.driver.find_element(By.XPATH, "//div[@id='monthlyPaymentPortal']/div[1]/div[1]/fieldset[1]/fieldset[1]/div[2]/label[3]/span[1]").click()
    #
    # def test_cargurus_e91126e0(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_research']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/div[1]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/div[1]/div[1]/select[1]").select("Audi")
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/div[2]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/div[2]/div[1]/select[1]").select("A6")
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/div[3]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/div[3]/div[1]/select[1]").select("2020")
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[1]/section[1]/form[1]/a[1]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[2]/div[1]/div[1]/div[4]/ul[1]/li[2]").click()
    #
    # def test_cargurus_edb8e817(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch']/label[3]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='smcVinPlateField' and @type='text' and @placeholder='(EX.) C4R 6URU']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='smcVinPlateField' and @type='text' and @placeholder='(EX.) C4R 6URU']").send_keys("XA1234")
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch-tab-content-2']/section[1]/form[1]/section[1]/fieldset[2]/div[1]/label[2]/div[1]/select[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch-tab-content-2']/section[1]/form[1]/section[1]/fieldset[2]/div[1]/label[2]/div[1]/select[1]").select("AZ")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_cargurus_eeeee9d8(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Our Team')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='post-2']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "select2-cws_jobsearch_parent_category-container").click()
    #     self.driver.find_element(By.ID, "select2-cws_jobsearch_parent_category-result-td3e-Sales & Ad Ops").click()
    #     self.driver.find_element(By.ID, "select2-cws_jobsearch_countryStateCity-container").click()
    #     self.driver.find_element(By.ID, "select2-cws_jobsearch_countryStateCity-result-d46u-US, CA, San Francisco").click()
    #     self.driver.find_element(By.ID, "job-result0").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Apply Now')]").click()
    #
    # def test_cargurus_fcb50c4e(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_buy']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//nav[@id='headerNav']/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "makes").clear()
    #     self.driver.find_element(By.ID, "makes").select("Jeep")
    #     self.driver.find_element(By.ID, "models").clear()
    #     self.driver.find_element(By.ID, "models").select("Compass")
    #     self.driver.find_element(By.ID, "ZIP").clear()
    #     self.driver.find_element(By.ID, "ZIP").send_keys("59316")
    #     self.driver.find_element(By.ID, "distance").clear()
    #     self.driver.find_element(By.ID, "distance").select("500 mi")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[9]/ul[1]/li[1]/label[1]/p[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/fieldset[18]/ul[1]/li[1]/label[1]/p[1]").click()
    #     self.driver.find_element(By.ID, "sort-listing").clear()
    #     self.driver.find_element(By.ID, "sort-listing").select("Lowest mileage first")
    #     self.driver.find_element(By.XPATH, "//div[@id='cargurus-listing-search']/div[1]/div[1]/div[2]/div[2]/div[5]/div[1]/div[1]/a[1]/div[3]/div[1]/div[2]/div[1]/button[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='listingSearchContactForm-waiid']/form[1]/div[4]/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='listingSearchContactForm-waiid']/form[1]/div[4]/button[1]/div[1]/span[1]").click()
    #
    # def test_cargurus_dd13bc51(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//button[@id='wai_snm_cnl_finance']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//nav[@id='headerNav']/div[1]/ul[1]/li[3]/div[1]/div[1]/div[3]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='price' and @value='$0' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='price' and @value='$0' and @type='text']").send_keys("30000")
    #     self.driver.find_element(By.XPATH, "//input[@name='downPayment' and @value='$0' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='downPayment' and @value='$0' and @type='text']").send_keys("6000")
    #     self.driver.find_element(By.XPATH, "//div[@id='monthlyPaymentPortal']/div[1]/div[2]/fieldset[1]/fieldset[1]/div[1]/label[3]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='monthlyPaymentPortal']/div[1]/div[2]/fieldset[1]/fieldset[1]/div[2]/label[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='monthlyPaymentPortal']/div[1]/div[2]/div[1]/div[3]/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.firstName' and @value='' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.firstName' and @value='' and @type='text']").send_keys("john")
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.lastName' and @value='' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.lastName' and @value='' and @type='text']").send_keys("doew")
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.emailAddress' and @value='buckeye.foobar@gmail.com' and @type='email']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.emailAddress' and @value='buckeye.foobar@gmail.com' and @type='email']").send_keys("johndoew@gmail.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.phoneNumbers[0]' and @value='' and @type='phone']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.phoneNumbers[0]' and @value='' and @type='phone']").send_keys("4533234565")
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.taxId' and @value='' and @type='password']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.taxId' and @value='' and @type='password']").send_keys("234567895")
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.dateOfBirth' and @value='' and @type='password']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='applicant.dateOfBirth' and @value='' and @type='password']").send_keys("06/23/1992")
    
    def test_cargurus_e832e1f9(self):
        # self.driver.get("https://www.cargurus.com/")
        self.driver.find_element(By.XPATH, "//div[@id='heroSearch']/label[2]/span[1]").click()
        self.driver.find_element(By.XPATH, "//input[@name='smcVinPlateField' and @type='text' and @placeholder='(EX.) C4R 6URU']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='smcVinPlateField' and @type='text' and @placeholder='(EX.) C4R 6URU']").send_keys("YAW639")
        dropdown_element = self.driver.find_element(By.XPATH, "//div[@id='heroSearch-tab-content-1']/section/form/section/fieldset[2]/div/label[2]/div/select")
        select = Select(dropdown_element)
        select.select_by_value('LA')
        self.driver.find_element(By.XPATH, "//button[@type='submit' and contains(., 'Get your offer')]").click()
        self.driver.find_element(By.ID, "postalCode").clear()
        self.driver.find_element(By.ID, "postalCode").send_keys("70726")
        self.driver.find_element(By.XPATH, "//section[@id='location']/div[1]/div[1]/form[1]/div[2]/button[1]/div[1]").click()
        self.driver.find_element(By.ID, "mileage").click()
        self.driver.find_element(By.ID, "mileage").send_keys("222900")
        self.driver.find_element(By.XPATH, "//section[@id='car-details']/div[1]/div[1]/form[1]/button[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='car-features']/div[1]/div[1]/form[1]/fieldset[1]/label[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='car-features']/div[1]/div[1]/form[1]/fieldset[2]/div[1]/div[1]/label[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='car-features']/div[1]/div[1]/form[1]/div[1]/button[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/label[3]").click()

        condition_dropdown = self.driver.find_element(By.ID, "CONDITION")
        condition_select = Select(condition_dropdown)
        condition_select.select_by_value('Good')

        tire_dropdown = self.driver.find_element(By.ID, "TIRE_CONDITION")
        tire_select = Select(tire_dropdown)
        tire_select.select_by_value('Good To Go')

        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[5]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[6]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[7]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[8]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[9]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[10]/div[1]/div[1]/div[1]/label[2]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[11]/div[1]/div[1]/div[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[12]/button[1]/div[1]").click()

    # def test_cargurus_36b86ab8(self):
    #     # self.driver.get("https://www.cargurus.com/")
    #     self.driver.find_element(By.XPATH, "//div[@id='heroSearch-tab-content-0']/section[1]/form[1]/section[1]/fieldset[1]/section[2]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='smcVinPlateField' and @type='text' and @placeholder='(EX.) C4R6URU5226123456']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='smcVinPlateField' and @type='text' and @placeholder='(EX.) C4R6URU5226123456']").send_keys("1HGCM66543A064159")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.ID, "postalCode").clear()
    #     self.driver.find_element(By.ID, "postalCode").send_keys("49102")
    #     self.driver.find_element(By.XPATH, "//section[@id='location']/div[1]/div[1]/form[1]/div[2]/button[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "mileage").clear()
    #     self.driver.find_element(By.ID, "mileage").send_keys("155000")
    #     self.driver.find_element(By.XPATH, "//section[@id='car-details']/div[1]/div[1]/form[1]/button[2]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='car-features']/div[1]/div[1]/form[1]/fieldset[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='car-features']/div[1]/div[1]/form[1]/div[1]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/label[3]").click()
    #     self.driver.find_element(By.ID, "CONDITION").clear()
    #     self.driver.find_element(By.ID, "CONDITION").select("Good")
    #     self.driver.find_element(By.ID, "TIRE_CONDITION").clear()
    #     self.driver.find_element(By.ID, "TIRE_CONDITION").select("Good To Go")
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[4]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[5]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[6]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[7]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[8]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[9]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[10]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[11]/div[1]/div[1]/div[1]/label[2]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[12]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//section[@id='condition']/div[1]/div[1]/form[1]/div[13]/button[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//main[@id='root']/div[1]/div[2]/div[1]/form[1]/button[1]/div[1]").click()
    