import pytest
from selenium.webdriver import Keys
from selenium.webdriver.common.by import By

from browser_helper import get_control_key


@pytest.mark.usefixtures("setup_class")
class TestZocdoc:
    
    # def test_zocdoc_451c96a3(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("Cardiologits")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("96162")
    #     self.driver.find_element(By.XPATH, "//div[@value='Truckee, CA 96162']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/label[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Dr. Parham Zarrini, MD, MBA, FACC')]").click()
    #
    # def test_zocdoc_5c2cf2a0(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("chiropractor")
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("90028")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Insurance carrier and plan']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Insurance carrier and plan']").send_keys("medicare")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/ol[1]/li[1]/div[1]/span[1]/em[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit' and @title='Search for doctors']").click()
    #
    # def test_zocdoc_9fafad6c(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("psychologist")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit' and @title='Search for doctors']").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[2]/div[1]/label[2]/div[1]/div[1]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    #
    # def test_zocdoc_b81ab2b4(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/section[1]/div[1]/div[4]/a[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='Near me']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='Near me']").send_keys("Log Angeles")
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/mark[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='choose insurance' and @type='text' and @placeholder='insurance carrier and plan']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[3]/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[4]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='on' and @type='checkbox']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[3]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/label[2]/div[1]/div[1]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[2]/div[1]/label[3]/div[1]/div[1]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/section[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/a[2]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'8:30 am')]").click()
    #     self.driver.find_element(By.ID, "modal-primary-button").click()
    #
    # def test_zocdoc_db2da0d7(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("Vineet Sandhu")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[8]/div[2]/div[1]/span[1]/em[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@role='gridcell']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='profile-booking-section']/div[1]/div[1]/span[1]/div[1]/div[2]/div[1]/div[5]/button[1]").click()
    #     self.driver.find_element(By.ID, "BookApptButton").click()
    
    def test_zocdoc_73178018(self):
        # self.driver.get("https://zocdoc.com")
        self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("chi")

        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='combined-specialty-procedure-item-0']").click()

        # self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
        # self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("new york")
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/mark[1]").click()
        self.driver.find_element(By.ID, "location-picker-input").send_keys(get_control_key() + "a")
        self.driver.find_element(By.ID, "location-picker-input").send_keys(Keys.DELETE)
        self.driver.find_element(By.NAME, "location-picker-input").send_keys("new york")
        self.driver.find_element(By.XPATH, "//div[@data-test='location-picker-option-0']").click()

        # add extra search step
        self.driver.find_element(By.XPATH, "//button[@data-test='search-bar-search-button' and @title='Search for doctors']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/fieldset[1]/div[1]/div[2]/div[1]/label[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[2]/button[2]").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='search-filters-availability-facet' and @role='button']").click()
        self.driver.find_element(By.XPATH, "//label[@for='radio-timeframe2' and @data-test='radio-button-label']").click()
        self.driver.find_element(By.XPATH, "//button[@data-test='availability-picker-dropdown-done']").click()

        # self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Insurance carrier and plan']").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[471]/div[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ol[1]/li[2]/div[1]/span[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//p[@data-test='selected-insurance-state-name-v2']").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='insurance-picker-row-v2-all-carrier-883']").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='insurance-picker-row-v2-all-plan-8651']").click()


        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[2]/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='facet-chip-button' and text()='In-person/video']").click()
        self.driver.find_element(By.ID, "in_person").click()
        self.driver.find_element(By.XPATH, "//button[@data-test='overlay-primary-button']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/label[3]/label[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='facet-chip-button' and text()='Distance']").click()
        self.driver.find_element(By.ID, "to_5_mile").click()
        self.driver.find_element(By.XPATH, "//button[@data-test='overlay-primary-button']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/label[1]/div[1]/div[1]/div[1]/label[1]/input[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]/div[2]/div[1]/label[10]/div[1]/div[1]/div[1]/label[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@data-test='facet-chip-button' and text()='More filters']").click()
        self.driver.find_element(By.XPATH, "//label[@for='male']").click()
        self.driver.find_element(By.XPATH, "//div[./div[text()='Languages spoken']]//button[text()='See more']").click()
        self.driver.find_element(By.XPATH, "//span[text()='Gujarati']").click()

        self.driver.find_element(By.XPATH, "//button[@data-test='overlay-primary-button']").click()
    
    # def test_zocdoc_7db514df(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("Theresa Meotti")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[8]/div[2]/div[1]/span[1]/em[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Reviews')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='reviews-target-element']/section[1]/div[3]/div[1]/div[51]/span[1]/button[1]").click()
    #
    # def test_zocdoc_6e8d48e2(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("dermatologist")
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("90028")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/div[2]/div[1]/label[1]/div[1]/div[1]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    #
    # def test_zocdoc_f47f2982(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("kidney stone")
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("miami")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/mark[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='Choose insurance' and @type='text' and @placeholder='Insurance carrier and plan']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[3]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/label[14]/div[1]/div[1]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/section[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[7]/div[1]/a[1]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[2]/div[1]/div[1]").click()
    #
    # def test_zocdoc_150ccccc(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("optometrist")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]/em[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/label[3]/div[1]/div[1]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    #
    # def test_zocdoc_15486e7c(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("Dermatologist")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]/em[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/label[1]/div[1]/div[1]/div[1]/label[1]/span[1]/span[1]/span[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Dr. Tatyana Groysman, DO')]").click()
    #
    # def test_zocdoc_19f68ca7(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("eye")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("07055")
    #     self.driver.find_element(By.XPATH, "//div[@value='Passaic, NJ 07055']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[3]/div[2]/div[1]/div[4]/div[1]/label[1]/input[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@value='Date' and @type='button']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/div[9]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit' and @title='Search for doctors']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/label[1]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
    #
    # def test_zocdoc_2c1393af(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("couples therapy")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]/em[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("brooklyn")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/mark[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='Choose insurance' and @type='text' and @placeholder='Insurance carrier and plan']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/ol[1]/li[6]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ol[1]/li[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]/path[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/label[2]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[3]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/label[1]/div[1]/div[1]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal-root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/section[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/a[1]/div[1]/div[2]").click()
    #
    # def test_zocdoc_7e2c11bf(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("Orthopedic Surgeon")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/span[1]/em[1]/b[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='City, state, or zip code']").send_keys("10001")
    #     self.driver.find_element(By.XPATH, "//div[@value='New York, NY 10001']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Insurance carrier and plan']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/ol[1]/li[3]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[7]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/div[134]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit' and @title='Search for doctors']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/fieldset[1]/div[1]/div[2]/div[1]").click()
    #
    # def test_zocdoc_7e85e6a2(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='patient-powered-search-input' and @value='' and @type='text' and @placeholder='Condition, procedure, doctor...']").send_keys("dentist")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/section[1]/div[1]/div[1]/div[1]/form[1]/div[1]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[3]/div[1]/div[1]/div[2]/div[1]/fieldset[1]/div[1]/div[3]/label[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/div[2]/div[3]/div[2]/div[1]/button[1]").click()
    #
    # def test_zocdoc_90314b88(self):
    #     # self.driver.get("https://zocdoc.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/section[1]/div[1]/div[2]/a[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='Near me']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='location-picker-input' and @value='' and @type='text' and @placeholder='Near me']").send_keys("Texas city")
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/mark[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='choose insurance' and @type='text' and @placeholder='insurance carrier and plan']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[3]/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/ol[1]/li[3]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[3]/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/ol[1]/li[3]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='header']/header[1]/section[1]/div[2]/div[1]/div[3]/section[1]/div[1]/form[1]/div[4]/button[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[1]/fieldset[1]/div[1]/div[1]/label[2]/label[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/section[1]/section[1]/div[4]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/main[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/section[1]/article[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/a[2]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'2:30 pm')]").click()
    