import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestExpedia:
    
    def test_expedia_88475d27(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.ID, "location-field-destination").clear()
        self.driver.find_element(By.ID, "location-field-destination").send_keys("Orlando")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[1]/div[2]/div[1]/button[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[2]/td[6]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.XPATH, "/html").click()
        self.driver.find_element(By.ID, "lodging-VACATION_HOME-88y").click()
        self.driver.find_element(By.XPATH, "//div[@id='app-layer-base']/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[2]/section[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/figure[1]/span[1]/div[1]/div[1]/div[2]/figure[1]/button[1]").click()
    
    def test_expedia_1337eca1(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='wizardMainRegionV2']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[5]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "location-field-location").clear()
        self.driver.find_element(By.ID, "location-field-location").send_keys("singapore")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-location-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-lx-pwa-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-lx-pwa-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-lx-pwa-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.ID, "cb-freeCancellation-categories").click()
        self.driver.find_element(By.ID, "cb-FamilyFriendly-categories").click()
    
    def test_expedia_5ea9ec16(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='wizardMainRegionV2']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/div[1]/div[1]/div[1]/button[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/div[1]/div[1]/div[1]/button[1]").send_keys("Los Angeles, CA")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/div[1]/div[1]/div[1]/button[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/div[1]/div[1]/div[1]/button[1]").send_keys("Miami, FL")
        self.driver.find_element(By.ID, "location-field-leg1-destination").clear()
        self.driver.find_element(By.ID, "location-field-leg1-destination").send_keys("Miami, FL")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[1]/div[1]/div[1]/button[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-roundtrip']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-roundtrip']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-roundtrip']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-roundtrip']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[2]/td[6]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-roundtrip']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    
    def test_expedia_56cfe20a(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='wizardMainRegionV2']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-locn-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-locn").clear()
        self.driver.find_element(By.ID, "location-field-locn").send_keys("jfk")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-locn-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-loc2-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-loc2").clear()
        self.driver.find_element(By.ID, "location-field-loc2").send_keys("jfk")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-loc2-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[5]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[2]/div[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[2]/div[1]/select[1]").select("9 00 am")
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[3]/div[1]/select[1]").clear()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[3]/div[1]/select[1]").select("6 00 pm")
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.ID, "TWO_TO_FIVE").click()
        self.driver.find_element(By.ID, "luxury").click()
        self.driver.find_element(By.ID, "cars-sort-dropdown").clear()
        self.driver.find_element(By.ID, "cars-sort-dropdown").select("Total Price")
    
    def test_expedia_3c098275(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='wizardMainRegionV2']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/span[1]").click()
        self.driver.find_element(By.ID, "location-field-locn").clear()
        self.driver.find_element(By.ID, "location-field-locn").send_keys("San Francisco")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-locn-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[2]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[7]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Rental-cars-transportation']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.ID, "ZI").click()
        self.driver.find_element(By.ID, "economy").click()
    
    def test_expedia_5307bed6(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-destination").clear()
        self.driver.find_element(By.ID, "location-field-destination").send_keys("national university of singapore")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[5]/button[1]").click()
        self.driver.find_element(By.XPATH, "//form[@id='wizard-hotel-pwa-v2-1']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[1]/div[2]/div[1]/button[1]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.ID, "lodging-HOTEL-o3l").click()
        self.driver.find_element(By.ID, "price-secondary").click()
        self.driver.find_element(By.ID, "sort-filter-dropdown-sort").clear()
        self.driver.find_element(By.ID, "sort-filter-dropdown-sort").select("Distance from landmark")
    
    def test_expedia_97e3f951(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='wizardMainRegionV2']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='uitk-tabs-button-container']/div[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[1]/div[1]/div[1]/button[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[1]/div[2]/div[1]/button[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[2]/section[1]/div[1]/div[4]/div[1]/button[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.ID, "child-age-input-0-0").clear()
        self.driver.find_element(By.ID, "child-age-input-0-0").select("4")
        self.driver.find_element(By.ID, "infant-age-input-0-0").clear()
        self.driver.find_element(By.ID, "infant-age-input-0-0").select("Under 1")
        self.driver.find_element(By.XPATH, "//div[@id='adaptive-menu']/div[1]/div[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.ID, "preferred-class-input-trigger").click()
        self.driver.find_element(By.XPATH, "//div[@id='preferred-class-input']/div[1]/div[1]/a[4]/span[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-oneway']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[7]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-oneway']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-leg1-origin").clear()
        self.driver.find_element(By.ID, "location-field-leg1-origin").send_keys("jfk")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-leg1-destination").clear()
        self.driver.find_element(By.ID, "location-field-leg1-destination").send_keys("heathrow")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    
    def test_expedia_8fb78266(self):
        # self.driver.get("https://expedia.com")
        self.driver.find_element(By.XPATH, "//div[@id='wizardMainRegionV2']/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/a[1]").click()
        self.driver.find_element(By.XPATH, "//ul[@id='uitk-tabs-button-container']/div[1]/li[2]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-leg1-origin").clear()
        self.driver.find_element(By.ID, "location-field-leg1-origin").send_keys("jfk")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-origin-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "location-field-leg1-destination").clear()
        self.driver.find_element(By.ID, "location-field-leg1-destination").send_keys("changi")
        self.driver.find_element(By.XPATH, "//div[@id='location-field-leg1-destination-menu']/section[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "d1-btn").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-oneway']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[3]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='wizard-flight-tab-oneway']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
        self.driver.find_element(By.ID, "NUM_OF_STOPS-0-tpr").click()
        self.driver.find_element(By.ID, "NUM_OF_STOPS-1-o82").click()
        self.driver.find_element(By.ID, "SEAT_CHOICE-SEAT_CHOICE-6br").click()
        self.driver.find_element(By.ID, "NO_CANCEL_FEE-NO_CANCEL_FEE-tuv").click()
        self.driver.find_element(By.ID, "sort-filter-dropdown-SORT").clear()
        self.driver.find_element(By.ID, "sort-filter-dropdown-SORT").select("Price (Lowest)")
    