import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


@pytest.mark.usefixtures("setup_class")
class TestBestbuy:
    
    def test_bestbuy_a59beab6(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("watch")
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-1993527']/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]/form[1]/button[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.ID, "features_facet-Water-Resistant-0").click()
        self.driver.find_element(By.ID, "features_facet-Touch-Screen-4").click()
        self.driver.find_element(By.ID, "colorcat_facet-Silver-0").click()
        self.driver.find_element(By.ID, "currentoffers_facet-On-Sale-0").click()
        self.driver.find_element(By.ID, "voiceassistant_facet-Google-Assistant-2").click()
    
    def test_bestbuy_c2739db1(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-60621330']/div[1]/div[1]/header[1]/div[2]/nav[1]/div[1]/div[1]/button[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Health & Wellness')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='widget-aa40c4d2-53b4-42b1-be73-ec52ad567293']/div[1]/div[3]/div[1]/a[1]/div[1]/img[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='widget-949fd36e-9e37-46ea-b534-015fb8bed1bc']/div[1]/div[2]/div[1]/div[7]/div[1]/a[1]").click()
        self.driver.find_element(By.ID, "brand_facet-NordicTrack-7").click()
        self.driver.find_element(By.ID, "sort-by-select").clear()
        self.driver.find_element(By.ID, "sort-by-select").select("Price Low to High")
    
    def test_bestbuy_cd5753f3(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-87265919']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-87265919']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[8]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-87265919']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[4]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gaming Monitors')]").click()
        self.driver.find_element(By.ID, "screenrefreshrate_facet-240Hz-2").click()
        self.driver.find_element(By.ID, "monitorscreensizerange_facet-33\"-49\"-2").click()
        self.driver.find_element(By.ID, "min-currentprice_facet-input").clear()
        self.driver.find_element(By.ID, "min-currentprice_facet-input").send_keys("500")
        self.driver.find_element(By.ID, "max-currentprice_facet-input").clear()
        self.driver.find_element(By.ID, "max-currentprice_facet-input").send_keys("1200")
        self.driver.find_element(By.ID, "currentprice_facet-$1250-$1499.99-0").click()
        self.driver.find_element(By.ID, "currentprice_facet-$1500-$1999.99-1").click()
        self.driver.find_element(By.ID, "currentprice_facet-$1250-$1499.99-0").click()
    
    def test_bestbuy_d7f01fd5(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("Samsung TV")
        self.driver.find_element(By.XPATH, "//div[@id='suggestViewClientComponent']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/span[1]/span[1]").click()
        self.driver.find_element(By.ID, "verticalresolution_facet-8K-(4320p)-3").click()
        self.driver.find_element(By.ID, "condition_facet-Open-Box-1").click()
    
    def test_bestbuy_f36b49c8(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.ID, "cardoccasion_facet-Birthday-1").click()
        self.driver.find_element(By.ID, "giftcardformat_facet-Physical-0").click()
        self.driver.find_element(By.ID, "customerreviews_facet-Top-Rated-0").click()
        self.driver.find_element(By.XPATH, "//div[@id='fulfillment-add-to-cart-button-14313598']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "quantity-hz7vsy0faju5-43qpbz6t74ynt").clear()
        self.driver.find_element(By.ID, "quantity-hz7vsy0faju5-43qpbz6t74ynt").select("2")
    
    def test_bestbuy_f5b9e5b9(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Careers')]").click()
        self.driver.find_element(By.ID, "job-location-search").clear()
        self.driver.find_element(By.ID, "job-location-search").send_keys("20001")
        self.driver.find_element(By.XPATH, "//div[@id='x3f667e3b1bb6c1105a1e10a41a4bcb89']/section[1]/div[1]/form[1]/div[1]/div[3]/button[1]").click()
        self.driver.find_element(By.ID, "radius-distance-select").clear()
        self.driver.find_element(By.ID, "radius-distance-select").select("Within 5 miles")
        self.driver.find_element(By.ID, "job-text-search").clear()
        self.driver.find_element(By.ID, "job-text-search").send_keys("Retail sales associate")
        self.driver.find_element(By.XPATH, "//div[@id='all_jobs_search']/div[1]/div[1]/form[1]/div[1]/div[4]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[@id='job-list-item-0']/div[1]/div[1]/h4[1]").click()
        self.driver.find_element(By.XPATH, "//a[@title='Apply for Retail Sales Associate']").click()
    
    def test_bestbuy_ff8cc274(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("cooktop")
        self.driver.find_element(By.XPATH, "//div[@id='suggestViewClientComponent']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[4]/a[1]/span[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='main-filters']/div[3]/div[2]/section[1]/fieldset[1]/ul[1]/li[8]/button[1]").click()
        self.driver.find_element(By.ID, "standardizedwidth_facet-30-inches-8").click()
        self.driver.find_element(By.ID, "sort-by-select").clear()
        self.driver.find_element(By.ID, "sort-by-select").select("Price Low to High")
        self.driver.find_element(By.ID, "fueltype_facet-Electric-0").click()
        self.driver.find_element(By.ID, "features_facet-Induction-0").click()
        self.driver.find_element(By.ID, "features_facet-Hot-Surface-Indicator(s)-2").click()
        self.driver.find_element(By.ID, "features_facet-Digital-Display-5").click()
        self.driver.find_element(By.ID, "features_facet-Auto-Shut-Off-3").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-save-for-later-97048560']/div[1]/button[1]").click()
    
    def test_bestbuy_8e1f66f2(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//div[@id='lt-container']/div[1]/div[1]/span[1]/span[1]/button[1]/span[2]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Find Another Store')]").click()
        self.driver.find_element(By.ID, "input-<csi:text><csi:vars>$(csi.instances.shop.location-zip-code-form.v1.id)</csi:vars></csi:text>").clear()
        self.driver.find_element(By.ID, "input-<csi:text><csi:vars>$(csi.instances.shop.location-zip-code-form.v1.id)</csi:vars></csi:text>").send_keys("30010")
        self.driver.find_element(By.XPATH, "//div[@id='shop-location-zip-code-form-75334480']/div[1]/div[1]/div[1]/form[1]/fieldset[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='location-filter-search-form-content-l']/div[2]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'apple imacs')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-location-list-73870182']/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "service-checkbox-Apple Authorized Service Provider").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-location-list-73870182']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/fieldset[1]/div[2]/div[1]/button[3]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-location-card-61816593']/div[1]/div[3]/button[1]").click()
    
    def test_bestbuy_9aec1bbb(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-31186471']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/button[1]/svg[1]/path[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-31186471']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[8]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-31186471']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Laptops')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='widget-8c4015d3-c719-4dbd-9b5c-75c11556c894']/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]").click()
        self.driver.find_element(By.ID, "systemmemoryram_facet-12-gigabytes-4").click()
        self.driver.find_element(By.ID, "brand_facet-HP-0").click()
        self.driver.find_element(By.ID, "parent_processormodelsv_facet-Intel-Core-i7-1").click()
        self.driver.find_element(By.XPATH, "//div[@id='nested-parent_operatingsystem_facet-Windows-0']/button[1]/span[2]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'1920 x 1080 (Full HD)')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-sku-list-item-23155010']/div[1]/div[1]/div[1]/a[1]/img[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-specifications-51739327']/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
    
    def test_bestbuy_a3af3bcb(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.ID, "currentprice_facet-$100-$149.99-4").click()
        self.driver.find_element(By.ID, "cardoccasion_facet-Birthday-1").click()
        self.driver.find_element(By.XPATH, "//div[@id='fulfillment-add-to-cart-button-91888996']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cartApp']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[4]/div[1]/div[1]/button[1]").click()
    
    def test_bestbuy_39d1c8cf(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("Iphone 13")
        self.driver.find_element(By.XPATH, "//div[@id='suggestViewClientComponent']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-sku-list-item-19635668']/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/ul[1]/li[3]/div[1]/a[1]/div[1]/img[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'See Details')]").click()
        self.driver.find_element(By.XPATH, "//button[@id='variation-dropdown-Cell_Phones_Internal_Memory']/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[@id='variations-dropdown-item-Cell_Phones_Internal_Memory-256GB']/span[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='variation-dropdown-Cell_Phones_Carrier']/span[1]/span[1]/img[1]").click()
        self.driver.find_element(By.ID, "warranty-sku-6480417-warranty-selector").click()
        self.driver.find_element(By.XPATH, "//div[@id='fulfillment-add-to-cart-button-17898859']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='transaction-types-container']/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='transaction-types-container']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/fieldset[1]/div[1]/label[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='transaction-types-container']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='transaction-types-container']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/fieldset[1]/div[2]/label[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='transaction-types-container']/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/button[1]").click()
        self.driver.find_element(By.ID, "cnxfta_credit-consent-checkbox").click()
        self.driver.find_element(By.XPATH, "//main[@id='package-builder-container']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/button[1]/span[1]").click()
    
    def test_bestbuy_3ff2ddd8(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("speaker")
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-53006057']/div[1]/div[1]/header[1]/div[1]/div[1]/div[1]/div[1]/form[1]/button[2]/span[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Bluetooth & Wireless Speakers')]").click()
        self.driver.find_element(By.ID, "currentprice_facet-$25-$49.99-1").click()
        self.driver.find_element(By.ID, "currentprice_facet-Less-than-$25-0").click()
        self.driver.find_element(By.ID, "currentoffers_facet-On-Sale-0").click()
    
    def test_bestbuy_6807ef3b(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Trade-In Program')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='product-families-container']/div[1]/section[1]/div[1]/div[1]/div[4]/div[1]/center[1]/div[1]/div[1]/div[1]/img[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/div[1]/section[1]/div[1]/section[1]/form[1]/fieldset[1]/div[1]/div[1]/div[2]/div[1]/div[4]/div[1]/div[27]/div[1]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/div[1]/section[1]/div[1]/section[1]/form[1]/fieldset[1]/div[2]/div[1]/div[2]/div[1]/div[4]/div[1]/div[15]/div[1]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/div[1]/section[1]/div[1]/section[1]/form[1]/fieldset[1]/div[3]/div[1]/div[2]/div[1]/div[4]/div[1]/div[9]/div[1]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/div[1]/section[1]/div[1]/section[1]/form[1]/fieldset[1]/div[4]/div[1]/div[2]/div[1]/div[4]/div[1]/div[9]/div[1]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/div[1]/section[1]/div[1]/section[1]/form[1]/fieldset[1]/div[5]/div[1]/div[1]/div[2]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/form[1]/fieldset[1]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[2]/div[1]/div[1]/div[7]/div[2]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/form[1]/fieldset[1]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='body-container']/section[1]/form[1]/fieldset[1]/div[2]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]/center[1]/div[2]").click()
        self.driver.find_element(By.XPATH, "//div[@id='appraisal-links']/div[4]/div[2]/div[1]").click()
        self.driver.find_element(By.ID, "tradeinTypeRadioInStore").click()
        self.driver.find_element(By.ID, "inStoreCartButton").click()
    
    def test_bestbuy_6b67e246(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("ssd")
        self.driver.find_element(By.XPATH, "//div[@id='suggestViewClientComponent']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[3]/a[1]/span[1]/span[2]").click()
        self.driver.find_element(By.ID, "brand_facet-Samsung-0").click()
        self.driver.find_element(By.ID, "formfactormv_facet-M.2-1").click()
        self.driver.find_element(By.ID, "condition_facet-New-0").click()
        self.driver.find_element(By.ID, "min-currentprice_facet-input").clear()
        self.driver.find_element(By.ID, "min-currentprice_facet-input").send_keys("25")
        self.driver.find_element(By.ID, "max-currentprice_facet-input").clear()
        self.driver.find_element(By.ID, "max-currentprice_facet-input").send_keys("200")
        self.driver.find_element(By.XPATH, "//div[@id='main-filters']/div[3]/div[3]/section[8]/fieldset[1]/div[1]/button[1]/svg[1]").click()
    
    def test_bestbuy_7e6deaae(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-3732446']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='shop-header-3732446']/div[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/div[1]/div[1]/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Schedule a Service')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='GAMING']/div[1]/p[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='I_NEED_A_REPAIR']/div[1]/h3[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='storesNearLocation']/ul[1]/li[2]/button[1]").click()
        self.driver.find_element(By.ID, "location").clear()
        self.driver.find_element(By.ID, "location").send_keys("10001")
        self.driver.find_element(By.XPATH, "//div[@id='storesNearLocation']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/form[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//main[@id='triage-app']/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//button[@id='c-calendar-date-1679616000000']/span[1]").click()
        self.driver.find_element(By.ID, "timeSelect1028").clear()
        self.driver.find_element(By.ID, "timeSelect1028").select("6 20 p.m. – 6 40 p.m. (EDT)")
        self.driver.find_element(By.XPATH, "//main[@id='triage-app']/div[2]/div[1]/div[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/div[1]/div[2]/button[1]").click()
    
    def test_bestbuy_84c1847c(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.ID, "gh-search-input").clear()
        self.driver.find_element(By.ID, "gh-search-input").send_keys("S21 PLUS")
        self.driver.find_element(By.XPATH, "//div[@id='suggestViewClientComponent']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/a[1]/span[1]/span[1]").click()
        self.driver.find_element(By.ID, "condition_facet-Open-Box-3").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Shop Open-Box')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='fulfillment-add-to-cart-button-54872098']/div[1]/div[1]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Go to Cart')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cartApp']/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='cartApp']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/section[1]/div[4]/ul[1]/li[1]/section[1]/div[3]/div[1]/ul[1]/li[1]/div[1]/div[3]/button[1]/span[1]").click()
        self.driver.find_element(By.ID, "brand").clear()
        self.driver.find_element(By.ID, "brand").select("Samsung")
        self.driver.find_element(By.ID, "modelFamily").clear()
        self.driver.find_element(By.ID, "modelFamily").select("Samsung Galaxy S20 5G")
        self.driver.find_element(By.ID, "color").clear()
        self.driver.find_element(By.ID, "color").select("Cosmic Gray")
        self.driver.find_element(By.ID, "carrier").clear()
        self.driver.find_element(By.ID, "carrier").select("Verizon")
        self.driver.find_element(By.XPATH, "//div[@id='undefined']/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/form[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='trade-results']/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.ID, "crackedscreen-mob-1 - No").click()
        self.driver.find_element(By.ID, "cellphone-condition2 - Good").click()
        self.driver.find_element(By.XPATH, "//div[@id='mocked-modal-styles']/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[3]/fieldset[1]/div[1]/div[1]/label[1]/span[1]").click()
    
    def test_bestbuy_47efde90(self):
        # self.driver.get("https://www.bestbuy.com/")
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Specialty Gift Cards')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Travel gift cards')]").click()
        self.driver.find_element(By.XPATH, "//div[@id='fulfillment-add-to-cart-button-27410931']/div[1]/div[1]/div[1]/button[1]").click()
    