import time

import pytest
from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select

from browser_helper import scroll_down


@pytest.mark.usefixtures("setup_class")
class TestStudent:
    
    # def test_student_2eb185df(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("chicago")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[2]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "select-box-1-2").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[1]/div[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[4]/div[1]/ul[1]/li[2]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[4]/div[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
    #
    # def test_student_7b8fa61f(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[2]/span[2]/span[1]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[1]/ul[1]/li[9]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[1]/ul[1]/li[10]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[3]/button[1]").click()
    #
    # def test_student_8a73fe1b(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("GLASSGOW")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[1]/div[1]/label[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[5]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[6]/div[1]/label[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[4]/div[1]/ul[1]/li[3]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]").click()
    #
    # def test_student_1f577a8d(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("london business school")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='max-price' and @value='4158' and @type='number' and @placeholder='4158']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='max-price' and @value='4158' and @type='number' and @placeholder='4158']").send_keys("300")
    #     self.driver.find_element(By.XPATH, "//input[@name='min-price' and @value='194' and @type='number' and @placeholder='194']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='min-price' and @value='194' and @type='number' and @placeholder='194']").send_keys("100")
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    #
    # def test_student_f24a6c7c(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("Aston University")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[3]/button[1]").click()
    #
    # def test_student_5be47163(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("San Diego")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[2]/div[2]/div[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[1]/div[3]/section[1]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Fifty Twenty-Five')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[1]/div[3]/section[1]/div[1]/div[1]/svg[1]").click()
    #
    # def test_student_5d98c7b7(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/div[1]/div[1]").clear()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/div[1]/div[1]").send_keys("UCLA")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[5]/div[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[3]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    #
    # def test_student_82d5f6bd(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("Michigan")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[7]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/span[3]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='13853']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='13852']/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[10]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[10]/div[2]/div[1]/div[5]/button[1]").click()
    #
    # def test_student_77be5a4d(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[3]/section[1]/div[1]/ul[1]/li[6]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[4]/div[1]/ul[1]/li[2]/a[1]/span[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/span[3]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/span[3]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[2]/span[3]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'true Liverpool')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='102929']/div[1]/div[1]/div[2]/span[1]").click()
    #
    # def test_student_486706b0(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("SYDNEY")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "react-select-university-filter-option-5").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[1]/ul[1]/li[9]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[2]/div[1]/ul[1]/li[3]/div[1]/label[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[5]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
    #
    # def test_student_e3b3e9b0(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/span[2]/span[6]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='select-box-1-0']/span[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "react-select-university-filter-option-2").click()
    #
    # def test_student_ec4674d2(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//span[@role='presentation']").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Group Booking')]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='groupSize' and @value='' and @placeholder='Select group size']").click()
    #     self.driver.find_element(By.XPATH, "//li[@value='FIVE_TO_TEN']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='city' and @value='' and @placeholder='Search destination city']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='city' and @value='' and @placeholder='Search destination city']").send_keys("Washington")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[1]/ul[1]/li[3]/div[1]/div[1]/ul[1]/div[1]/li[1]/p[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='moveInDate' and @value='' and @type='text' and @placeholder='Desired move-in date']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[1]/ul[1]/li[6]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[3]/div[4]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='moveOutDate' and @value='' and @type='text' and @placeholder='Desired move-out date']").click()
    #     self.driver.find_element(By.XPATH, "//select[@name='month']").clear()
    #     self.driver.find_element(By.XPATH, "//select[@name='month']").select("Oct")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[1]/ul[1]/li[7]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[5]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='budgetEndValue' and @value='' and @type='text' and @placeholder='e.g. 300']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='budgetEndValue' and @value='' and @type='text' and @placeholder='e.g. 300']").send_keys("1200")
    #     self.driver.find_element(By.XPATH, "//input[@name='budgetSelectTime' and @value='Per Week' and @placeholder='']").click()
    #     self.driver.find_element(By.XPATH, "//li[@value='MONTHLY']").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='name' and @value='' and @type='text' and @placeholder='Input your name']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='name' and @value='' and @type='text' and @placeholder='Input your name']").send_keys("James Smith")
    #     self.driver.find_element(By.XPATH, "//input[@name='emailAddress' and @value='' and @type='text' and @placeholder='Input email address']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='emailAddress' and @value='' and @type='text' and @placeholder='Input email address']").send_keys("buckeye.foobar@gmail.com")
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #
    # def test_student_c02b046d(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("bristol")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "react-select-university-filter-option-10").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='max-price' and @value='679' and @type='number' and @placeholder='679']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='max-price' and @value='679' and @type='number' and @placeholder='679']").send_keys("300")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[3]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='140288']/div[1]/div[1]/div[3]/div[1]/div[2]/span[1]/button[1]").click()
    #
    # def test_student_7e5e0ded(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("LIVERPOOL")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "react-select-university-filter-option-7").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='min-price' and @value='82' and @type='number' and @placeholder='82']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='min-price' and @value='82' and @type='number' and @placeholder='82']").send_keys("100")
    #     self.driver.find_element(By.XPATH, "//input[@name='max-price' and @value='1190' and @type='number' and @placeholder='1190']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@name='max-price' and @value='1190' and @type='number' and @placeholder='1190']").send_keys("300")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[1]/div[1]/ul[1]/li[1]/div[1]/label[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
    #
    # def test_student_c54b647c(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("London")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[5]/div[1]/ul[1]/li[3]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[5]/div[1]/ul[1]/li[6]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[2]/div[3]/button[1]").click()
    #
    # def test_student_17a3488c(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[2]/span[2]/span[7]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'826 9th Avenue by June')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[1]/div[3]/section[1]/div[1]/div[1]/svg[1]").click()
    #
    # def test_student_43c8104b(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("University of Oxford")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[2]").click()
    #
    # def test_student_f0e64c18(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("TOKYO")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "react-select-university-filter-option-3").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[1]/ul[1]/li[7]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[1]/ul[1]/li[12]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[1]/div[2]/div[1]/div[2]/div[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/a[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[4]/div[1]/ul[1]/li[1]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[4]/div[1]/ul[1]/li[15]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    
    def test_student_a36836fd(self):
        # self.driver.get("https://student.com")
        # add extra step to navigate to the main website
        self.driver.find_element(By.XPATH, "//span[text()='Oceania']").click()
        self.driver.find_element(By.XPATH, "//a[text()='Sydney']").click()

        # self.driver.find_element(By.XPATH, "//span[@role='presentation']").click()
        self.driver.find_element(By.XPATH, "//span[@role='presentation' and text()='Rentals']").click()

        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Group Booking')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),'Group booking')]").click()

        # add extra step to close potential pop up
        if self.driver.find_element(By.XPATH, "//div[@class='download-banner__close-content' and @role='presentation']") is not None:
            self.driver.find_element(By.XPATH, "//div[@class='download-banner__close-content' and @role='presentation']").click()

        self.driver.find_element(By.XPATH, "//input[@name='groupSize' and @value='' and @placeholder='Select group size']").click()
        self.driver.find_element(By.XPATH, "//li[@value='FIVE_TO_TEN']").click()
        self.driver.find_element(By.XPATH, "//input[@name='preciseGroupSize' and @value='' and @type='text' and @placeholder='Input precise group size']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='preciseGroupSize' and @value='' and @type='text' and @placeholder='Input precise group size']").send_keys("10")
        self.driver.find_element(By.XPATH, "//input[@name='city' and @value='' and @placeholder='Search destination city']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='city' and @value='' and @placeholder='Search destination city']").send_keys("sydney")
        self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[1]/ul[1]/li[3]/div[1]/div[1]/ul[1]/div[2]/li[1]/p[1]").click()
        self.driver.find_element(By.XPATH, "//input[@name='university' and @value='' and @placeholder='Input destination university']").click()
        self.driver.find_element(By.XPATH, "//li[@value='17']").click()
        self.driver.find_element(By.XPATH, "//input[@name='interestedProperty' and @value='' and @type='text' and @placeholder='Input Interested Property']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='interestedProperty' and @value='' and @type='text' and @placeholder='Input Interested Property']").send_keys("apartment")

        scroll_down(self.driver, 500)
        self.driver.find_element(By.XPATH, "//input[@name='moveInDate' and @value='' and @type='text' and @placeholder='Desired move-in date']").click()
        # self.driver.find_element(By.XPATH, "//select[@name='month']").clear()
        # self.driver.find_element(By.XPATH, "//select[@name='month']").select("Apr")
        # self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[1]/ul[1]/li[6]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[7]").click()
        # click on the calendar first so that the elements in the calendar are clickable, ignored the long relative xpath here since it mainly related to the input
        self.driver.find_element(By.XPATH, "//select[@name='year']").click()
        move_in_year_dropdown = self.driver.find_element(By.XPATH, "//select[@name='year']")
        move_in_year_select = Select(move_in_year_dropdown)
        move_in_year_select.select_by_value("2025")
        move_in_month_dropdown = self.driver.find_element(By.XPATH, "//select[@name='month']")
        move_in_month_select = Select(move_in_month_dropdown)
        move_in_month_select.select_by_visible_text("Apr")
        self.driver.find_element(By.XPATH, "//div[@aria-label='Tue Apr 01 2025']").click()

        self.driver.find_element(By.XPATH, "//input[@name='moveOutDate' and @value='' and @type='text' and @placeholder='Desired move-out date']").click()

        # self.driver.find_element(By.XPATH, "//select[@name='year']").clear()
        # self.driver.find_element(By.XPATH, "//select[@name='year']").select("2024")
        # self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[1]/ul[1]/li[7]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/div[5]/div[7]").click()
        self.driver.find_element(By.XPATH, "//select[@name='year']").click()
        move_out_year_dropdown = self.driver.find_element(By.XPATH, "//select[@name='year']")
        move_out_year_select = Select(move_out_year_dropdown)
        move_out_year_select.select_by_value("2026")
        move_out_month_dropdown = self.driver.find_element(By.XPATH, "//select[@name='month']")
        move_out_month_select = Select(move_out_month_dropdown)
        move_out_month_select.select_by_value("2")
        self.driver.find_element(By.XPATH, "//div[@aria-label='Tue Mar 31 2026']").click()

        self.driver.find_element(By.XPATH, "//input[@name='budgetStartValue' and @value='' and @type='text' and @placeholder='e.g. 100']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='budgetStartValue' and @value='' and @type='text' and @placeholder='e.g. 100']").send_keys("100")
        self.driver.find_element(By.XPATH, "//input[@name='budgetEndValue' and @value='' and @type='text' and @placeholder='e.g. 300']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='budgetEndValue' and @value='' and @type='text' and @placeholder='e.g. 300']").send_keys("500")
        self.driver.find_element(By.XPATH, "//input[@name='budgetSelectTime' and @value='Per Week' and @placeholder='']").click()
        self.driver.find_element(By.XPATH, "//li[@value='MONTHLY']").click()
        self.driver.find_element(By.XPATH, "//input[@name='name' and @value='' and @type='text' and @placeholder='Input your name']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='name' and @value='' and @type='text' and @placeholder='Input your name']").send_keys("John Brown")
        self.driver.find_element(By.XPATH, "//input[@name='emailAddress' and @value='' and @type='text' and @placeholder='Input email address']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='emailAddress' and @value='' and @type='text' and @placeholder='Input email address']").send_keys("Johnbrown@gmail.com")
        self.driver.find_element(By.XPATH, "//input[@name='phone-input' and @value='' and @type='phone' and @placeholder='Phone number']").clear()
        self.driver.find_element(By.XPATH, "//input[@name='phone-input' and @value='' and @type='phone' and @placeholder='Phone number']").send_keys("3324456543")

        # avoid sending spam data
        # self.driver.find_element(By.XPATH, "//button[@type='button']").click()
    
    # def test_student_952b24e0(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("American University")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[2]/div[3]/div[1]/div[1]/svg[1]").click()
    #
    # def test_student_9b94f5b1(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("Oxford school of english")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[1]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='select-box-1-0']/span[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]").click()
    #
    # def test_student_4946dd68(self):
    #     # self.driver.get("https://student.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='' and @type='text' and @placeholder='Search by college, city or property']").send_keys("leeds")
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/section[1]/div[2]/form[1]/div[1]/div[1]/div[1]/div[2]/span[1]/span[2]/span[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[2]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/ul[1]/li[3]/div[1]/ul[1]/li[6]/div[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[2]/div[1]/div[2]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='select-box-1']/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[2]/div[2]/div[2]/section[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]").click()
    