import time

import pytest
from selenium.webdriver.common.by import By

from browser_helper import switch_to_new_tab, calculate_dates_without_space, switch_to_new_tab_and_close_old, scroll_down


@pytest.mark.usefixtures("setup_class")
class TestUnited:
    
    # def test_united_35c34724(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav0']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav0-panel']/div[1]/div[1]/ul[1]/li[4]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "filterOriginInput").clear()
    #     self.driver.find_element(By.ID, "filterOriginInput").send_keys("las vegas")
    #     self.driver.find_element(By.XPATH, "//li[@id='filterOriginInput-menu-item-0']/button[1]").click()
    #     self.driver.find_element(By.ID, "YZiCZN-Gz").clear()
    #     self.driver.find_element(By.ID, "YZiCZN-Gz").select("Roundtrip")
    #     self.driver.find_element(By.XPATH, "//form[@id='mapSearchForm']/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='flexibleDatesOpt']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='mapSearchForm']/div[2]/div[3]/button[1]/span[1]").click()
    #
    # def test_united_2f14b18e(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='checkInTab']/h2[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "flightCheckInConfNumber").clear()
    #     self.driver.find_element(By.ID, "flightCheckInConfNumber").send_keys("10987654")
    #     self.driver.find_element(By.ID, "flightCheckInLastName").clear()
    #     self.driver.find_element(By.ID, "flightCheckInLastName").send_keys("Lewis")
    #     self.driver.find_element(By.ID, "formSubmitBtn").click()
    #
    # def test_united_c4848d71(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[1]/fieldset[1]/div[1]/label[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[1]/div[1]/label[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("Sacramento")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("Houston")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "DepartDate").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[1]/td[6]/div[1]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    
    def test_united_fdf322bd(self):
        # self.driver.get("https://www.united.com/en/us")
        # self.driver.find_element(By.XPATH, "//a[@id='headerNav0']/span[1]").click()
        self.driver.find_element(By.XPATH, "//button/span[text()='Book']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='headerNav0-panel']/div[1]/div[2]/ul[1]/li[3]/a[1]/span[1]").click()
        self.driver.find_element(By.XPATH, "//a[text()='Vacation packages']").click()
        switch_to_new_tab_and_close_old(self.driver)

        # self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/label[2]/div[1]/svg[1]").click()
        self.driver.find_element(By.XPATH, "//label[@for='Hotel + Flight + Car']").click()

        self.driver.find_element(By.ID, "Where from?").clear()
        self.driver.find_element(By.ID, "Where from?").send_keys("new york")

        # self.driver.find_element(By.XPATH, "//div[@id='Where from?-dropdown-item-0']/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Where from?-dropdown']//div[@id='undefined-item-0']/div[1]/div[1]").click()

        self.driver.find_element(By.ID, "Where to?").clear()
        self.driver.find_element(By.ID, "Where to?").send_keys("las vegas")

        # self.driver.find_element(By.XPATH, "//div[@id='Where to?-dropdown-item-0']/div[1]/div[1]").click()
        self.driver.find_element(By.XPATH, "//div[@id='Where to?-dropdown']//div[@id='undefined-item-0']/div[1]/div[1]").click()

        # self.driver.find_element(By.XPATH, "//input[@value='' and @placeholder='Departing - Returning']").click()
        # self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[17]/div[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[3]/div[25]/div[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/label[2]/div[1]/svg[3]").click()
        self.driver.find_element(By.XPATH, "//div[text()='Departing - Returning']").click()
        start_date_str, end_date_str = calculate_dates_without_space(14, 21)
        self.driver.find_element(By.XPATH, f"//div[@data-autobot-element-id='DATEPICKER_DAY_{start_date_str}']").click()
        self.driver.find_element(By.XPATH, f"//div[@data-autobot-element-id='DATEPICKER_DAY_{end_date_str}']").click()

        # self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/div[2]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[text()='Start Saving']").click()
        switch_to_new_tab_and_close_old(self.driver)

        # self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[1]/div[1]/div[3]/div[2]/div[1]/div[7]/div[1]/div[1]/div[2]/label[1]/div[1]/div[1]/div[1]/svg[3]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[1]/div[1]/div[3]/div[2]/div[1]/div[5]/div[1]/div[1]/div[1]/button[4]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='root']/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]").click()
        # self.driver.find_element(By.XPATH, "/html/body[1]/reach-portal[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[1]/button[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//svg[@role='img' and @title='Increase Rooms']").click()
        # self.driver.find_element(By.XPATH, "//svg[@role='img' and @title='Increase Adults']").click()
        # self.driver.find_element(By.XPATH, "//div[@id='popover-description-traveler-selection-popover']/div[3]/div[1]/div[2]/div[2]/button[2]/div[1]/svg[1]/path[1]").click()
        # self.driver.find_element(By.XPATH, "/html/body[1]/div[5]").click()
        # self.driver.find_element(By.XPATH, "//button[contains(.,'Update Search')]").click()
        # NEED to wait for the content to be fully loaded then click and select rooms and adults otherwise the changes made will be reset after the content is fully loaded.
        # The attachments shows the screenshot of the page that the selections are RESET after page is fully loaded even though it was set to 2 rooms and 4 adults before.
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//div[text()='1 Room, 2 Adults']").click()
        self.driver.find_element(By.XPATH, "//button[@aria-label='Select traveler information']").click()
        self.driver.find_element(By.XPATH, "//button[@aria-label='Increase Rooms']").click()
        self.driver.find_element(By.XPATH, "//button[@aria-label='Increase Adults']").click()
        self.driver.find_element(By.XPATH, "//button[@aria-label='Increase Adults']").click()
        # Use javascript click to force the click since the Done button is now showed in the screen area.
        # self.driver.find_element(By.XPATH, "//div[text()='Done']").click()
        self.driver.execute_script("arguments[0].click()", self.driver.find_element(By.XPATH, "//div[text()='Done']").get_native_element())
        self.driver.find_element(By.XPATH, "//div[text()='Update Search']").click()
        switch_to_new_tab_and_close_old(self.driver)

        # self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[2]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[3]/button[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//a[contains(text(),'Choose Another Hotel')]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='main-wrapper']/div[2]/div[5]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[3]/button[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='name-and-price']/div[2]/div[2]/button[1]/div[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='rates-table-50570']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/button[1]").click()
        # self.driver.find_element(By.XPATH, "//div[@id='listingContent']/div[1]/div[3]/section[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[2]/div[2]/div[1]/button[1]").click()
        self.driver.find_element(By.XPATH, "//div[text()='4 +']").click()
        self.driver.find_element(By.XPATH, "//div[text()='Show 12 more']").click()
        self.driver.find_element(By.XPATH, "//div[contains(@for, 'Amenities-CASINO-checkbox-')]").click()
        self.driver.find_element(By.XPATH, "//button[@data-testid='DROP_DOWN_FIELD_BOX']").click()
        self.driver.find_element(By.XPATH, "//div[text()='Lowest Price']").click()
        self.driver.find_element(By.XPATH, "//div[contains(@class, 'undefined listings')]/div[contains(@class, 'Listings__StyledWrapper')]/div[1]//button[@data-testid='price-choosen-button']").click()
        time.sleep(2)


    # def test_united_5c29c805(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='bookHotelTab']/h3[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookHotelInput").clear()
    #     self.driver.find_element(By.ID, "bookHotelInput").send_keys("Chicago")
    #     self.driver.find_element(By.XPATH, "//li[@id='bookHotelInput-menu-item-0']/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookHotelCheckinDate").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='bookHotelTab-panel']/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[6]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='bookHotelTab-panel']/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[4]/td[1]").click()
    #     self.driver.find_element(By.ID, "bookHotelModel.passengers").click()
    #     self.driver.find_element(By.ID, "Adults plusBtn").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='bookHotelTab-panel']/form[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Price')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Price (low to high)')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Mccormick Place Guest House')]").click()
    #
    # def test_united_e6f6e6c8(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav2']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav2-panel']/div[1]/div[2]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Baggage fee calculator')]").click()
    #
    # def test_united_401c4e6f(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='bookCarTab']/h3[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookCarPickupInput").clear()
    #     self.driver.find_element(By.ID, "bookCarPickupInput").send_keys("Brooklyn Central")
    #     self.driver.find_element(By.XPATH, "//li[@id='bookCarPickupInput-menu-item-0']/button[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "bookCarPickupDate").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookCarForm']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookCarForm']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[7]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_united_112459f9(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='checkInTab']/h2[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "flightCheckInConfNumber").clear()
    #     self.driver.find_element(By.ID, "flightCheckInConfNumber").send_keys("123456")
    #     self.driver.find_element(By.ID, "flightCheckInLastName").clear()
    #     self.driver.find_element(By.ID, "flightCheckInLastName").send_keys("John")
    #     self.driver.find_element(By.ID, "formSubmitBtn").click()
    #
    # def test_united_c9f2258a(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav4']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav4-panel']/div[1]/div[2]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "sfm-origin-638e0c68f2a61e33e76214d2-input").clear()
    #     self.driver.find_element(By.ID, "sfm-origin-638e0c68f2a61e33e76214d2-input").send_keys("New York")
    #     self.driver.find_element(By.ID, "sfm-destination-638e0c68f2a61e33e76214d2-input").clear()
    #     self.driver.find_element(By.ID, "sfm-destination-638e0c68f2a61e33e76214d2-input").send_keys("Honolulu")
    #     self.driver.find_element(By.ID, "downshift-3-item-0").click()
    #     self.driver.find_element(By.ID, "sfm-budget-638e0c68f2a61e33e76214d2-input").clear()
    #     self.driver.find_element(By.ID, "sfm-budget-638e0c68f2a61e33e76214d2-input").send_keys("1300")
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='react-select-2-option-1']/div[1]").click()
    #
    # def test_united_c497534c(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='bookCarTab']/h3[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookCarForm']/div[5]/label[1]").click()
    #     self.driver.find_element(By.ID, "bookCarPickupInput-label").clear()
    #     self.driver.find_element(By.ID, "bookCarPickupInput-label").send_keys("caldwell")
    #     self.driver.find_element(By.XPATH, "//li[@id='bookCarPickupInput-menu-item-0']/button[1]/div[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "bookCarPickupDate").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookCarForm']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[7]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookCarForm']/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[5]").click()
    #     self.driver.find_element(By.ID, "pickupTime").click()
    #     self.driver.find_element(By.ID, "pickupTime").click()
    #     self.driver.find_element(By.ID, "pickupTime_item-4").click()
    #     self.driver.find_element(By.ID, "dropoffTime").click()
    #     self.driver.find_element(By.ID, "dropoffTime_item-20").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_united_3a231c03(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav2']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav2-panel']/div[1]/div[2]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Baggage fee calculator')]").click()
    #     self.driver.find_element(By.ID, "7fl11HABm9").click()
    #     self.driver.find_element(By.ID, "voZU_kaSQ").clear()
    #     self.driver.find_element(By.ID, "voZU_kaSQ").send_keys("10000002")
    #     self.driver.find_element(By.ID, "xXvTCVUWzc").clear()
    #     self.driver.find_element(By.ID, "xXvTCVUWzc").send_keys("Son")
    #     self.driver.find_element(By.XPATH, "//div[@id='my-flights-id-container']/form[1]/div[1]/button[1]/span[1]").click()
    #
    # def test_united_74b456b6(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//section[@id='footerPanel0-panel']/div[1]/div[1]/ul[1]/li[6]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Open Jobs')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[2]/fieldset[1]/ul[1]/li[3]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='CountryAccordion']/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[3]/div[2]/div[3]/div[1]/div[2]/fieldset[1]/ul[1]/li[4]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='State/ProvinceAccordion']/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[3]/div[3]/div[3]/div[1]/div[2]/fieldset[1]/ul[1]/li[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='CityAccordion']/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[3]/div[4]/div[3]/div[1]/div[2]/fieldset[1]/ul[1]/li[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='HiringTypeAccordion']/i[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[1]/div[1]/section[2]/div[1]/div[1]/div[1]/div[3]/div[5]/div[3]/div[1]/div[2]/fieldset[1]/ul[1]/li[1]/label[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "sortselect").clear()
    #     self.driver.find_element(By.ID, "sortselect").select("Most recent")
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[1]/div[2]/section[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/ul[1]/li[6]/div[1]/div[1]/span[1]/a[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='acc-skip-content']/div[2]/div[1]/div[1]/div[2]/section[1]/div[1]/div[1]/div[1]/div[2]/a[1]/ppc-content[1]").click()
    #     self.driver.find_element(By.ID, "email").clear()
    #     self.driver.find_element(By.ID, "email").send_keys("jacksparrow@gmail.com")
    #     self.driver.find_element(By.XPATH, "//input[@value='Continue' and @type='submit']").click()
    #
    # def test_united_7ec95f61(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav2']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav2-panel']/div[1]/div[2]/ul[1]/li[2]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='datesDropdown']/div[1]").click()
    #     self.driver.find_element(By.ID, "datesDropdown_item-4").click()
    #     self.driver.find_element(By.ID, "airlineDropdown").click()
    #     self.driver.find_element(By.XPATH, "//span[@role='group']").click()
    #     self.driver.find_element(By.ID, "originInput").clear()
    #     self.driver.find_element(By.ID, "originInput").send_keys("belo horizonte")
    #     self.driver.find_element(By.XPATH, "//li[@id='originInput-menu-item-0']/button[1]").click()
    #     self.driver.find_element(By.ID, "destinationInput").clear()
    #     self.driver.find_element(By.ID, "destinationInput").send_keys("buenos aires")
    #     self.driver.find_element(By.XPATH, "//li[@id='destinationInput-menu-item-0']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='flightInfoSearchForm']/div[6]/button[1]/span[1]").click()
    #
    # def test_united_4e9d71b9(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav2']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav2-panel']/div[1]/div[2]/ul[1]/li[1]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Baggage fee calculator')]").click()
    #     self.driver.find_element(By.ID, "airport-autocomplete-.from").clear()
    #     self.driver.find_element(By.ID, "airport-autocomplete-.from").send_keys("columbus")
    #     self.driver.find_element(By.XPATH, "//li[@id='airport-autocomplete-.from-menu-item-0']/button[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "airport-autocomplete-.to").clear()
    #     self.driver.find_element(By.ID, "airport-autocomplete-.to").send_keys("new orleans")
    #     self.driver.find_element(By.XPATH, "//li[@id='airport-autocomplete-.to-menu-item-0']/button[1]/div[1]").click()
    #     self.driver.find_element(By.ID, "qDm6eS6y0C").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='SPjF170gi']/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[1]").click()
    #     self.driver.find_element(By.ID, "E2-b7taTyv").clear()
    #     self.driver.find_element(By.ID, "E2-b7taTyv").select("Business or First")
    #     self.driver.find_element(By.XPATH, "//button[@id='anyFlightFormSubmit']/span[1]").click()
    #
    # def test_united_59bdd427(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("Santa Fe")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("Phoenix")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]/strong[1]").click()
    #     self.driver.find_element(By.ID, "DepartDate").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[3]/td[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[5]/td[2]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@role='text']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='flightResults-content']/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[1]/div[4]/div[1]").click()
    #
    # def test_united_0fb36232(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[1]/fieldset[1]/div[1]/label[2]/span[2]").click()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("New York")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-1']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("Toronto")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #
    # def test_united_0b16b42c(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav4']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav4-panel']/div[1]/div[2]/ul[1]/li[2]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[4]/div[1]/div[1]/h3[6]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Within sight of downtown Miami, yet worlds away, Biscayne protects a rare combination of aquamarine waters, emerald islands and fish-bejeweled ...')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'Fly to Miami (MIA)')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='__next']/div[1]/div[2]/div[1]/article[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]").click()
    #     self.driver.find_element(By.ID, "flights-booking-popup-id-3").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='calendar-8']/div[1]/div[1]/div[2]/div[2]/div[3]/div[2]/div[7]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='calendar-8']/div[1]/div[1]/div[2]/div[1]/div[3]/div[3]/div[5]/div[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='modal']/div[1]/div[2]/div[1]/div[1]/div[3]/div[2]/div[1]/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='refundable']/span[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "wgcqmKjLW").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='flightResults-content']/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[2]/div[1]/div[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='flightResults-content']/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/button[1]/div[2]/div[1]/div[2]").click()
    #
    # def test_united_90a0f029(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav0']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav0-panel']/div[1]/div[1]/ul[1]/li[3]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//fieldset[@id='packageType32']/div[1]/div[1]/div[2]/label[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//fieldset[@id='fareClass133']/div[1]/div[1]/div[2]/label[1]").click()
    #     self.driver.find_element(By.ID, "vacationOriginInput").clear()
    #     self.driver.find_element(By.ID, "vacationOriginInput").send_keys("las vegas")
    #     self.driver.find_element(By.XPATH, "//li[@id='vacationOriginInput-menu-item-0']/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "vacationDestinationInput").clear()
    #     self.driver.find_element(By.ID, "vacationDestinationInput").send_keys("san francisco")
    #     self.driver.find_element(By.XPATH, "//li[@id='vacationDestinationInput-menu-item-0']/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@name='DepartDate' and @value='' and @type='text' and @placeholder='Departure']").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookVacationForm']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[3]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookVacationForm']/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[3]/td[6]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='containerId']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//input[@value='1' and @type='text']").clear()
    #     self.driver.find_element(By.XPATH, "//input[@value='1' and @type='text']").send_keys("1")
    #     self.driver.find_element(By.ID, "selectedRooms").click()
    #     self.driver.find_element(By.ID, "selectedRooms_item-0").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_united_bafd6a44(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav2']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav2-panel']/div[1]/div[2]/ul[1]/li[5]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='fly-component-2']/div[1]/div[1]/div[3]/div[1]/div[1]/a[1]/div[1]/div[1]/div[1]/p[1]").click()
    #
    # def test_united_d22ce493(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").click()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("BWI")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("NYC")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-1']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "DepartDate").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/button[2]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[1]/td[4]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[2]/td[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengerSelector']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengerMenuId']/div[1]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.ID, "travelTab-panel").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #
    # def test_united_28f6ac29(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav1']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav1-panel']/div[1]/div[1]/ul[1]/li[6]/a[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "radiofield-item-id-search-receipt-by-1").click()
    #     self.driver.find_element(By.ID, "PdtDT_-2y").clear()
    #     self.driver.find_element(By.ID, "PdtDT_-2y").send_keys("12345678")
    #     self.driver.find_element(By.ID, "8ZzxQL0jE").clear()
    #     self.driver.find_element(By.ID, "8ZzxQL0jE").send_keys("Jason")
    #     self.driver.find_element(By.ID, "v0gW_C4Bye").clear()
    #     self.driver.find_element(By.ID, "v0gW_C4Bye").send_keys("Two")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_united_2d18cb36(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "headerNav1").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav1-panel']/div[1]/div[1]/ul[1]/li[2]").click()
    #     self.driver.find_element(By.XPATH, "//a[@id='L2VuL3VzL21hbmFnZXJlcy9teXRyaXBzMQ']/span[1]").click()
    #     self.driver.find_element(By.ID, ".lastName").clear()
    #     self.driver.find_element(By.ID, ".lastName").send_keys("Atas")
    #     self.driver.find_element(By.ID, ".confirmationNumber_label").clear()
    #     self.driver.find_element(By.ID, ".confirmationNumber_label").send_keys("1000001")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_united_14f0e837(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='statusTab']/h2[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "flightStatusModel.flightNumber").clear()
    #     self.driver.find_element(By.ID, "flightStatusModel.flightNumber").send_keys("1234")
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #
    # def test_united_8b6eed27(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("MUMBAI")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]/strong[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("LONDON")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]/strong[1]").click()
    #     self.driver.find_element(By.ID, "DepartDate").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[1]/td[7]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengersSlidingInputContainer']/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[2]/td[4]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengerSelector']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengerMenuId']/div[1]/div[1]/div[1]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='passengerMenuId']/div[1]/div[2]/div[2]/div[1]/button[2]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='cabinType']/div[1]").click()
    #     self.driver.find_element(By.ID, "cabinType_item-1").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[3]/div[3]/div[4]/button[1]/span[1]").click()
    #
    # def test_united_4770e887(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("Pune")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("New York")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-1']/button[1]/span[1]/strong[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='flightResults-content']/div[3]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/button[1]/div[1]").click()
    #
    # def test_united_4aaf59c0(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav2']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav2-panel']/div[1]/div[1]/ul[1]/li[4]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'sit on a parent’s lap')]").click()
    #     self.driver.find_element(By.XPATH, "//a[contains(text(),'approved car seat')]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='fly-component-4']/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/h4[1]").click()
    #
    # def test_united_9e035a36(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightOriginInput").send_keys("SPRINGFIELD")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").clear()
    #     self.driver.find_element(By.ID, "bookFlightDestinationInput").send_keys("AUSTIN")
    #     self.driver.find_element(By.XPATH, "//li[@id='autocomplete-item-0']/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[1]/fieldset[1]/div[1]/label[2]/span[2]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='bookFlightForm']/div[5]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "NqSyIJ77pq").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/svg[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[5]/td[7]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[4]/div[3]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='flightResults-content']/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='flightResults-content']/div[3]/div[1]/div[1]/div[1]/div[2]/div[1]/div[5]/div[1]/button[2]/span[1]").click()
    #
    # def test_united_9ea9ac0d(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//li[@id='statusTab']/h2[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "flightStatusOriginInput").clear()
    #     self.driver.find_element(By.ID, "flightStatusOriginInput").send_keys("london")
    #     self.driver.find_element(By.XPATH, "//li[@id='flightStatusOriginInput-menu-item-0']/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "flightStatusDestinationInput").clear()
    #     self.driver.find_element(By.ID, "flightStatusDestinationInput").send_keys("new york")
    #     self.driver.find_element(By.XPATH, "//li[@id='flightStatusDestinationInput-menu-item-1']/button[1]/div[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//button[@id='datesDropdown']/div[1]").click()
    #     self.driver.find_element(By.ID, "datesDropdown_item-3").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='flightStatusModel']/div[1]/button[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='app']/div[1]/div[1]/div[1]/div[3]/div[2]/div[1]/section[1]/div[1]/div[2]/div[2]/div[4]/div[1]/div[5]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "upgrades").click()
    #
    # def test_united_ab23e83a(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.XPATH, "//a[@id='headerNav1']/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='headerNav1-panel']/div[1]/div[1]/ul[1]/li[5]/a[1]/span[1]").click()
    #     self.driver.find_element(By.XPATH, "//div[@id='G65qv-CdZ']/main[1]/div[1]/div[1]/form[1]/div[2]/section[1]/div[1]/section[1]/div[2]/div[2]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "31").clear()
    #     self.driver.find_element(By.ID, "31").send_keys("Lo")
    #     self.driver.find_element(By.ID, "30").clear()
    #     self.driver.find_element(By.ID, "30").send_keys("12345678912345")
    #     self.driver.find_element(By.XPATH, "/html/body[1]/div[5]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/button[1]").click()
    #     self.driver.find_element(By.ID, "5").clear()
    #     self.driver.find_element(By.ID, "5").send_keys("ian.lo@gmail.com")
    #     self.driver.find_element(By.XPATH, "//div[@id='G65qv-CdZ']/main[1]/div[1]/div[1]/form[1]/div[2]/div[2]/button[1]/span[1]").click()
    #
    # def test_united_af8a7016(self):
    #     # self.driver.get("https://www.united.com/en/us")
    #     self.driver.find_element(By.ID, "filterOriginInput").clear()
    #     self.driver.find_element(By.ID, "filterOriginInput").send_keys("Phoenix")
    #     self.driver.find_element(By.XPATH, "//li[@id='filterOriginInput-menu-item-0']/button[1]").click()
    #     self.driver.find_element(By.XPATH, "//form[@id='mapSearchForm']/div[2]/div[3]/button[1]/span[1]").click()
    #     self.driver.find_element(By.ID, "v06UXHinGN").click()
    #     self.driver.find_element(By.XPATH, "//dd[@id='ywoSwT-wld']/div[1]/div[1]/div[1]/ul[1]/li[13]/button[2]/div[2]/div[1]/span[1]").click()
    